{
 "title": "MinIO Overview",
 "description": "Overview of single MinIO cluster",
 "tags": [
  "Pigsty",
  "MINIO",
  "HOME",
  "OVERVIEW"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{cls='$cls'}, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds,cls)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MinIO Members",
   "type": "table",
   "description": "MinIO cluster members",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (cls,server,version) (minio_software_version_info{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server,ins,instance,ip) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n- max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "1 - \nmax by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"}) /\nmax by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_nodes_online_total{cls=\"$cls\"})",
     "legendFormat": "Nodes Online"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_drive_online_total{cls=\"$cls\"})",
     "legendFormat": "Disks Online"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"} / minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Usage%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_capacity_usable_total_bytes{cls=\"$cls\"})",
     "legendFormat": "Size Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_capacity_usable_total_bytes{cls=\"$cls\"} - \nminio_cluster_capacity_usable_free_bytes{cls=\"$cls\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{ins=\"$ins\"})",
     "legendFormat": "Buckets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{cls=\"$cls\"})",
     "legendFormat": "Objects"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "S3 API QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_total{cls=\"$cls\", ins=\"$ins\"}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "S3 ERROR QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_errors_total{cls=\"$cls\", ins=\"$ins\"}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "S3 API QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_s3_requests_total{ins=\"$ins\"}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "S3 ERROR QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_s3_requests_errors_total{cls=\"$cls\", ins=\"$ins\"}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_cluster_usage_object_total{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (range) (minio_cluster_objects_size_distribution{cls=\"$cls\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Transmit by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minio_s3_traffic_sent_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}->{{ server }}"
    }
   ]
  },
  {
   "title": "Receive by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minio_s3_traffic_sent_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}->{{ server }}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{ins=\"$ins\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{ins=\"$ins\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{ins=\"$ins\"}[1m])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{ins=\"$ins\"}[1m])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "MinIO Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,src) (count_over_time(({cls=\"$cls\", src=\"syslog\"} |~ \"minio\")[$__interval]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "MinIO Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "{cls=\"$cls\", src=\"syslog\"} |~ \"minio\""
    }
   ]
  }
 ]
}