{
 "title": "PGLOG Instance",
 "description": "PostgreSQL Log for Single Instance",
 "tags": [
  "Pigsty",
  "PGLOG",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": "label_values(ins)" },
   {
    "name": "src",
    "label": "Source",
    "query": "label_values({ins=\"$ins\"}, src)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "README", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "PGLOG requires **extra setup** to work, since logging system are optional.\n\n```bash\n./infra-loki.yml      # install loki on meta node\n./pgsql-promtail.yml  # deploy log agent on pgsql node\n```"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "options": {
    "content": "Select pgsql instance via `Instance`\n\nSelect log type (postgres|pgbouncer|patroni) by `Source`\n\nSearch keyword in logs with `Search` textbox."
   }
  },
  { "title": "Log Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", src=\"$src\"})[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", src=\"$src\"} |~ \"ERROR|FATAL|PANIC\")[$__interval]))",
     "legendFormat": "errs per $__interval"
    }
   ]
  },
  {
   "title": "Searched Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", src=\"$src\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  { "title": "Log Entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rencent Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{ins=\"$ins\", src=\"$src\"} |~ \"$search\""
    }
   ]
  }
 ]
}