#!/usr/bin/env bash
set -uo pipefail

#==============================================================#
# File      :   pg-init
# Ctime     :   2020-12-16
# Mtime     :   2020-12-21
# ATime     :   {{ '%Y-%m-%d %H:%M' | strftime }}
# Desc      :   init postgres cluster (after creation)
# Path      :   /pg/bin/pg-init
# Depend    :   psql, /pg/tmp/pg-init-*.sql
# Author    :   Vonng(fengruohang@outlook.com)
# Copyright (C) 2018-2022 Ruohang Feng
#==============================================================#

PROG_NAME="$(basename $0)"
PROG_DIR="$(cd $(dirname $0) && pwd)"


#==================================================================#
#                          Default Roles                           #
#==================================================================#
psql postgres -qAXwtf /pg/tmp/pg-init-roles.sql


#==================================================================#
#                          System Template                         #
#==================================================================#
# system default template
psql template1 -qAXwtf /pg/tmp/pg-init-template.sql

# make postgres same as templated database (optional)
psql postgres  -qAXwtf /pg/tmp/pg-init-template.sql



#==================================================================#
#                          Customize Logic                         #
#==================================================================#
# add your template logic here
