{
 "title": "Nodes Alert",
 "description": "Nodes Alert",
 "tags": [
  "Pigsty",
  "INFRA",
  "NODES",
  "Overview",
  "Alert"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"nodes\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", job=\"nodes\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"nodes\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=\"nodes\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{job=\"nodes\"}"
    }
   ]
  },
  { "title": "NODES : CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "NodeCpuHigh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:cpu_usage_1m", "legendFormat": "{{ ip }}" }
   ]
  },
  {
   "title": "NODES: Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeLoadHigh",
     "type": "timeseries",
     "description": "Standard Load (divide by cpu count) > 100%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:stdload1", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODES: Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeOutOfMem",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:mem_avail", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODES: Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeMemSwapped",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:swap_usage", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODES : Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeDiskSlow",
     "type": "timeseries",
     "description": "Disk read/write avg latency > 32ms",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (ip,device) (node:dev:disk_write_rt_1m > node:dev:disk_read_rt_1m or node:dev:disk_read_rt_1m)",
       "legendFormat": "{{ ip}}-{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODES : Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeFsFull",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:space_usage", "legendFormat": "{{ ip }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsExhaust",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "node:fs:space_exhaust{}", "legendFormat": "{{ ip }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsFilesFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:inode_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFdFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:fd_usage", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODES: Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeTcpErrHigh",
     "type": "timeseries",
     "description": "TCP Error Rate > 1 / s",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      { "expr": "rate(node:ins:tcp_error[1m])", "legendFormat": "{{ ip }}" }
     ]
    },
    {
     "title": "NodeTcpRetransHigh",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      { "expr": "node:ins:tcp_retrans_ratio1m", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODES: NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeNtpSanity",
     "type": "timeseries",
     "description": "Check ntp protocol / clock sanity",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min without() (node_ntp_sanity or node_timex_sync_status)",
       "legendFormat": "{{ ip }}"
      }
     ]
    },
    {
     "title": "NodeClockSkew",
     "type": "timeseries",
     "description": "Clock time offset alert > 50ms",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "abs(node_timex_offset_seconds)", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  }
 ]
}