#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   docker.yml
# Desc      :   init docker on nodes
# Ctime     :   2023-02-20
# Mtime     :   2023-02-20
# Path      :   docker.yml
# Author    :   Ruohang Feng (rh@vonng.com)
# License   :   AGPLv3
#==============================================================#
- name: DOCKER INIT
  hosts: all
  gather_facts: no
  become: yes
  vars:
    docker_enabled: true                # enable docker on this node?
    # docker_cgroups_driver: systemd    # docker cgroup fs driver: cgroupfs,systemd
    # docker_registry_mirrors: [ ]      # docker registry mirror list
    # docker_image_cache: /tmp/docker   # docker image cache dir, `/tmp/docker` by default
  roles:
    - { role: node_id , tags: id     }  # get node identity (always)
    - { role: docker  , tags: docker }  # prepare node for pigsty

#---------------------------------------------------------------
# Usage
#---------------------------------------------------------------
# simply run this playbook on nodes to init docker on them
#
# ./docker.yml -l <group|host>
#
# docker images on /tmp/docker/*.tgz will be loaded automatically
# you can add registry mirror to `docker_registry_mirrors` to accelerate
#---------------------------------------------------------------
# Tasks
#---------------------------------------------------------------
# docker               : setup docker on node to run containers (optional)
#   - docker_install   : install docker on nodes
#   - docker_admin     : add user to docker admin group
#   - docker_config    : generate docker daemon
#   - docker_launch    : launch docker daemon systemd service
#   - docker_image     : load docker images from /tmp/docker/*.tgz if exists
#---------------------------------------------------------------
...