#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   infra-demo.yml
# Ctime     :   2021-01-19
# Mtime     :   2022-04-28
# Desc      :   init demo on sandbox nodes (one-pass bootstrap)
# Path      :   infra-demo.yml
# Copyright (C) 2018-2022 Ruohang Feng (rh@vonng.com)
#==============================================================#

#---------------------------------------------------------------
# Notice
#---------------------------------------------------------------
# This is a special playbook that interleave infra.yml & pgsql.yml
# It is used for 4-node demo, or in case that there are multiple
# meta nodes also reused as common database nodes.
#
# to init multiple meta nodes, add their ip address to pigsty.yml
#   all.children.meta.hosts
#
# if offline installation packages is used, you can also copy them to
#   copy /www/pigsty to all meta nodes before run ./demo.yml
#---------------------------------------------------------------

#---------------------------------------------------------------
# setup meta node identity
#---------------------------------------------------------------
- name: Node Identity
  hosts: all
  gather_facts: no
  tags: [ always, node-id ]
  connection: local
  tasks:

    # overwrite nodes identity with pgsql identity if pg_hostname is true
    - name: Overwrite node_cluster
      when: (pg_hostname is defined and pg_hostname|bool) and (node_cluster is not defined or node_cluster == 'nodes' or node_cluster == '') and (pg_cluster is defined and pg_cluster != '')
      set_fact: { node_cluster: "{{ pg_cluster }}" }  # use pg_cluster as non-trivial node_cluster name

    - name: Overwrite nodename
      when: (pg_hostname is defined and pg_hostname|bool) and (nodename is not defined or nodename == '') and (pg_cluster is defined and pg_cluster != '' and pg_seq is defined)
      set_fact: { nodename: "{{ pg_cluster }}-{{ pg_seq }}" }

    - debug: { msg: "ins={{ nodename|default('NULL') }} cls={{ node_cluster|default('NULL') }}" }

#---------------------------------------------------------------
# bootstrap meta node with local yum repo
#---------------------------------------------------------------
- name: Infra Bootstrap
  become: yes
  hosts: meta
  gather_facts: no
  tags: infra-boot
  roles:
    - role: environ             # setup environment on meta nodes
      tags: environ

    - role: ca                  # init self-signed ca-infrastructure
      tags: ca

    - role: repo                # setup local yum repo on meta nodes
      tags: repo                # you can disable repo on extra meta nodes with nginx_enabled: false
      when: nginx_enabled|bool


#---------------------------------------------------------------
# init node & dcs
#---------------------------------------------------------------
- name: Node Init
  become: yes
  hosts: all
  gather_facts: no
  tags: node-init
  roles:

    - role: node            # init meta node itself
      tags: [ node , node-init ]



    - role: docker          # init docker if enabled
      tags: docker
      when: docker_enabled|bool

    - role: consul          # init consul if enabled
      tags: [ dcs, consul ]
      when: consul_enabled|bool

    - role: etcd            # init etcd if enabled
      tags: [ dcs, etcd ]
      when: etcd_enabled|bool


#---------------------------------------------------------------
# init infrastructure on meta nodes
#---------------------------------------------------------------
- name: Setup Infrastructure on meta nodes
  become: yes
  hosts: meta
  gather_facts: no
  tags: infra
  roles:

    - role: nameserver    # init dns nameserver
      tags: nameserver
      # when: nameserver_enabled|bool

    - role: nginx           # init nginx
      tags: nginx
      # when: nginx_enabled|bool

    - role: prometheus      # init prometheus
      tags: prometheus
      # when: prometheus_enabled|bool

    - role: grafana         # init grafana
      tags: grafana
      # when: grafana_enabled|bool

    - role: loki            # init loki
      tags: loki
      # when: loki_enabled|bool

    - role: infra_register
      tags: infra_register

#---------------------------------------------------------------
# Node Monitor
#---------------------------------------------------------------
- name: Node Monitor
  become: yes
  hosts: all
  gather_facts: no
  tags: node-monitor
  roles:

    # init & register node exporter
    - role: node_exporter
      tags: node-exporter
      when: node_exporter_enabled|bool

    # init & register promtail log agent
    - role: promtail
      tags: promtail
      when: promtail_enabled|bool

    # register node-exporter & docker to prometheus
    - role: node_register
      tags: node-register

#---------------------------------------------------------------
# init cmdb(s) on meta nodes
#---------------------------------------------------------------
- name: PGSQL Init     # init pgsql cmdb on meta nodes
  become: yes
  hosts: all
  gather_facts: no
  tags: [ pgsql-init ]
  vars:
    no_cmdb: false          # command line args (-e no_cmdb=true)
  roles:

    - role: postgres        # init postgres pgbouncer patroni
      when: not no_cmdb|bool
      tags: postgres

    - role: service         # init service , haproxy , vip
      when: not no_cmdb|bool
      tags: service

    - role: pg_exporter     # init monitor exporters
      when: not no_cmdb|bool
      tags: pg-exporter

    - role: pg_register     # register cluster/instance to infra
      when: not no_cmdb|bool
      tags: pg-register

#---------------------------------------------------------------
...
