#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   infra-remove.yml
# Ctime     :   2022-02-22
# Mtime     :   2022-03-20
# Desc      :   uninstall pigsty from meta nodes
# Path      :   infra-remove.yml
# Copyright (C) 2018-2022 Ruohang Feng (rh@vonng.com)
#==============================================================#

#---------------------------------------------------------------
# Usage
#---------------------------------------------------------------
# ./infra-remove.yml -t pgsql     # remove cmdb on meta node
#
# ./infra-remove.yml -t infra     # remove infra on meta node
# ./infra-remove.yml -t infra-svc # stop & disable meta services
# ./infra-remove.yml -e rm_metadata=true   # remove pigsty data
# ./infra-remove.yml -e rm_metadpkgs=true  # remove meta pkgs too
# ./infra-remove.yml -e rm_metadata=true -e rm_metadpkgs=true  #
#---------------------------------------------------------------

#------------------------------------------------------------------------------
# Remove CMDB
#------------------------------------------------------------------------------
- name: PGSQL Remove
  become: yes
  hosts: meta
  tags:  [ cmdb , pgsql-remove ]
  gather_facts: no
  ignore_errors: yes
  vars:
    rm_dcs_server: true     # remove dcs server? false by default
    rm_pgdata: false        # remove postgres data? false by default
    rm_pgpkgs: true         # uninstall pg_packages? false by default
  roles:
    - role: pg_remove
      tags: pg-remove

#------------------------------------------------------------------------------
# Remove Infrastructure
#------------------------------------------------------------------------------
- name: Infra Remove
  become: yes
  hosts: meta
  tags: infra
  gather_facts: no
  ignore_errors: yes
  vars:
    rm_metadata: false        # remove metadata on meta nodes? false by default
    rm_metapkgs: false        # uninstall node_meta_packages? false by default

  tasks:

    #---------------------------------------------
    # Stop Service
    #---------------------------------------------
    - name: Stop and disable systemd infra service
      systemd: name={{ item }} state=stopped enabled=no daemon_reload=yes
      tags: infra-svcs
      with_items:
        - grafana-server
        - prometheus
        - alertmanager
        - node_exporter
        - consul
        - jupyter
        - pgweb
        - loki
        - promtail

    #---------------------------------------------
    # Remove Data
    #---------------------------------------------
    - name: Remove infra data on meta nodes
      file: state=absent path="{{ item }}"
      tags: infra-data
      when: rm_metadata|bool
      with_items:
        - /etc/pigsty
        - /etc/prometheus/targets
        - /etc/nginx/conf.d/
        - /var/lib/grafana
        - "{{ repo_home }}"
        - "{{ pg_data }}"
        - "{{ prometheus_data_dir }}"
        - "{{ consul_data_dir }}"

    #---------------------------------------------
    # Remove Packages
    #---------------------------------------------
    - name: Uninstall meta packages
      yum: name={{ item }} state=removed
      tags: infra-pkgs
      when: rm_metapkgs|bool
      with_items:
        - prometheus2
        - grafana
        - alertmanager
        - loki
        - nginx
        - consul

...