#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   supabase.yml
# Desc      :   init supabase cluster
# Ctime     :   2024-11-24
# Mtime     :   2024-11-24
# Path      :   supabase.yml
# License   :   AGPLv3 @ https://pigsty.io/docs/about/license
# Copyright :   2018-2024  Ruohang Feng / Vonng (rh@vonng.com)
#==============================================================#

# [OPTIONAL], copy local supabase docker images
# put docker saved *.tgz tarball under /tmp/supabase
- name: SUPABASE IMAGE
  become: yes
  hosts: supabase
  tags: [ supa-image, image ]
  gather_facts: no
  tasks:
    - name: copy local docker images
      copy: src="{{ item }}" dest="/tmp/docker/"
      with_fileglob: "{{ supa_images }}"
      vars: # you can override this with -e cli args
        supa_images: /tmp/supabase/*.tgz


# install docker on the hard-coded `supabase` group
- name: SUPABASE DOCKER
  become: yes
  hosts: supabase
  gather_facts: no
  tags: docker
  roles:
    - role: node_id
    - role: docker


# install supabase with docker compose
- name: SUPABASE INSTALL
  become: yes
  hosts: supabase
  gather_facts: no
  tags: supa-init
  tasks:

    # copy app/supabase to /opt/supabase
    - name: copy supabase app dir
      tags: supa_copy
      copy: src="{{ playbook_dir }}/app/supabase" dest=/opt/supabase

    # copy app/supabase to /opt/supabase
    - name: overwrite supabase config
      tags: supa_config
      lineinfile:
        path: /opt/supabase/.env
        regexp: '^{{ item.key | upper }}='
        line: '{{ item.key | upper }}={{ item.value }}'
        create: yes
      loop: "{{ supa_config | dict2items }}"

    # it may take a while to pull images, or very fast if you already have local image loaded
    - name: start supabase
      tags: supa_launch
      shell:
        cmd: docker compose up -d
        chdir: /opt/supabase
        warn: no

...