{
 "title": "PGCAT Database",
 "description": "PostgreSQL Catalog Explorer for Single Database",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn}';" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate, datallowconn,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,\n       t.spcname as tablespace\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nWHERE d.datname = '$datname'\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT unnest(datacl) AS name FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Recovery status of this instance",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_is_in_recovery()::INTEGER AS recovery"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Database OID of ${datname}",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT oid FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT json_object_agg(kind, count) AS data\n         FROM (SELECT relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY 1) d\n     ) j;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT pg_catalog.shobj_description(d.oid, 'pg_database') as description FROM pg_database d WHERE datname = '$datname';"
    }
   ]
  },
  {
   "title": "Schemas",
   "type": "table",
   "description": "Schemas of current database ${datname}",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n       relnamespace AS \"OID\", nspname AS \"Schema\", nspowner::RegRole::TEXT AS \"Owner\",\n       coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT relnamespace, json_object_agg(kind, count) AS data\n         FROM (SELECT relnamespace, relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY 1,2) d\n         GROUP BY 1\n     ) j LEFT JOIN pg_namespace nsp ON j.relnamespace = nsp.oid\nWHERE nspname NOT IN ('pg_toast', 'information_schema', 'pg_catalog');"
    }
   ]
  },
  {
   "title": "Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tables",
     "type": "table",
     "description": "Tables of current database ${datname}",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "SELECT * FROM pg_class;",
       "rawSql": "SELECT c.oid                                                AS \"OID\",\n       n.nspname                                            as \"Schema\",\n       n.nspname || '.' || c.relname                        as \"Name\",\n       CASE WHEN relispartition THEN 'P' ELSE c.relkind END AS \"Kind\",\n       age(c.relfrozenxid)::FLOAT / 2147483648              AS relage,\n       reltuples,\n       relpages,\n       relfilenode,\n       pg_table_size(c.oid)                                 AS \"Size\",\n       relnatts, s.*\nFROM pg_catalog.pg_class c\n         LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n         LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid\nWHERE c.relkind IN ('r', 'p', '')\n  AND n.nspname <> 'pg_catalog'\n  AND n.nspname !~ '^pg_toast'\n  AND n.nspname <> 'information_schema'\nORDER BY 1, 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexes",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || indexrelname   AS \"Name\", \n       *,\n       pg_get_indexdef(indexrelid) AS def\nFROM pg_stat_user_indexes;"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all heap tables",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM monitor.pg_table_bloat;"
      }
     ]
    },
    {
     "title": "Index Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all btree indexes",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM monitor.pg_index_bloat;"
      }
     ]
    },
    {
     "title": "Table Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, nspname, size * ratio AS waste, ratio FROM monitor.pg_table_bloat;"
      }
     ]
    },
    {
     "title": "Index Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, nspname, size * ratio AS waste, ratio FROM monitor.pg_index_bloat;"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT *,\n  extract(epoch from now() - backend_start) AS conn_time,\n  extract(epoch from now() - xact_start)    AS xact_time,\n  extract(epoch from now() - query_start)   AS query_time,\n  extract(epoch from now() - state_change)  AS state_time\nFROM pg_stat_activity Where datname = '$datname';"
      }
     ]
    },
    {
     "title": "Sessions (by Type)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(backend_type, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(backend_type, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by State)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(state, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(state, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Wait Event)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(wait_event, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(wait_event, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Client Addr)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(client_addr::text, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(client_addr::text, 'null');\n"
      }
     ]
    },
    {
     "title": "Sessions (by User)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(usename, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(usename, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by App)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(application_name, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Statements",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\nLEFT JOIN pg_database d ON s.dbid = d.oid\n     LEFT JOIN pg_roles r ON s.userid = r.oid \nWHERE datname='$datname'     \nORDER BY rows DESC LIMIT 200;"
      }
     ]
    },
    {
     "title": "Query (by Time Spent)",
     "type": "marcusolsson-treemap-panel",
     "description": "Area represent time spent\ncolor represent RT of this query",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT                     AS query,\n       sum(total_exec_time)              AS time_spent,\n       sum(calls)                        AS calls,\n       sum(total_exec_time) / sum(calls) AS rt\nFROM (\n         SELECT queryid, total_exec_time, calls\n         FROM monitor.pg_stat_statements s\n         WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '$datname')\n         ORDER BY rows DESC\n         LIMIT 200\n     ) raw\nWHERE calls > 0\nGROUP BY 1\nORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "Query (by Total Calls)",
     "type": "marcusolsson-treemap-panel",
     "description": "Area represent call counts\ncolor represent RT of this query",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT                     AS query,\n       sum(total_exec_time)              AS time_spent,\n       sum(calls)                        AS calls,\n       sum(total_exec_time) / sum(calls) AS rt\nFROM (\n         SELECT queryid, total_exec_time, calls\n         FROM monitor.pg_stat_statements s\n         WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '$datname')\n         ORDER BY rows DESC\n         LIMIT 200\n     ) raw\nWHERE calls > 0\nGROUP BY 1\nORDER BY 2 DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Logical Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Slots (Logical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'logical';"
      }
     ]
    },
    {
     "title": "Subscription",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_subscription;"
      }
     ]
    },
    {
     "title": "Publication",
     "type": "stat",
     "description": "Publication Information\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_publication;" }
     ]
    }
   ]
  }
 ]
}