{
 "title": "PGCAT Instance",
 "description": "PostgreSQL Catalog Explorer for Single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn}';" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. ",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Recovery status of this instance",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_is_in_recovery()::INTEGER AS recovery"
    }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Database OID of ${datname}",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT oid FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "title": "Cluster Identifier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select system_identifier FROM pg_control_system();"
    }
   ]
  },
  {
   "title": "Cluster Created At",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select to_timestamp(((system_identifier>>32) & (2^32 -1)::bigint)) AS created FROM pg_control_system();"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (SELECT count(*) AS databases FROM pg_database) d,\n     (SELECT count(*) AS roles FROM pg_roles) r,\n     (SELECT count(*) AS tablespaces FROM pg_tablespace) tsp,\n     (SELECT count(*) AS schemas FROM pg_namespace) nsp,\n     (SELECT count(*) AS relations FROM pg_class WHERE relkind in ('r','m','p')) rc,\n     (SELECT count(*) AS indexes FROM pg_class WHERE relkind = 'i') ic,\n     (SELECT count(*) AS sequences FROM pg_class WHERE relkind = 'S') sc,\n     (SELECT count(*) AS views FROM pg_class WHERE relkind = 'v') vc;\n;"
    }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Roles of this database",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT r.oid, r.rolname, r.rolsuper, r.rolinherit,\n       r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,\n       r.rolconnlimit, r.rolvaliduntil,\n       ARRAY(SELECT b.rolname\n             FROM pg_catalog.pg_auth_members m\n                      JOIN pg_catalog.pg_roles b ON (m.roleid = b.oid)\n             WHERE m.member = r.oid) as memberof\n        , pg_catalog.shobj_description(r.oid, 'pg_authid') AS description\n        , r.rolreplication\n        , r.rolbypassrls\nFROM pg_catalog.pg_roles r\nWHERE r.rolname !~ '^pg_'\nORDER BY 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT *,\n  extract(epoch from now() - backend_start) AS conn_time,\n  extract(epoch from now() - xact_start)    AS xact_time,\n  extract(epoch from now() - query_start)   AS query_time,\n  extract(epoch from now() - state_change)  AS state_time\nFROM pg_stat_activity;"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions (by Type)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(backend_type, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(backend_type, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by State)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(state, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(state, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Wait Event)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(wait_event, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(wait_event, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Client Addr)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(client_addr::text, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(client_addr::text, 'null');\n"
      }
     ]
    },
    {
     "title": "Sessions (by User)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(usename, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(usename, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by App)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(application_name, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Statements",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\nLEFT JOIN pg_database d ON s.dbid = d.oid\n     LEFT JOIN pg_roles r ON s.userid = r.oid ORDER BY rows DESC LIMIT 200;"
      }
     ]
    },
    {
     "title": "Query (by Time Spent)",
     "type": "marcusolsson-treemap-panel",
     "description": "Area represent time spent\ncolor represent RT of this query",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS query, sum(total_exec_time) AS time_spent, sum(calls) AS calls, \n       sum(total_exec_time) / sum(calls) AS rt \nFROM\n(SELECT queryid, total_exec_time, calls FROM monitor.pg_stat_statements s ORDER BY rows DESC LIMIT 200) raw\nWHERE calls > 0\nGROUP BY 1 ORDER BY 2 DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postmaster",
     "type": "stat",
     "description": "These settings can only be applied when the server starts",
     "gridPos": { "h": 22, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'postmaster'"
      }
     ]
    },
    {
     "title": "Internal",
     "type": "stat",
     "description": "These settings cannot be changed directly; they reflect internally determined values. Some of them may be adjustable by rebuilding the server with different configuration options, or by changing options supplied to initdb.",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'internal'"
      }
     ]
    },
    {
     "title": "Changed",
     "type": "table",
     "description": "These settings that has non-default values",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT name,setting,source,context,pending_restart FROM pg_settings;"
      }
     ]
    },
    {
     "title": "Init Parameters",
     "type": "stat",
     "description": "Info from pg_control_system",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_init();"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE name in ('archive_command', 'primary_conninfo')"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Stats",
     "type": "table",
     "description": "The pg_stat_replication view will contain one row per WAL sender process, showing statistics about replication to that sender's connected standby server. Only directly connected standbys are listed; no information is available about downstream standby servers.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT application_name                                                 AS appname,\n       usename,\n       coalesce(abbrev(client_addr), 'localhost') || ':' || client_port AS address,\n       pid,\n       state,\n       sync_state,\n       sync_priority,\n       backend_xmin::TEXT::BIGINT                                       AS backend_xmin,\n       current.lsn - '0/0'                                              AS lsn,\n       current.lsn - sent_lsn                                           AS sent_diff,\n       current.lsn - write_lsn                                          AS write_diff,\n       current.lsn - flush_lsn                                          AS flush_diff,\n       current.lsn - replay_lsn                                         AS replay_diff,\n       coalesce(extract(EPOCH FROM write_lag), 0)                       AS write_lag,\n       coalesce(extract(EPOCH FROM flush_lag), 0)                       AS flush_lag,\n       coalesce(extract(EPOCH FROM replay_lag), 0)                      AS replay_lag,\n       extract(EPOCH FROM current_timestamp)                            AS \"time\",\n       extract(EPOCH FROM backend_start)                                AS launch_time,\n       extract(EPOCH FROM reply_time)                                   AS reply_time\nFROM pg_stat_replication,\n     (SELECT CASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END AS lsn) current;"
      }
     ]
    },
    {
     "title": "Replication Slots (Physical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'physical';"
      }
     ]
    },
    {
     "title": "Replication Slots (Logical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'logical';"
      }
     ]
    },
    {
     "title": "WAL Receiver (Replica Only)",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_wal_receiver;"
      }
     ]
    },
    {
     "title": "Subscription",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_subscription;"
      }
     ]
    },
    {
     "title": "Publication",
     "type": "stat",
     "description": "Publication Information\n",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_publication;" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(name, 'Free') AS name, off AS offset, allocated_size AS size FROM monitor.pg_shmem();"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "piechart",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, coalesce(name, 'Free') AS name, allocated_size AS size FROM monitor.pg_shmem() ORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "marcusolsson-treemap-panel",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, coalesce(name, 'Free') AS name, allocated_size AS size FROM monitor.pg_shmem() ORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "pg_stat_slru",
     "type": "table",
     "description": "PostgreSQL accesses certain on-disk information via SLRU (simple least-recently-used) caches. The pg_stat_slru view will contain one row for each tracked SLRU cache, showing statistics about access to cached pages.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 18 },
     "targets": [
      { "rawSql": "SELECT * FROM pg_stat_slru;" }
     ]
    }
   ]
  },
  {
   "title": "Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "pg_control_checkpoint",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_checkpoint();"
      }
     ]
    },
    {
     "title": "pg_control_system",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_system();"
      }
     ]
    },
    {
     "title": "pg_stat_bgwriter",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_bgwriter;"
      }
     ]
    },
    {
     "title": "pg_stat_wal",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_stat_wal;" }
     ]
    },
    {
     "title": "pg_control_recovery",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_recovery();"
      }
     ]
    }
   ]
  }
 ]
}