{
 "title": "PGSQL Replication",
 "description": "PostgreSQL Replication of Single cluster",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "description": "Leader of cluster ${cls} is ${primary}",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    },
    {
     "expr": "max by (ins, primary_conninfo) (pg_meta_info{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "CLS ID",
   "type": "stat",
   "description": "ip = ${ip}. Unique identifier for corresponding node",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster_id)(pg_meta_info{ins=\"$primary\"})",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (pg_meta_info{ins=\"$primary\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Cluster Status: 0 : Leaderless,  1 : OK,  2+ : Partitioned",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:partition{cls=\"$cls\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "description": "Cluster size ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg:cls:members{cls=\"$cls\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "leader: {{ ins }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_bytes{cls=\"$cls\"}",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_seconds{cls=\"$cls\"}",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_repl_replay_lag{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_lsn{cls=\"$cls\"} - pg_repl_sent_lsn{cls=\"$cls\"}",
     "legendFormat": "[SENT] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_sent_lsn{cls=\"$cls\"} - pg_repl_write_lsn{cls=\"$cls\"}",
     "legendFormat": "[WRITE] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_write_lsn{cls=\"$cls\"} - pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[FLUSH] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"} - pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[REPLAY] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds (Follower's View)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_lag{cls=\"$cls\"}",
     "legendFormat": "→ {{ ins }}"
    }
   ]
  },
  { "title": "LSN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Replication LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"}",
     "legendFormat": "replay @ {{ appname }}"
    },
    {
     "expr": "pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "flush @ {{ appname }}"
    },
    {
     "expr": "pg_repl_write_lsn{cls=\"$cls\"}",
     "legendFormat": "write @ {{ appname }}"
    },
    {
     "expr": "pg_slot_restart_lsn{cls=\"$cls\"}",
     "legendFormat": "slot restart @ {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Checkpoint LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{ins=\"$primary\"}",
     "legendFormat": "Checkpoint Leader $primary"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "Checkpoint Follower {{ ins }}"
    },
    {
     "expr": "pg_checkpoint_redo_lsn{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "Redo {{ ins }}"
    }
   ]
  },
  {
   "title": "LSN Progress Rate 1m",
   "type": "timeseries",
   "description": "Rate of lsn in last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "XMax Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cls=\"$cls\"}",
     "legendFormat": "xmax-{{ ins }}"
    },
    {
     "expr": "pg_xact_xmin{cls=\"$cls\"}",
     "legendFormat": "xmin-{{ ins }}"
    }
   ]
  },
  {
   "title": "Xmin Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_xact_xmin{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "XMin Horizon",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_xact_xmax{cls=\"$cls\"})",
     "legendFormat": "XMax"
    },
    {
     "expr": "pg_repl_backend_xmin{cls=\"$cls\"}",
     "legendFormat": "repl: {{ appname }}"
    },
    {
     "expr": "pg_slot_catalog_xmin{cls=\"$cls\"}",
     "legendFormat": "slot: {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Xact in Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_xact_xnum{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Slot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Replication Slots",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max by (ins, slot_name, datname) (pg_slot_retained_bytes{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_active{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_temporary{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_wal_status{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_restart_lsn{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Slot Retained Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} reserved for {{ slot_name }}"
    }
   ]
  },
  { "title": "Logical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } }
 ]
}