{
 "title": "PGSQL Database",
 "description": "PostgreSQL Database Overview",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cls}",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{ins=\"$ins\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{ins=\"$ins\"} + pg_db_allow_conn{ins=\"$ins\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$ins\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$ins\"})",
     "legendFormat": "Conn Limit"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:status{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Database OID",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_datid{ins=\"$ins\", datname=\"$datname\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_numbackends{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Database of this cluster ${cls}",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  { "title": "${datname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "datname" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_rollback_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:ixact_backends{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "iXact"
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "timeseries",
   "description": "Scan on all tables on this database",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_numbackends{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:age{ins=\"$ins\", datname=\"$datname\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "HitRate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg:db:tup_fetched_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Tup Access"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_temp_bytes{ins=\"$ins\", datname=\"$datname\"}[5m]))",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_class_relsize{ins=\"$ins\", datname=\"$datname\", relkind=\"r\"})"
    }
   ]
  },
  {
   "title": "Query",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query)(increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[15m])) / 1000",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[15m]))",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_servers{ins=\"$ins\",datname=\"$datname\"})",
     "legendFormat": "Pool Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_clients{ins=\"$ins\",datname=\"$datname\"})",
     "legendFormat": "Pool Client"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_database_current_connections{ins=\"$ins\", datname=\"$datname\"}) / sum(pgbouncer_database_max_connections{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Conn Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stat_avg_query_time{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:xact_rt_1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Xact RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pgbouncer_pool_waiting_clients{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rate1m{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rt_1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Query RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:rx_rate1m{ins=\"$ins\", datname=\"$datname\"}) + sum(pgbouncer:db:tx_rate1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Traffic"
    }
   ]
  }
 ]
}