{
 "title": "PGSQL Databases",
 "description": "PostgreSQL Databases",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Data Source", "query": "prometheus" },
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{cls=\"$cls\"}, datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "description": "Business Database among this cluster\nValue means current connections\n\nClick goes to PGSQL Database Dashboard",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_db_numbackends{cls=\"$cls\", datname!~\"wal|log|postgres|template\\\\d\"})",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"}) / sum by (datname) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cls=\"$cls\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cls=\"$cls\", datname!=\"pgbouncer\"})",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:xact_commit_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:xact_rollback_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:xact_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_rate1m{cls=\"$cls\",datname=\"$datname\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_time_rate1m{cls=\"$cls\",  datname=\"$datname\"}) / sum(pgbouncer:db:query_rate1m{cls=\"$cls\",  datname=\"$datname\"})",
     "legendFormat": "Query RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_clients{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Pool Client"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_servers{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_numbackends{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pgbouncer_pool_waiting_clients{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:ixact_backends{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "iXact"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:age{cls=\"$cls\", datname=\"$datname\"}) / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "TPS (Commit + Rollback)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins!=\"$primary\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Query RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_time_rate1m{cls=\"$cls\", datname=\"$datname\"}) / \nsum(pgbouncer:db:query_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Row Fetched",
   "type": "timeseries",
   "description": "Tuples fetched from databases",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_fetched{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "rate(pg_db_tup_fetched{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Row Modified",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$primary\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$primary\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$primary\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{cls=\"$cls\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "SAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_max_tx_duration{cls=\"$cls\", ins=\"$primary\", state=\"active\"})",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "sum by (ins) (pg_activity_max_tx_duration{cls=\"$cls\", ins!=\"$primary\", state=\"active\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Active Clients (Pgbouncer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer:db:active_clients{cls=\"$cls\", ins=\"primary\", datname=\"$datname\"})",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "sum by (ins) (pgbouncer:db:active_clients{cls=\"$cls\", ins!=\"primary\",  datname=\"$datname\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "pg:db:blks_hit_ratio1m{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Active Servers (Pgbouncer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer:db:active_servers{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pool_mode,user,datname) (pgbouncer_pool_active_clients{cls=\"$cls\"})",
     "legendFormat": "[{{ pool_mode }}]] {{ user }}@{{ datname }}"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "max by (relname, relid) (pg_table_relid{ns=\"$primary\"})",
     "legendFormat": "OID"
    },
    {
     "expr": "max by (relname) (pg_table_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Table Size"
    },
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Table Scan"
    },
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Primary Scan"
    },
    {
     "expr": "sum by (relname) (pg_table_seq_scan{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Seq Scan"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_tup_read{cls=\"$cls\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Read"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_n_tup_mod{cls=\"$cls\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Mod"
    },
    {
     "expr": "max by (relname) (pg_table_n_live_tup{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Tup Live"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Tup Dead"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"} / \n(pg_table_n_live_tup{ins=\"$primary\", datname=\"$datname\"} + pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"}))",
     "legendFormat": "Dead%"
    }
   ]
  },
  {
   "title": "Table Size & Access",
   "type": "marcusolsson-treemap-panel",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (relname) (pg_table_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ relname }}"
    },
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Scan (scan/s)",
   "type": "timeseries",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    rate(pg_table_tup_read{cls=\"$cls\", datname=\"$datname\"}[1m])\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Statementes",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins, query) (pg_query_calls{cls=\"$cls\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (pg_query_exec_time{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (rate(pg_query_rows{cls=\"$cls\", datname=\"$datname\"}[5m])\n/ rate(pg_query_calls{cls=\"$cls\", datname=\"$datname\"}[5m])\n)",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (rate(pg_query_wal_bytes{cls=\"$cls\", datname=\"$datname\"}[5m]) / rate(pg_query_calls{cls=\"$cls\", datname=\"$datname\"}[5m])\n)",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Time Spent & RT",
   "type": "marcusolsson-treemap-panel",
   "description": "Area represent time spent in last 1h\ncolor represent RT of this query",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{cls=\"$cls\", datname=\"$datname\"}[1h])",
     "rawSql": "SELECT queryid::TEXT AS query, sum(total_exec_time) AS time_spent, sum(calls) AS calls, \n       sum(total_exec_time) / sum(calls) AS rt \nFROM\n(SELECT queryid, total_exec_time, calls FROM monitor.pg_stat_statements s ORDER BY rows DESC LIMIT 200) raw\nWHERE calls > 0\nGROUP BY 1 ORDER BY 2 DESC;"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"})",
     "rawSql": "SELECT queryid::TEXT AS query, sum(total_exec_time) AS time_spent, sum(calls) AS calls, \n       sum(total_exec_time) / sum(calls) AS rt \nFROM\n(SELECT queryid, total_exec_time, calls FROM monitor.pg_stat_statements s ORDER BY rows DESC LIMIT 200) raw\nWHERE calls > 0\nGROUP BY 1 ORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{cls=\"$cls\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}