{
 "title": "PGSQL Activity",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Data Source", "query": "prometheus" },
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Pressure 1m",
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cls:pressure1{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CPU Usage 1m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:cpu_usage_1m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg_up{cls=\"$cls\"} * 0 + on(ip) node:ins:disk_read_bytes_rate1m",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "pg_up{cls=\"$cls\"} * 0 - on(ip) node:ins:disk_write_bytes_rate1m",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:network_tx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:network_rx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Postgres Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{cls=\"$cls\", datname!~'postgres|template\\\\d'}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{cls=\"$cls\", datname!~'pgbouncer|template\\\\d'}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "pgbouncer:ins:active_clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Waiting Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "pgbouncer:ins:waiting_clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "HAproxy Backends (Database Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{cls=\"$cls\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Proxy ➔ Server Sessions",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,server) (haproxy_server_current_sessions{cls=\"$cls\"})",
     "legendFormat": "{{ ins }} ➔ {{ server }}"
    }
   ]
  },
  {
   "title": "HAproxy Frontents (Proxy Instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_server_current_sessions{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Cluster Xact Commit Rate",
   "type": "timeseries",
   "description": "Postgres transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_commit_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_commit_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact Rollback",
   "type": "timeseries",
   "description": "Postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_rollback_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins!=\"$primary\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Cluster TPS (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:xact_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:xact_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact RT (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer average transaction response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rt_1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:xact_rt_5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:xact_rt_15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Cluster QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:query_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:query_rt_5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:query_rt_15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rate15m{ins=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_5m{ins=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_15m{ins=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}