{
 "title": "PGSQL Cluster",
 "description": "PostgreSQL Cluster Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "description": "Leader of cluster ${cls} is ${primary}",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Services in cluster ${cls}. On(green) means current instance are member of that service. Off(orange) means the opposite.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_server_status{cls=\"$cls\"}) "
    }
   ]
  },
  {
   "type": "table",
   "description": "All haproxy instances in this cluster ${cls}",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CLS ID",
   "type": "stat",
   "description": "ip = ${ip}. Unique identifier for corresponding node",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster_id)(pg_meta_info{ins=\"$primary\"})",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (pg_meta_info{ins=\"$primary\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Cluster Status: 0 : Leaderless,  1 : OK,  2+ : Partitioned",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:partition{cls=\"$cls\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "description": "Cluster size ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg:cls:members{cls=\"$cls\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "table",
   "description": "Important configuration entries of this instance",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$primary\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cls}",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$primary\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{ins=\"$primary\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{ins=\"$primary\"} + pg_db_allow_conn{ins=\"$primary\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$primary\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$primary\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:conn_usage{ins=\"$primary\"})",
     "legendFormat": "Pool Usage"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{ins=\"$primary\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 3, "w": 13, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "leader: {{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_load1{cls=\"$cls\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{cls=\"$cls\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(max by (datname) (pg_db_age{cls=\"$cls\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "node:cls:cpu_count{cls=\"$cls\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=\"$cls\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (ins, mountpoint)(node_filesystem_size_bytes{cls=\"$cls\", fstype!=\"rootfs\"}))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cls=\"$cls\", alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}⚡️] {{alertname}}  @ {{ ins }}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"}",
     "legendFormat": "[{{ severity }}⏰]{{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "Node"
    },
    {
     "expr": "pg:cls:load1{cls=\"$cls\"} != -1",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:cls:load1{cls=\"$cls\"} != -1",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "avg by (cls) (haproxy:ins:usage{cls=\"$cls\"})",
     "legendFormat": "Haproxy"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cls:pressure1{cls=\"$cls\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cls:pressure1{cls=\"$cls\"}",
     "legendFormat": "p1"
    },
    {
     "expr": "cls:pressure5{cls=\"$cls\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "cls:pressure15{cls=\"$cls\"}",
     "legendFormat": "p15"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:xact_rollback_rate1m{cls=\"$cls\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rate1m{cls=\"$cls\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate1m{cls=\"$cls\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$primary\"}",
     "legendFormat": "Primary RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_seconds{cls=\"$cls\"}",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_bytes{cls=\"$cls\"}",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:cls:waiting_clients{cls=\"$cls\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:age{cls=\"$cls\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{cls=\"$cls\"})",
     "legendFormat": "Space"
    }
   ]
  }
 ]
}