{
 "title": "PGSQL Session",
 "description": "PostgreSQL Session of Single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:conn_usage{ins=\"$ins\"}",
     "legendFormat": "Postgres"
    }
   ]
  },
  {
   "title": "Backends by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_backend_count{ins=\"$ins\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "SAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{ins=\"$ins\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Wait Event",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (event) (pg_wait_count{ins=\"$ins\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Max Conn Lifespan",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_conn_duration{ins=\"$ins\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_max_connections{ins=\"$ins\"}",
     "legendFormat": "Max Connection"
    },
    {
     "expr": "pg_setting_max_worker_processes{ins=\"$ins\"}",
     "legendFormat": "Max Worker Proc"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{ins=\"$ins\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{ins=\"$ins\"} + pg_db_allow_conn{ins=\"$primary\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$ins\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$ins\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:conn_usage{ins=\"$ins\"})",
     "legendFormat": "Pool Usage"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{ins=\"$ins\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "PG Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session by Database",
   "type": "timeseries",
   "description": "Total Session Established ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "pg_activity_count{ins=\"$ins\", state=\"active\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "iXact Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pgbouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Pgbouncer Database Definition",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:ins:pool_databases{ins=\"$ins\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "pgbouncer:ins:pool_users{ins=\"$ins\"}",
     "legendFormat": "User"
    },
    {
     "expr": "pgbouncer:ins:pools{ins=\"$ins\"}",
     "legendFormat": "Pools"
    },
    {
     "expr": "pgbouncer:ins:free_servers{ins=\"$ins\"}",
     "legendFormat": "Free Srv"
    },
    {
     "expr": "pgbouncer:ins:active_servers{ins=\"$ins\"}",
     "legendFormat": "Active Srv"
    },
    {
     "expr": "pgbouncer:ins:active_clients{ins=\"$ins\"}",
     "legendFormat": "Active Clients"
    },
    {
     "expr": "pgbouncer:ins:free_clients{ins=\"$ins\"}",
     "legendFormat": "Free Clients"
    },
    {
     "expr": "pgbouncer:ins:used_clients{ins=\"$ins\"}",
     "legendFormat": "Used Clients"
    },
    {
     "expr": "pgbouncer:ins:login_clients{ins=\"$ins\"}",
     "legendFormat": "Login Clients"
    },
    {
     "expr": "max(pgbouncer:db:conn_usage{ins=\"$ins\"})",
     "legendFormat": "Conn Usage"
    }
   ]
  },
  {
   "title": "Pgbouncer Server State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "pgbouncer:ins:active_servers{ins=\"$ins\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:ins:used_servers{ins=\"$ins\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pgbouncer:ins:idle_servers{ins=\"$ins\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "pgbouncer:ins:tested_servers{ins=\"$ins\"}",
     "legendFormat": "Tested"
    },
    {
     "expr": "pgbouncer:ins:login_servers{ins=\"$ins\"}",
     "legendFormat": "Login"
    }
   ]
  },
  {
   "title": "Pgbouncer Client State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "pgbouncer:ins:active_clients{ins=\"$ins\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:pool:waiting_clients{ins=\"$ins\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Pgbouncer Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:pool:maxwait{ins=\"$ins\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pgbouncer_pool_active_clients{ins=\"$ins\"}",
     "legendFormat": "[{{ pool_mode }}]] {{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer:pool:active_clients{ins=\"$ins\"})",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Clients by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "pgbouncer:pool:active_clients{ins=\"$ins\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum by (datname) (pgbouncer:pool:active_clients{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  }
 ]
}