---
galaxy_info:
  role_name: node_id
  description: calculate node identity
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: AGPLv3
  platforms:
    - name: EL
      versions: [ 7, 8 , 9 ]
    - name: Ubuntu
      versions: [ 24.04, 22.04, 20.04 ]
    - name: Debian
      versions: [ 12, 11 ]
  galaxy_tags:
    - pigsty
    - node
...