{
 "title": "PGCAT Database",
 "description": "PostgreSQL Catalog Explorer for Single Database",
 "tags": [
  "Pigsty",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn}';" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate, datallowconn,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,\n       t.spcname as tablespace\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nWHERE d.datname = '$datname'\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT unnest(datacl) AS name FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Recovery status of this instance",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_is_in_recovery()::INTEGER AS recovery"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Database OID of ${datname}",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT oid FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT json_object_agg(kind, count) AS data\n         FROM (SELECT relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY 1) d\n     ) j;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT pg_catalog.shobj_description(d.oid, 'pg_database') as description FROM pg_database d WHERE datname = '$datname';"
    }
   ]
  },
  {
   "title": "Schemas",
   "type": "table",
   "description": "Schemas of current database ${datname}",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n       relnamespace AS \"OID\", nspname AS \"Schema\", nspowner::RegRole::TEXT AS \"Owner\",\n       coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT relnamespace, json_object_agg(kind, count) AS data\n         FROM (SELECT relnamespace, relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY 1,2) d\n         GROUP BY 1\n     ) j LEFT JOIN pg_namespace nsp ON j.relnamespace = nsp.oid\nWHERE nspname NOT IN ('pg_toast', 'information_schema', 'pg_catalog');"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tables",
   "type": "table",
   "description": "Tables of current database ${datname}",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT c.oid                                                AS \"OID\",\n       n.nspname                                            as \"Schema\",\n       n.nspname || '.' || c.relname                        as \"Name\",\n       CASE WHEN relispartition THEN 'P' ELSE c.relkind END AS \"Kind\",\n       age(c.relfrozenxid)::FLOAT / 2147483648              AS relage,\n       reltuples,\n       relpages,\n       relfilenode,\n       pg_table_size(c.oid)                                 AS \"Size\",\n       relnatts, s.*\nFROM pg_catalog.pg_class c\n         LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n         LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid\nWHERE c.relkind IN ('r', 'p', '')\n  AND n.nspname <> 'pg_catalog'\n  AND n.nspname !~ '^pg_toast'\n  AND n.nspname <> 'information_schema'\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Table Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Bloat",
     "type": "table",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM monitor.pg_table_bloat;"
      }
     ]
    },
    {
     "title": "Table Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 17, "w": 13, "x": 11, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, nspname, size * ratio AS waste, ratio FROM monitor.pg_table_bloat;"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Schema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Sequences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Views",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT *,\n  extract(epoch from now() - backend_start) AS conn_time,\n  extract(epoch from now() - xact_start)    AS xact_time,\n  extract(epoch from now() - query_start)   AS query_time,\n  extract(epoch from now() - state_change)  AS state_time\nFROM pg_stat_activity Where datname = '$datname';"
      }
     ]
    },
    {
     "title": "Sessions (by Type)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(backend_type, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(backend_type, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by State)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(state, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(state, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Wait Event)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(wait_event, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(wait_event, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by Client Addr)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(client_addr::text, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(client_addr::text, 'null');\n"
      }
     ]
    },
    {
     "title": "Sessions (by User)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(usename, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY coalesce(usename, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by App)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time ,\n  coalesce(application_name, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE datname = '$datname'\nGROUP BY 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Statements",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\nLEFT JOIN pg_database d ON s.dbid = d.oid\n     LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname = '$datname'     \nORDER BY rows DESC LIMIT 200;"
      }
     ]
    },
    {
     "title": "Query (by Time)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, queryid::TEXT AS query, sum(t) AS value FROM\n(SELECT queryid, total_exec_time AS t FROM monitor.pg_stat_statements s WHERE dbid = (SELECT oid FROM pg_database WHERE datname= '$datname' LIMIT 1)\nORDER BY rows DESC LIMIT 200) raw\nGROUP BY 2 ORDER BY 3 DESC;"
      }
     ]
    },
    {
     "title": "Query (by Rows)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, queryid::TEXT AS query, sum(t) AS value FROM\n(SELECT queryid, rows AS t FROM monitor.pg_stat_statements s WHERE dbid = (SELECT oid FROM pg_database WHERE datname= '$datname' LIMIT 1)\nORDER BY rows DESC LIMIT 200) raw\nGROUP BY 2 ORDER BY 3 DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postmaster",
     "type": "stat",
     "description": "These settings can only be applied when the server starts",
     "gridPos": { "h": 22, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'postmaster'"
      }
     ]
    },
    {
     "title": "Internal",
     "type": "stat",
     "description": "These settings cannot be changed directly; they reflect internally determined values. Some of them may be adjustable by rebuilding the server with different configuration options, or by changing options supplied to initdb.",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'internal'"
      }
     ]
    },
    {
     "title": "Changed",
     "type": "table",
     "description": "These settings that has non-default values",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT name,setting,source,context,pending_restart FROM pg_settings;"
      }
     ]
    },
    {
     "title": "Init Parameters",
     "type": "stat",
     "description": "Info from pg_control_system",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_init();"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, name AS metric,setting AS value FROM pg_settings WHERE name in ('archive_command', 'primary_conninfo')"
      }
     ]
    }
   ]
  },
  {
   "title": "Logical Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Slots (Logical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'logical';"
      }
     ]
    },
    {
     "title": "Subscription",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_subscription;"
      }
     ]
    },
    {
     "title": "Publication",
     "type": "stat",
     "description": "Publication Information\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_publication;" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Memory Segments",
     "type": "table",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(name, 'Free') AS name, off AS offset, allocated_size AS size FROM monitor.pg_shmem();"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "piechart",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, coalesce(name, 'Free') AS name, allocated_size AS size FROM monitor.pg_shmem() ORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "marcusolsson-treemap-panel",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(name, 'Free') AS name, allocated_size AS size FROM monitor.pg_shmem();"
      }
     ]
    },
    {
     "title": "pg_stat_slru",
     "type": "table",
     "description": "PostgreSQL accesses certain on-disk information via SLRU (simple least-recently-used) caches. The pg_stat_slru view will contain one row for each tracked SLRU cache, showing statistics about access to cached pages.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 25 },
     "targets": [
      { "rawSql": "SELECT * FROM pg_stat_slru;" }
     ]
    }
   ]
  },
  {
   "title": "Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "pg_control_checkpoint",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_checkpoint();"
      }
     ]
    },
    {
     "title": "pg_control_system",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_system();"
      }
     ]
    },
    {
     "title": "pg_stat_bgwriter",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_bgwriter;"
      }
     ]
    },
    {
     "title": "pg_stat_wal",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_stat_wal;" }
     ]
    },
    {
     "title": "pg_control_recovery",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_recovery();"
      }
     ]
    }
   ]
  }
 ]
}