{
 "title": "PGCAT Bloat",
 "description": "Table Bloat Visualization from Catalog",
 "tags": [
  "PG",
  "Catalog",
  "Database",
  "Table"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" }
  ]
 },
 "panels": [
  {
   "title": "Table Bloat",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM monitor.pg_table_bloat;"
    }
   ]
  },
  {
   "title": "Index Bloat",
   "type": "table",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM monitor.pg_index_bloat;"
    }
   ]
  },
  {
   "title": "Table Wasted Bytes",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT nspname || '.' || relname AS relname, size * ratio AS waste FROM monitor.pg_table_bloat;"
    }
   ]
  },
  {
   "title": "Index Wasted Bytes",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_index_bloat;"
    }
   ]
  }
 ]
}