#!/bin/bash

#==============================================================#
# File      :   install
# Ctime     :   2021-06-29
# Mtime     :   2021-06-29
# Desc      :   install pgsql monitoring system
# Path      :   app/pgsql/install
# Copyright (C) 2018-2021 Ruohang Feng
#==============================================================#

# detect environment
PROG_NAME="$(basename $0))"
PROG_DIR="$(cd $(dirname $0) && pwd)"

# fetch parameter
PGURL=${1-'postgres://dbuser_dba:DBUser.DBA@:5432/meta'}
GFDIR=${2-'/etc/dashboards'}

# load database content

# copy dashboards definition
sudo mkdir -p ${GFDIR}
cp -rf ${PROG_DIR}/dashboards/* ${GFDIR}/

# cp -rf app/pgsql/dashboards/pgsql -> /etc/dashboards/pgsql
exit 0