# pigsty default singleton vm (3C6G)
Specs = [
  {"name" => "meta",   "ip" => "10.10.10.10", "cpu" => "3",  "mem" => "6128", "image" => "generic/centos7" },
  #{"name" => "node-1", "ip" => "10.10.10.11", "cpu" => "1",  "mem" => "2048", "image" => "generic/centos7" },
  #{"name" => "node-2", "ip" => "10.10.10.12", "cpu" => "1",  "mem" => "2048", "image" => "generic/centos7" },
  #{"name" => "node-3", "ip" => "10.10.10.13", "cpu" => "1",  "mem" => "2048", "image" => "generic/centos7" },
]

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    # generate nodes definition according to Specs
    Specs.each_with_index do |spec, index|
        config.vm.define spec["name"] do |node|
            node.vm.box = spec["image"]
            node.vm.network "private_network", ip: spec["ip"]
            node.vm.hostname = spec["name"]
            node.vm.provider "virtualbox" do |v|
                v.linked_clone = true
                v.customize [
                    "modifyvm", :id, "--cpus", spec["cpu"], "--memory", spec["mem"],
                    "--nictype1", "virtio", "--nictype2", "virtio", "--hwvirtex", "on", "--ioapic", "on",
                     "--rtcuseutc", "on", "--vtxvpid", "on", "--largepages", "on"
                  ]
                v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000]
            end
            node.vm.provision "shell", path: "provision.sh"
        end
    end
end
