Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9"
      config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "2048"
    vmware.vmx["numvcpus"] = "2"
  end
end
