{
 "title": "PGLOG Session",
 "description": "PostgreSQL Log Analysis for single session",
 "tags": [
  "APP",
  "PGLOG"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "log", "label": "Log Table", "query": "pglog.sample" },
   { "name": "sid", "label": "Session ID", "query": "60f01952.988" },
   {
    "name": "ts_begin",
    "label": "Time Begin",
    "query": "SELECT min(ts) - '5s'::INTERVAL FROM ${log} WHERE sid = '$sid';"
   },
   {
    "name": "ts_end",
    "label": "Time End",
    "query": "SELECT max(ts) + '5s'::INTERVAL FROM ${log} WHERE sid = '$sid';"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Events (All)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       level AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT sid, count(*) AS count, count(*) FILTER ( WHERE code != '00000' ) AS error\nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY sid ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Log Events (Current Session)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       level AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts) AND sid = '$sid'\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM ${log} WHERE sid = '${sid}' LIMIT 1;"
    }
   ]
  },
  {
   "title": "Log Event",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT * FROM ${log} WHERE sid = '${sid}'"
    }
   ]
  }
 ]
}