{
 "title": "Redis Instance",
 "description": "Redis Instance Dashboard",
 "tags": [
  "Pigsty",
  "REDIS",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "id", "label": "Instance", "query": { "query": "label_values(redis:ins, id)" } },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_instance_info{job=\"redis\", ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
    }
   },
   {
    "name": "addr",
    "label": "Address",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Used as an unique instance identifier",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "redis_instance_info{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:cpu_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:mem_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:qps{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Address",
   "type": "stat",
   "description": "Host:Port of this redis instance",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "description": "Redis Mode: Cluster|Sentinel|Normal(standalone)",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (redis_mode) (redis_instance_info{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "stat",
   "description": "Primary|master address of this replica redid instance",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (upstream) (label_join(redis_slave_info{ins=\"$ins\"}, 'upstream', ':', 'master_host', 'master_port'))"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Role of this redid instance: primary|replica",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (role) (redis_instance_info{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "stat",
   "description": "Redis MaxMemory Policy:\nvolatile-lru\nallkeys-lru\nvolatile-lfu\nallkeys-lfu\nvolatile-random\nallkeys-random\nvolatile-ttl\nnoeviction",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (maxmemory_policy) (redis_instance_info{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Redis Version",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (redis_version) (redis_instance_info{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slave_info{master_host=\"$ip\", master_port=\"$port\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mem Allocation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{ins=\"$ins\"} / redis_memory_max_bytes{ins=\"$ins\"}",
     "legendFormat": "Mem Usage"
    },
    {
     "expr": "redis_memory_used_bytes{ins=\"$ins\"}",
     "legendFormat": "Mem Used"
    },
    {
     "expr": "redis_memory_max_bytes{ins=\"$ins\"}",
     "legendFormat": "Mem Config"
    },
    {
     "expr": "max(label_replace(redis_total_system_memory_bytes{ins=\"$ins\"}, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\"))",
     "legendFormat": "Mem Node"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "CMD",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:cmd_qps{ins=\"$ins\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:mem_usage{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:qps{ins=\"$ins\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{ins=\"$ins\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:rt{ins=\"$ins\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{ins=\"$ins\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_enabled{cls=\"$cls\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "max(redis_cluster_state{cls=\"$cls\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "avg(redis_cluster_size{cls=\"$cls\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max(redis_cluster_current_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch"
    },
    {
     "expr": "min(redis_cluster_my_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch Min"
    },
    {
     "expr": "min(redis_cluster_known_nodes{cls=\"$cls\"})",
     "legendFormat": "Known Ins"
    },
    {
     "expr": "max(redis_cluster_slots_assigned{cls=\"$cls\"})",
     "legendFormat": "Slot Assigned"
    },
    {
     "expr": "max(redis_cluster_slots_ok{cls=\"$cls\"})",
     "legendFormat": "Slot OK"
    },
    {
     "expr": "max(redis_cluster_slots_fail{cls=\"$cls\"})",
     "legendFormat": "Slot Fail"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", ins=\"$ins\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", ins=\"$ins\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}  @ {{ ins }}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}  @ {{ ins }}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "redis:ins:cpu_usage{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "CPU Usage (Child)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "redis:ins:cpu_usage_child{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "redis:ins:rx{ins=\"$ins\"}",
       "legendFormat": "⬇️RX"
      },
      {
       "expr": "-redis:ins:tx{ins=\"$ins\"}",
       "legendFormat": "⬆️TX"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "redis_memory_used_bytes{ins=\"$ins\"}",
       "legendFormat": "used"
      },
      {
       "expr": "min(redis_memory_max_bytes{ins=\"$ins\"} )",
       "legendFormat": "max"
      },
      {
       "expr": "redis:ins:mem_usage{ins=\"$ins\"}",
       "legendFormat": "usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis:ins:qps{ins=\"$ins\"}",
       "legendFormat": "QPS"
      },
      {
       "expr": "redis:ins:qps_mu{ins=\"$ins\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "redis:ins:qps_mu{ins=\"$ins\"} + redis:ins:qps_sigma{ins=\"$ins\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "redis:ins:qps_mu{ins=\"$ins\"} - redis:ins:qps_sigma{ins=\"$ins\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "redis:ins:qps_mu{ins=\"$ins\"} +  3 * redis:ins:qps_sigma{ins=\"$ins\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "redis:ins:qps_mu{ins=\"$ins\"} - 3 * redis:ins:qps_sigma{ins=\"$ins\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Instance RT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "redis:ins:rt{ins=\"$ins\"}",
       "legendFormat": "RT"
      },
      {
       "expr": "redis:ins:rt_mu{ins=\"$ins\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "redis:ins:rt_mu{ins=\"$ins\"} + redis:ins:rt_sigma{ins=\"$ins\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "redis:ins:rt_mu{ins=\"$ins\"} - redis:ins:rt_sigma{ins=\"$ins\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "redis:ins:rt_mu{ins=\"$ins\"} +  3 * redis:ins:rt_sigma{ins=\"$ins\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "redis:ins:rt_mu{ins=\"$ins\"} - 3 * redis:ins:rt_sigma{ins=\"$ins\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Command QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis:ins:cmd_qps{ins=\"$ins\"}",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Command QPS (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(redis_commands_total{ins=\"$ins\"}[1m])",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Command RT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "redis:ins:cmd_rt{ins=\"$ins\"}",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Command Time (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(redis_commands_duration_seconds_total{ins=\"$ins\"}[1m])",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Command Distribution (Realtime)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis:ins:cmd_qps{ins=\"$ins\"}",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Command Time Distribution (1 Day)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (cmd) (increase(redis_commands_duration_seconds_total{ins=\"$ins\"}[1d]))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clients",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis:ins:clients{ins=\"$ins\"}",
       "legendFormat": "clients"
      }
     ]
    },
    {
     "title": "Connected Slaves",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_connected_slaves{ins=\"$ins\"}",
       "legendFormat": "slaves"
      }
     ]
    },
    {
     "title": "Received Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis:ins:conn_rate{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Max Output List",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(redis_blocked_clients{ins=\"$ins\"})",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Reject Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis:ins:conn_reject{ins=\"$ins\"}",
       "legendFormat": "reject"
      }
     ]
    },
    {
     "title": "Blocked Client Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis:ins:blocked_clients{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Expired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis:ins:key_expire{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (redis_db_keys{ins=\"$ins\"})",
       "legendFormat": "{{ ins }} "
      }
     ]
    },
    {
     "title": "Key Evicted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis:ins:key_evict{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Keys (per DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{ins=\"$ins\"}) by (db)",
       "legendFormat": "{{ db }} "
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "redis_db_avg_ttl_seconds{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Key Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "redis:ins:key_hit_rate{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Fork Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "redis_latest_fork_seconds{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Latest AOF Rewrite Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "redis_aof_last_rewrite_duration_sec{ins=\"$ins\"} > 0",
       "legendFormat": "{{ ins }}"
      },
      { "expr": "0", "legendFormat": "zero" }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "label_join(label_replace(redis_slave_info{cls=\"$cls\"}, \"replica_ins\", \"$1\", \"ins\", \"(.+)\"), 'ins', ':', 'master_host', 'master_port')"
      }
     ]
    },
    {
     "title": "LSN Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "redis:ins:lsn_rate{ins=\"$ins\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  }
 ]
}