{
 "title": "Node HAProxy",
 "description": "HAProxy Instance",
 "tags": [
  "Pigsty",
  "NODE",
  "HAProxy",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_process_idle_time_percent, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(haproxy_process_idle_time_percent{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(haproxy_process_idle_time_percent{ins=\"$ins\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. Formed as {{ cls }}-{{ seq }}. ",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "Service among cluster. Number of routes from proxy to server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"})"
    },
    {
     "expr": "sum by (proxy) (haproxy_server_status{ins=\"$ins\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Proxy instances among this cluster\n",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_server_current_sessions{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "All postgres instance served by this proxy",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum by (server)(haproxy_server_status{ins=\"$ins\"})",
     "legendFormat": "Route"
    },
    {
     "expr": "max by (server) (haproxy_server_weight{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Node IP",
   "type": "stat",
   "description": "ip = ${ip}. Unique identifier for corresponding node",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "description": "Hostname = ${node}",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Admin Page",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (instance) (haproxy_up{ins=\"$ins\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{ins=\"$ins\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - haproxy_process_idle_time_percent{ins=\"$ins\"}",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (proxy) (haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}))",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (server)(haproxy_server_status{ins=\"$ins\"}))",
     "legendFormat": "Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{ins=\"$ins\"})",
     "legendFormat": "Frontend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"})",
     "legendFormat": "Backends"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_process_nbproc{ins=\"$ins\"}",
     "legendFormat": "BG Proc"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_process_current_tasks{ins=\"$ins\"}",
     "legendFormat": "Task"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Service Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{ins=\"$ins\", proxy!=\"stats\"} == 1)",
     "legendFormat": "Frontends Up"
    },
    {
     "expr": "- count(haproxy_backend_status{ins=\"$ins\", proxy!=\"stats\"} == 1)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (server) (haproxy_server_status{ins=\"$ins\", proxy!=\"stats\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Route Matrix",
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_current_sessions{cls=\"$cls\"}\n)"
    }
   ]
  },
  {
   "title": "Proxy Routes",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "haproxy_server_status{ins=\"$ins\", state=\"UP\"}",
     "legendFormat": " {{ proxy }} 【service】→ {{ server }} 【server】"
    }
   ]
  },
  {
   "title": "General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_bytes_in_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8) by (instance)",
       "legendFormat": "IN Front"
      },
      {
       "expr": "sum(irate(haproxy_frontend_bytes_out_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8) by (instance)",
       "legendFormat": "OUT Front"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_in_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8) by (instance)",
       "legendFormat": "IN Back"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
       "legendFormat": "OUT Back"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_connections_total{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "FE"
      },
      {
       "expr": "sum(irate(haproxy_backend_connection_errors_total{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "BE Errors"
      }
     ]
    },
    {
     "title": "Total received requests / responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_requests_total{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "Frontend requests"
      },
      {
       "expr": "sum(irate(haproxy_frontend_request_errors_total{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "Frontend requests errors"
      },
      {
       "expr": "sum(irate(haproxy_frontend_requests_denied_total{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "Frontend request denied"
      },
      {
       "expr": "sum(irate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend redispatch warnings"
      },
      {
       "expr": "sum(irate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend retry warnings"
      },
      {
       "expr": "sum(irate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend response errors"
      },
      {
       "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$host:$port\"}) by (instance)",
       "legendFormat": "Backend queued requests"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend requests"
      }
     ]
    },
    {
     "title": "Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "Frontend current sessions"
      },
      {
       "expr": "sum(irate(haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}[5m])) by (instance)",
       "legendFormat": "Backend current sessions"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_connection_attempts_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_backend_connection_errors_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_bytes_in_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_backend_bytes_out_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_bytes_in_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_bytes_out_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_connections_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_denied_connections_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total number of connections reuses",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_connection_reuses_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of connections per second",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_connections_rate_max{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_sessions_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_sessions_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_denied_sessions_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Denied by \"tcp-request session\" rules {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_max_sessions{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_max_sessions{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of sessions per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Last session assigned",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_last_session_seconds{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_client_aborts_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_server_aborts_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_check_up_down_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total weight of the servers in the backend / Active servers backend",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_weight{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_last_session_seconds{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total number of times a service was selected",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_loadbalanced_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 203 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_bytes_in_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_bytes_out_total{ins=\"$ins\", proxy!=\"stats\"}[5m])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 203 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_attempts_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_connection_errors_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_connection_reuses_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of queued requests",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 203 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_current_queue{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_sessions_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 16, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_client_aborts_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_server_aborts_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total downtime in seconds",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_downtime_seconds_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks history",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(haproxy_server_check_failures_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total number of failed check {{ proxy }} / {{ server }}"
      },
      {
       "expr": "increase(haproxy_server_check_up_down_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "Total number of UP->DOWN transitions {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total of connection errors",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_errors_total{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Throttle",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Current throttle percentage for the server, when slowstart is active, or no value if not in slowstart {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Loadbalanced",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_loadbalanced_total{ins=\"$ins\", proxy!=\"stats\"}",
       "legendFormat": "Total number of times a service was selected {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Service weight",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_last_session_seconds{ins=\"$ins\", proxy!=\"stats\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HAProxy Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Memory",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{ins=\"$ins\"}",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "irate(haproxy_process_pool_allocated_bytes{ins=\"$ins\"}[5m])",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "irate(haproxy_process_pool_used_bytes{ins=\"$ins\"}[5m])",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_current_tasks{ins=\"$ins\"}[5m])",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "haproxy_process_current_run_queue{ins=\"$ins\"}",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "haproxy_process_stopping{ins=\"$ins\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_fds{ins=\"$ins\"}",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "haproxy_process_max_sockets{ins=\"$ins\"}",
       "legendFormat": "Maximum numer of open sockets"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{ins=\"$ins\"}",
       "legendFormat": "Configured maximum number of pipes"
      },
      {
       "expr": "irate(haproxy_process_pipes_used_total{ins=\"$ins\"}[5m])",
       "legendFormat": "Number of pipes in used"
      },
      {
       "expr": "irate(haproxy_process_pipes_free_total{ins=\"$ins\"}[5m])",
       "legendFormat": "Number of pipes unused"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_nbthread{ins=\"$ins\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{ins=\"$ins\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_pool_failures_total{ins=\"$ins\"}",
       "legendFormat": "Total number of failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{ins=\"$ins\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_jobs{ins=\"$ins\"}[5m])",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "irate(haproxy_process_unstoppable_jobs{ins=\"$ins\"}[5m])",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "irate(haproxy_process_listeners{ins=\"$ins\"}[5m])",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_active_peers{ins=\"$ins\"}",
       "legendFormat": "Current number of active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{ins=\"$ins\"}",
       "legendFormat": "Current number of connected peers"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_dropped_logs_total{ins=\"$ins\"}",
       "legendFormat": "Total number of dropped logs"
      }
     ]
    },
    {
     "title": "Process - Sessions over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_session_rate{ins=\"$ins\"}",
       "legendFormat": "Current number of sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_session_rate{ins=\"$ins\"}",
       "legendFormat": "Configured maximum number of sessions per second"
      }
     ]
    },
    {
     "title": "Process - Total sessions / requests",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_connections_total{ins=\"$ins\"}[5m])",
       "legendFormat": "Total number of created sessions"
      },
      {
       "expr": "irate(haproxy_process_requests_total{ins=\"$ins\"}[5m])",
       "legendFormat": "Total number of requests (TCP or HTTP)"
      }
     ]
    },
    {
     "title": "Process - Connections over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_connection_rate{ins=\"$ins\"}",
       "legendFormat": "Current number of connections per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{ins=\"$ins\"}",
       "legendFormat": "Configured maximum number of connections per second."
      }
     ]
    },
    {
     "title": "Process - Connections",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_connections{ins=\"$ins\"}",
       "legendFormat": "Maximum number of concurrent connections"
      },
      {
       "expr": "haproxy_process_hard_max_connections{ins=\"$ins\"}",
       "legendFormat": "Initial Maximum number of concurrent connections"
      }
     ]
    }
   ]
  }
 ]
}