{
 "title": "Home",
 "description": "Pigsty Home Page",
 "tags": [ "PG" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pigsty",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "<div style=\"text-align: center; height:100%; weight: 100%\" height=\"100%\">\n<img src=\"/public/img/pigsty.svg\" height=\"100%\" style=\"text-aligh: center;\">\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "<div style=\"text-align: center; height:100%; weight: 100%\" height=\"100%\">\n    <div>\n        <p>\n            Links:\n            <a href=\"http://g.pigsty\">Grafana</a>,\n            <a href=\"http://c.pigsty\">Consul</a>,\n            <a href=\"http://p.pigsty\">Prometheus</a>,\n            <a href=\"http://a.pigsty\">AlertManager</a>,\n            <a href=\"http://yum.pigsty/pigsty\">Yum Repo</a>,\n            <a href=\"http://h.pigsty\">HAProxy</a>\n        </p>\n\n        <p><a href=\"https://github.com/Vonng/pigsty\">Pigsty</a>\n            is a monitoring system specially designed for large scale PostgreSQL clusters.</p>\n        <p>Integrated with a production grade cluster provisioning solution</p>\n        <p> Check\n            <a href=\"http://pigsty.cc\">Official Site</a> and\n            <a href=\"https://github.com/Vonng/pigsty\">Github Repo</a> for more information\n        </p>\n    </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg:cls:saturation1[1d]", "legendFormat": "{{ cls }}" },
    { "expr": "pg:cls:size" }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{}) or on() vector(0)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "pg:cls:saturation0", "legendFormat": "{{ cls }}" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 11 },
   "targets": [
    { "expr": "min by (ins,ip) (pg_status{})" },
    {
     "expr": "min by (ins) (pg:ins:saturation1{})"
    }
   ]
  },
  {
   "title": "Xacts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg:all:xacts)" }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(count by(ip)(pg_up{}))" }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_up{role=\"primary\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg:cls:size{})" }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_up{role=\"replica\"})"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cls, datname) (pg_database_age{datname!~\"postgres|template0|template1|monitordb\"}))"
    }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node:ins:cpu_count{})" }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (ins, mountpoint)(node_filesystem_size_bytes{fstype!=\"rootfs\"}))"
    }
   ]
  },
  {
   "title": "PCIE-SSD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (ins, mountpoint)(node_filesystem_size_bytes{device=~'/dev/dfa.*'}))"
    }
   ]
  },
  {
   "title": "Link",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (ins) (node_network_speed_bytes{}) * 8)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum without(cls, mode) (node:cls:cpu_mode{mode=\"idle\"}) / sum(node:cls:cpu_count{})"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(node:ins:mem_free)  / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disk Traffic",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (ins, mountpoint) (node:dev:disk_io_rate{}))"
    }
   ]
  },
  {
   "title": "Net Traffic",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node:ins:network_io{})" }
   ]
  },
  {
   "title": "Retrans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:tcp_retranssegs{})"
    }
   ]
  }
 ]
}