{
 "title": "Node",
 "description": "Node Instance Dashboard",
 "tags": [
  "PG",
  "Instance"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "templating": {
  "list": [
   { "name": "ip", "label": "IP", "query": { "query": "label_values(node_load1{}, ip)" } },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"}, ins)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"},  ins)"
    }
   },
   {
    "name": "svc",
    "label": "Service",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"}, svc)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 1, "h": 2, "w": 6, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "y": 1, "h": 2, "w": 6, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 4, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:stdload1{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 6, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${node}" }
   ]
  },
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 6, "x": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ip}" }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 3, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ip=\"$ip\"} ",
     "legendFormat": "{{ sysname }}"
    }
   ]
  },
  {
   "title": "Arch",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 3, "x": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ip=\"$ip\"} ",
     "legendFormat": "{{ machine }}"
    }
   ]
  },
  {
   "title": "Release",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 3, "x": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ip=\"$ip\"} ",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 3, "x": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ip=\"$ip\"} ",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 5, "h": 4, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (device,fstype,mountpoint) (node_filesystem_avail_bytes{ip=\"$ip\"})"
    },
    {
     "expr": "max by (device) (node_filesystem_size_bytes{ip=\"$ip\"})"
    },
    {
     "expr": "1 - max by (device) (node_filesystem_avail_bytes{ip=\"$ip\"}) / max by (device) (node_filesystem_size_bytes{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_count{ip=\"$ip\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{ip=\"$ip\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Link",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_network_speed_bytes{ip=\"$ip\"}) * 8 or on() vector(1000000000)"
    }
   ]
  },
  {
   "title": "Numa",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_vmstat_numa_hit{ip=\"$ip\"}[1m]) > bool 0 or on() vector(0)"
    }
   ]
  },
  {
   "title": "Huge Page",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{ip=\"$ip\"} > bool 0",
     "legendFormat": "HP"
    }
   ]
  },
  {
   "title": "NVME SSD",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (device) (node_disk_read_bytes_total{ip=\"$ip\", device=~'dfa.*'})) > bool 0"
    }
   ]
  },
  {
   "title": "Bond",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (ins) (node_bonding_active{ip=\"$ip\"} > 0) > bool 0",
     "legendFormat": "Bond"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 9, "h": 4, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_network_info{ip=\"$ip\"}"
    },
    {
     "expr": "max by (device) (node_network_mtu_bytes{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Machine",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_count{ip=\"$ip\"} > bool 8",
     "legendFormat": "Res"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{ip=\"$ip\"} > bool 0",
     "legendFormat": "Res"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{ip=\"$ip\", instance=~\".*:(9100|9099)\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - node_boot_time_seconds{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:cpu_usage{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:mem_usage{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "iNode Usage",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:inode_usage{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "TCP Err Rate",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_netstat_TcpExt_ListenOverflows{ip=\"$ip\"}[3m]) + rate(node_netstat_TcpExt_ListenDrops{ip=\"$ip\"}[3m]) + rate(node_netstat_Tcp_RetransSegs{ip=\"$ip\"}[3m]) + rate(node_netstat_Tcp_InErrs{ip=\"$ip\"}[3m]))"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(node_ntp_offset_seconds{ip=\"$ip\"}))"
    }
   ]
  },
  {
   "title": "Disk Traffic",
   "type": "stat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (mountpoint) (node:dev:disk_io_rate{ins=\"$ins\"}))"
    }
   ]
  },
  {
   "title": "Net Traffic",
   "type": "stat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:network_io{ip=\"$ip\"}) * 8"
    }
   ]
  },
  { "title": "CPU / Schedule", "type": "row", "gridPos": { "y": 17, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Core Usage (avg1m)",
   "type": "table",
   "gridPos": { "y": 18, "h": 19, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(node:cpu:cpu_usage{ip=\"$ip\"}[1m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "y": 18, "h": 6, "w": 10, "x": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Load (Normalized)",
   "type": "graph",
   "gridPos": { "y": 18, "h": 6, "w": 10, "x": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{ip=\"$ip\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{ip=\"$ip\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{ip=\"$ip\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU Usage (Mode)",
   "type": "graph",
   "gridPos": { "y": 24, "h": 6, "w": 10, "x": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:ins:cpu_mode{ip=\"$ip\"}",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU usage (core)",
   "type": "graph",
   "gridPos": { "y": 24, "h": 6, "w": 10, "x": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:cpu:cpu_usage{ip=\"$ip\"}",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "graph",
   "gridPos": { "y": 30, "h": 7, "w": 10, "x": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:ins:ctx_switch{ip=\"$ip\"}",
     "legendFormat": "Context Switch"
    },
    {
     "expr": "node:ins:intrrupt{ip=\"$ip\"}",
     "legendFormat": "Interrupt"
    }
   ]
  },
  {
   "title": "Scheduled Timeslices (core)",
   "type": "graph",
   "gridPos": { "y": 30, "h": 7, "w": 10, "x": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:cpu:sched_timeslices{ip=\"$ip\"}",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Fork",
   "type": "graph",
   "gridPos": { "y": 37, "h": 7, "w": 4, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:ins:forks{ip=\"$ip\"}",
     "legendFormat": "Fork"
    }
   ]
  },
  {
   "title": "Process State / Thread",
   "type": "graph",
   "gridPos": { "y": 37, "h": 7, "w": 10, "x": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{ip=\"$ip\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "node_procs_blocked{ip=\"$ip\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "node_processes_threads{ip=\"$ip\"}",
     "legendFormat": "Thread"
    }
   ]
  },
  {
   "title": "Non-Sleep Process State",
   "type": "graph",
   "gridPos": { "y": 37, "h": 7, "w": 10, "x": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_processes_state{ip=\"$ip\", state!=\"S\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Memory / VM", "type": "row", "gridPos": { "y": 44, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "y": 45, "h": 6, "w": 15, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{ip=\"$ip\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{ip=\"$ip\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{ip=\"$ip\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_PageTables_bytes{ip=\"$ip\"}",
     "legendFormat": "PageTable"
    },
    {
     "expr": "node_memory_Slab_bytes{ip=\"$ip\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Shmem_bytes{ip=\"$ip\"}",
     "legendFormat": "Shmem"
    }
   ]
  },
  {
   "title": "Memory / Swap Usage",
   "type": "graph",
   "gridPos": { "y": 45, "h": 6, "w": 6, "x": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:ins:mem_usage{ip=\"$ip\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "node:ins:swap_usage{ip=\"$ip\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "EDAC Errors",
   "type": "stat",
   "gridPos": { "y": 45, "h": 3, "w": 3, "x": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_edac_correctable_errors_total{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Uncorrectable",
   "type": "stat",
   "gridPos": { "y": 48, "h": 3, "w": 3, "x": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_edac_uncorrectable_errors_total{ip=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Memory Active/Anonymous Structure",
   "type": "graph",
   "gridPos": { "y": 51, "h": 6, "w": 8, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{ip=\"$ip\"}",
     "legendFormat": "Inactive-File"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{ip=\"$ip\"}",
     "legendFormat": "Inactive-Anonymous"
    },
    {
     "expr": "node_memory_Active_file_bytes{ip=\"$ip\"}",
     "legendFormat": "Active-File"
    },
    {
     "expr": "node_memory_Active_anon_bytes{ip=\"$ip\"}",
     "legendFormat": "Active-Anonymous"
    }
   ]
  },
  {
   "title": "Writeback / Dirty",
   "type": "graph",
   "gridPos": { "y": 51, "h": 6, "w": 8, "x": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{ip=\"$ip\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_Dirty_bytes{ip=\"$ip\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Committed",
   "type": "graph",
   "gridPos": { "y": 51, "h": 6, "w": 8, "x": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{ip=\"$ip\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{ip=\"$ip\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{ip=\"$ip\"} / node_memory_CommitLimit_bytes{ip=\"$ip\"}",
     "legendFormat": "Commit Ratio"
    }
   ]
  },
  {
   "title": "Page/Swap IO",
   "type": "graph",
   "gridPos": { "y": 57, "h": 6, "w": 16, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:ins:pagein{ip=\"$ip\"}",
     "legendFormat": "⬆️PageIn"
    },
    {
     "expr": "node:ins:pageout{ip=\"$ip\"}",
     "legendFormat": "⬇️PageOut"
    },
    {
     "expr": "node:ins:swapin{ip=\"$ip\"}",
     "legendFormat": "⬆️SwapIn"
    },
    {
     "expr": "node:ins:swapout{ip=\"$ip\"}",
     "legendFormat": "⬇️SwapOut"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "graph",
   "gridPos": { "y": 57, "h": 6, "w": 8, "x": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:ins:pagefault{ip=\"$ip\"}",
     "legendFormat": "PageFault"
    }
   ]
  },
  { "title": "Storage / Filesystem", "type": "row", "gridPos": { "y": 63, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "table",
   "gridPos": { "y": 64, "h": 5, "w": 24, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (device,fstype,mountpoint) (node_filesystem_size_bytes{ip=\"$ip\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (device) (node_filesystem_avail_bytes{ip=\"$ip\"})",
     "legendFormat": "Avail"
    },
    {
     "expr": "max by (device) (node_filesystem_size_bytes{ip=\"$ip\"}) - max by (device) (node_filesystem_avail_bytes{ip=\"$ip\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "1 - max by (device) (node_filesystem_avail_bytes{ip=\"$ip\"}) / max by (device) (node_filesystem_size_bytes{ip=\"$ip\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max by (device) (node_filesystem_files{ip=\"$ip\"})",
     "legendFormat": "iNodes"
    },
    {
     "expr": "max by (device) (node_filesystem_files_free{ip=\"$ip\"})",
     "legendFormat": "iNode Free"
    },
    {
     "expr": "max by (device) (node_filesystem_files{ip=\"$ip\"}) - max by (device) (node_filesystem_files_free{ip=\"$ip\"})",
     "legendFormat": "iNode Used"
    },
    {
     "expr": "1 - max by (device) (node_filesystem_files_free{ip=\"$ip\"}) /  max by (device) (node_filesystem_files{ip=\"$ip\"})",
     "legendFormat": "iNode Usage"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "y": 69, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}",
     "legendFormat": "{{ device }}:{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Space Exhaust Estimate",
   "type": "graph",
   "gridPos": { "y": 69, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node:fs:space_exhaust{ip=\"$ip\"}",
     "legendFormat": "{{ device }}:{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "FD Usage",
   "type": "graph",
   "gridPos": { "y": 78, "h": 5, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{ip=\"$ip\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filefd_allocated{ip=\"$ip\"} / node_filefd_maximum{ip=\"$ip\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "iNode Used",
   "type": "graph",
   "gridPos": { "y": 78, "h": 5, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mountpoint) (node_filesystem_files{ip=\"$ip\", fstype!=\"rootfs\"} - node_filesystem_files_free{ip=\"$ip\", fstype!=\"rootfs\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "graph",
   "gridPos": { "y": 83, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:dev:disk_read_iops{ip=\"$ip\"}",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "node:dev:disk_write_iops{ip=\"$ip\"}",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "graph",
   "gridPos": { "y": 83, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:dev:disk_read_rate{ip=\"$ip\"}",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "node:dev:disk_write_rate{ip=\"$ip\"}",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Response Time",
   "type": "graph",
   "gridPos": { "y": 89, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node:dev:disk_read_rt{ip=\"$ip\"}",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "node:dev:disk_write_rt{ip=\"$ip\"}",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Average Bytes",
   "type": "graph",
   "gridPos": { "y": 89, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node:dev:disk_read_rate{ip=\"$ip\"} / node:dev:disk_read_iops{ip=\"$ip\"}",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "node:dev:disk_write_rate{ip=\"$ip\"} / node:dev:disk_write_iops{ip=\"$ip\"}",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "IO in progress",
   "type": "graph",
   "gridPos": { "y": 95, "h": 5, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{ip=\"$ip\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Weighted IO Time",
   "type": "graph",
   "gridPos": { "y": 95, "h": 5, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{ip=\"$ip\"}[1m])",
     "legendFormat": "⬆️{{ device }}"
    }
   ]
  },
  { "title": "Interface / Network", "type": "row", "gridPos": { "y": 100, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Transmit/Receive Packets",
   "type": "graph",
   "gridPos": { "y": 101, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{ip=\"$ip\", device!=\"lo\"}[1m])",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{ip=\"$ip\", device!=\"lo\"}[1m])",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth",
   "type": "graph",
   "gridPos": { "y": 101, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:dev:network_tx{ip=\"$ip\", device!=\"lo\"}",
     "legendFormat": "⬆️{{ device }}"
    },
    {
     "expr": "node:dev:network_rx{ip=\"$ip\", device!=\"lo\"}",
     "legendFormat": "⬇️{{ device }}"
    }
   ]
  },
  {
   "title": "TCP Segments",
   "type": "graph",
   "gridPos": { "y": 108, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "node:ins:tcp_insegs{ip=\"$ip\"}",
     "legendFormat": "⬆️in"
    },
    {
     "expr": "node:ins:tcp_outsegs{ip=\"$ip\"}",
     "legendFormat": "⬇️out"
    }
   ]
  },
  {
   "title": "UDP Segments",
   "type": "graph",
   "gridPos": { "y": 108, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{ip=\"$ip\"}[1m])",
     "legendFormat": "⬆️in"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{ip=\"$ip\"}[1m])",
     "legendFormat": "⬇️out"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "y": 114, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{ip=\"$ip\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "TCP Retransmit",
   "type": "graph",
   "gridPos": { "y": 114, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "node:ins:tcp_retranssegs{ip=\"$ip\"}",
     "legendFormat": "Retrans Segs"
    },
    {
     "expr": "node:ins:tcp_retrans_rate{ip=\"$ip\"}",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "TCP Socket Stat",
   "type": "graph",
   "gridPos": { "y": 120, "h": 6, "w": 8, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{ip=\"$ip\"}",
     "legendFormat": "Using"
    },
    {
     "expr": "node_sockstat_TCP_tw{ip=\"$ip\"}",
     "legendFormat": "Time Wait"
    }
   ]
  },
  {
   "title": "TCP Open",
   "type": "graph",
   "gridPos": { "y": 120, "h": 6, "w": 8, "x": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{ip=\"$ip\"}[1m])",
     "legendFormat": "active"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{ip=\"$ip\"}[1m])",
     "legendFormat": "passive"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "graph",
   "gridPos": { "y": 120, "h": 6, "w": 8, "x": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{ip=\"$ip\"}[1m])",
     "legendFormat": "Listen Overflows"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{ip=\"$ip\"}[1m])",
     "legendFormat": "Listen Drop"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{ip=\"$ip\"}[1m])",
     "legendFormat": "Retrans"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{ip=\"$ip\"}[1m])",
     "legendFormat": "In Error"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "y": 126, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Time Sync",
   "type": "graph",
   "gridPos": { "y": 127, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_timex_sync_status{ip=\"$ip\"}",
     "legendFormat": "Synced"
    },
    {
     "expr": "node_timex_frequency_adjustment_ratio{ip=\"$ip\"}",
     "legendFormat": "Adjust"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "graph",
   "gridPos": { "y": 127, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_ntp_offset_seconds{ip=\"$ip\"}",
     "legendFormat": "Offset"
    },
    {
     "expr": "node_timex_offset_seconds{ip=\"$ip\"}",
     "legendFormat": "Drift"
    }
   ]
  },
  {
   "title": "Node Exporter Duration",
   "type": "graph",
   "gridPos": { "y": 133, "h": 5, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{ip=\"$ip\"}",
     "legendFormat": "{{ collector }}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "y": 133, "h": 17, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{ip=\"$ip\", state=\"active\"}"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "graph",
   "gridPos": { "y": 138, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{ip=\"$ip\"}",
     "legendFormat": "{{ chip }}"
    }
   ]
  },
  {
   "title": "Hardware Power",
   "type": "graph",
   "gridPos": { "y": 144, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{ip=\"$ip\"}"
    }
   ]
  }
 ]
}