{
 "title": "PG Cluster",
 "description": "PG cluster overview",
 "tags": [
  "PG",
  "Cluster"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": "label_values(pg_up{}, cls)" },
   {
    "name": "svc",
    "label": "Service",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, svc)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, role)"
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, ins)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_age{cls=\"$cls\"}, datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 0, "h": 6, "w": 12, "x": 8 },
   "targets": [
    {
     "expr": "min by (ins,ip,svc) (pg_status{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "y": 0, "h": 4, "w": 4, "x": 20 },
   "targets": [
    {
     "expr": "count by (svc) (pg_up{cls=\"$cls\"})",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "title": "Cluster ID",
   "type": "stat",
   "gridPos": { "y": 2, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls,cluster_id)(pg_meta_info{ins=\"$ins\"})",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "y": 2, "h": 2, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls,version) (pg_meta_info{ins=\"$ins\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "y": 4, "h": 2, "w": 4, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:size{cls=\"$cls\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Main LB",
   "type": "stat",
   "gridPos": { "y": 4, "h": 2, "w": 4, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{cls=\"$cls\"}) > 0",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "table",
   "gridPos": { "y": 4, "h": 2, "w": 4, "x": 20 },
   "targets": [
    {
     "expr": "max by (datname)(pg_database_age{cls=\"$cls\", datname!~\"template0|template1|postgres\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 6, "h": 7, "w": 8, "x": 0 },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 6, "h": 3, "w": 12, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_load1{cls=\"$cls\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "count(pg_up{cls=\"$cls\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (svc) (pg_up{cls=\"$cls\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(count by (datname) (pg_database_age{cls=\"$cls\", datname!~\"template0|template1|postgres\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(node:ins:cpu_count{cls=\"$cls\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=\"$cls\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (ins, mountpoint)(node_filesystem_size_bytes{cls=\"$cls\", fstype!=\"rootfs\"}))",
     "legendFormat": "Disk"
    },
    {
     "expr": "max by (cls) (node_network_speed_bytes{cls=\"$cls\"}) * 8 or on() vector(1000000000)",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "graph",
   "gridPos": { "y": 6, "h": 3, "w": 4, "x": 20 },
   "targets": [
    {
     "expr": "(max by (ins) (pg_status{cls=\"$cls\"})) == 3",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 9, "h": 4, "w": 16, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:load1{cls=\"$cls\"})",
     "legendFormat": "cluster"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 13, "h": 12, "w": 8, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:tps_realtime{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "sum(pg:cls:qps_realtime{cls=\"$cls\"})",
     "legendFormat": "QPS"
    },
    {
     "expr": "sum(pg:cls:commits_realtime{cls=\"$cls\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(pg:cls:rollbacks_realtime{cls=\"$cls\"})",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "max(pg_replication_replay_lag{cls=\"$cls\", application_name!=\"pg_receivewal\"})",
     "legendFormat": "Lag Time"
    },
    {
     "expr": "pg:svc:query_rt{cls=\"$cls\", role=\"primary\"}",
     "legendFormat": "Primary RT"
    },
    {
     "expr": "pg:svc:query_rt{cls=\"$cls\", role=\"replica\"}",
     "legendFormat": "Replica RT"
    },
    {
     "expr": "max(node:cls:ntp_offset_range{cls=\"$cls\"})",
     "legendFormat": "Time Offset"
    },
    {
     "expr": "max(pg_replication_replay_diff{cls=\"$cls\"})",
     "legendFormat": "Lag Size"
    },
    {
     "expr": "sum(pg:ins:active_servers{cls=\"$cls\"})",
     "legendFormat": "Active Servers"
    },
    {
     "expr": "sum(pg:ins:waiting_clients{cls=\"$cls\"})",
     "legendFormat": "Queue Clients"
    },
    {
     "expr": "max(pg:cls:age{cls=\"$cls\"}) / 2147483648",
     "legendFormat": "Age"
    },
    {
     "expr": "max(node:fs:space_usage{cls=\"$cls\"})",
     "legendFormat": "FS Space"
    },
    {
     "expr": "max(node:cls:disk_io_rate{cls=\"$cls\"})",
     "legendFormat": "Disk IO"
    },
    {
     "expr": "sum(node:cls:mem_usage{cls=\"$cls\"})",
     "legendFormat": "Mem Usage"
    },
    {
     "expr": "sum(node:cls:cpu_usage{cls=\"$cls\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 13, "h": 6, "w": 3, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:saturation0{cls=\"$cls\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "y": 13, "h": 6, "w": 13, "x": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg:cls:saturation0{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "max by (ins) (pg:ins:saturation0{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 19, "h": 6, "w": 3, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cls=\"$cls\", alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "y": 19, "h": 6, "w": 13, "x": 11 },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Replication Overview",
   "type": "table",
   "gridPos": { "y": 25, "h": 6, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "label_replace(pg_walreceiver_last_tli{cls=\"$cls\"}, \"client_addr\" , \"$1\",  \"ip\", \"(.*)\" )"
    },
    {
     "expr": "label_replace(pg_replication_replay_diff{cls=\"$cls\"}, \"sender\" , \"$1\",  \"ins\", \"(.*)\" )"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "y": 31, "h": 13, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(pg_table_tbl_scan{cls=\"$cls\", datname=\"$datname\"}[1h])) by (relname) > 0"
    },
    {
     "expr": "sum(pg_class_relsize{cls=\"$cls\", datname=\"$datname\"}) by (relname) "
    },
    {
     "expr": "sum(pg_class_reltuples{cls=\"$cls\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "y": 31, "h": 13, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (ins,datname,query) (pg_query_calls{cls=\"$cls\"})"
    },
    {
     "expr": "max by (query) (pg_query_total_time{cls=\"$cls\"})"
    },
    {
     "expr": "max by (query) (pg_query_mean_time{cls=\"$cls\"})"
    },
    {
     "expr": "max by (query) (pg:query:rt{cls=\"$cls\"})"
    },
    {
     "expr": "max by (query) (rate(pg_query_calls{cls=\"$cls\"}[1h]))"
    },
    {
     "expr": "max by (query) (rate(pg_query_total_time{cls=\"$cls\"}[1h]))"
    }
   ]
  }
 ]
}