{
 "title": "PG Cluster Replication",
 "description": "PG Cluster Replication Overview Dashboard",
 "tags": [
  "PG",
  "Cluster"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": "label_values(pg_up{}, cls)" },
   {
    "name": "svc",
    "label": "Service",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, svc)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, role)"
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{cls=\"$cls\", role=\"primary\"}, ins)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_age{cls=\"$cls\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Identity", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 1, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 8, "w": 12, "x": 4 },
   "targets": [
    {
     "expr": "min by (ins,ip) (pg_status{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load0{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 8, "w": 8, "x": 16 },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "title": "Main LB",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls, ins) (haproxy_backend_current_sessions) > 0",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 4, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:size{cls=\"$cls\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  { "title": "Replication Topo", "type": "row", "gridPos": { "y": 9, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "table",
   "gridPos": { "y": 10, "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "label_replace(pg_walreceiver_last_tli{cls=\"$cls\"}, \"client_addr\" , \"$1\",  \"ip\", \"(.*)\" )"
    },
    {
     "expr": "label_replace(pg_replication_replay_diff{cls=\"$cls\"}, \"sender\" , \"$1\",  \"ins\", \"(.*)\" )"
    }
   ]
  },
  {
   "title": "Primary Connection Info",
   "type": "table",
   "gridPos": { "y": 15, "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "pg_meta_info{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "y": 20, "h": 3, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:size{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Primary",
   "type": "stat",
   "gridPos": { "y": 20, "h": 3, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:leader{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "y": 20, "h": 3, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max by (ins) (pg_in_recovery{cls=\"$cls\"} == 1))"
    }
   ]
  },
  {
   "title": "Max Senders",
   "type": "stat",
   "gridPos": { "y": 20, "h": 3, "w": 3, "x": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_wal_senders{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "WAL Source (Primary/Bridge)",
   "type": "table",
   "gridPos": { "y": 20, "h": 4, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (ins, role, ip) (pg_replication_lsn{cls=\"$cls\", state=\"streaming\"} > 0)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "y": 23, "h": 3, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:size{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "WAL Senders",
   "type": "stat",
   "gridPos": { "y": 23, "h": 3, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(pg_replication_lsn{cls=\"$cls\"}))"
    }
   ]
  },
  {
   "title": "WAL Receivers",
   "type": "stat",
   "gridPos": { "y": 23, "h": 3, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(pg_walreceiver_last_tli{cls=\"$cls\"}))"
    }
   ]
  },
  {
   "title": "Cascading",
   "type": "stat",
   "gridPos": { "y": 23, "h": 3, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:cascading{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Sync Commit Mode",
   "type": "stat",
   "gridPos": { "y": 24, "h": 2, "w": 6, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:synchronous{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Sync Standby Names",
   "type": "stat",
   "gridPos": { "y": 24, "h": 2, "w": 6, "x": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (names) (pg_sync_standby_enabled{ins=\"$ins\"})",
     "legendFormat": "{{ names }}"
    }
   ]
  },
  {
   "title": "Lag Bytes",
   "type": "gauge",
   "gridPos": { "y": 26, "h": 6, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_replay_diff{cls=\"$cls\",  application_name!=\"pg_receivewal\"})"
    }
   ]
  },
  {
   "title": "Lag Secs",
   "type": "gauge",
   "gridPos": { "y": 26, "h": 6, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_replay_lag{cls=\"$cls\", application_name!=\"pg_receivewal\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "gauge",
   "gridPos": { "y": 26, "h": 6, "w": 4, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(node:cls:ntp_offset_range{cls=\"$cls\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Leadership / Timeline",
   "type": "graph",
   "gridPos": { "y": 26, "h": 6, "w": 5, "x": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (ins) (topk(1, pg_checkpoint_tli{cls=\"$cls\"} - pg_is_in_recovery))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Downstream Count",
   "type": "graph",
   "gridPos": { "y": 26, "h": 6, "w": 7, "x": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_downstream_count{cls=\"$cls\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Replication Metrics", "type": "row", "gridPos": { "y": 32, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Replication Lag: Replay Lag (bytes)",
   "type": "graph",
   "gridPos": { "y": 33, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_replay_diff{cls=\"$cls\", application_name!=\"pg_receivewal\"}",
     "legendFormat": "{{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  {
   "title": "Replication Lag: Replay Lag (seconds)",
   "type": "graph",
   "gridPos": { "y": 33, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_replication_replay_lag{cls=\"$cls\", application_name!=\"pg_receivewal\"}",
     "legendFormat": "{{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  {
   "title": "Replication Lag: Flush Lag (bytes)",
   "type": "graph",
   "gridPos": { "y": 40, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_flush_diff{cls=\"$cls\", application_name!=\"pg_receivewal\"}",
     "legendFormat": "{{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  {
   "title": "Replication Lag (Standby's View)",
   "type": "graph",
   "gridPos": { "y": 40, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg:ins:lag_seconds{cls=\"$cls\", role!=\"primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag: Write Lag (bytes)",
   "type": "graph",
   "gridPos": { "y": 47, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_write_diff{cls=\"$cls\", application_name!=\"pg_receivewal\"}",
     "legendFormat": "{{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "graph",
   "gridPos": { "y": 47, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_ntp_offset_seconds{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag: Detailed",
   "type": "graph",
   "gridPos": { "y": 54, "h": 8, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_lsn{cls=\"$cls\"} - pg_replication_sent_lsn{cls=\"$cls\"}",
     "legendFormat": "[SENT] {{ application_name }} {{ ip }} -> {{ client_addr }}"
    },
    {
     "expr": "pg_replication_sent_lsn{cls=\"$cls\"} - pg_replication_write_lsn{cls=\"$cls\"}",
     "legendFormat": "[WRITE] {{ application_name }} {{ ip }} -> {{ client_addr }}"
    },
    {
     "expr": "pg_replication_write_lsn{cls=\"$cls\"} - pg_replication_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[FLUSH] {{ application_name }} {{ ip }} -> {{ client_addr }}"
    },
    {
     "expr": "pg_replication_replay_lsn{cls=\"$cls\"} - pg_replication_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[REPLAY] {{ application_name }} {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  {
   "title": "Primary LSN Progress",
   "type": "graph",
   "gridPos": { "y": 62, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "hex" }
   ],
   "targets": [
    {
     "expr": "pg_lsn{ins=\"$ins\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{ins=\"$ins\"}",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "pg_checkpoint_redo_lsn{ins=\"$ins\"}",
     "legendFormat": "Redo"
    }
   ]
  },
  {
   "title": "Cluster LSN Progress",
   "type": "graph",
   "gridPos": { "y": 62, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "hex" }
   ],
   "targets": [
    {
     "expr": "max(pg_replication_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_replication_replay_lsn{cls=\"$cls\"}",
     "legendFormat": "[REPLAY] {{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    },
    {
     "expr": "pg_replication_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[FLUSH] {{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    },
    {
     "expr": "pg_replication_write_lsn{cls=\"$cls\"}",
     "legendFormat": "[WRITE] {{ application_name }} [{{ sync_state }}:{{ state }}] {{ ip }} -> {{ client_addr }}"
    }
   ]
  },
  { "title": "Replication Slots", "type": "row", "gridPos": { "y": 71, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "table",
   "gridPos": { "y": 72, "h": 4, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ slot_name }}|"
    },
    {
     "expr": "pg_slot_restart_lsn{cls=\"$cls\"}"
    },
    {
     "expr": "pg_slot_xmin{cls=\"$cls\"}"
    },
    {
     "expr": "pg_slot_active{cls=\"$cls\"}"
    },
    {
     "expr": "pg_slot_temporary{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Max Slots",
   "type": "stat",
   "gridPos": { "y": 76, "h": 4, "w": 3, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_replication_slots{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "gridPos": { "y": 76, "h": 4, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(pg_slot_active{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Active Slots",
   "type": "stat",
   "gridPos": { "y": 76, "h": 4, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(pg_slot_active{cls=\"$cls\"} == 1)"
    }
   ]
  },
  {
   "title": "Temp Slots",
   "type": "stat",
   "gridPos": { "y": 76, "h": 4, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(pg_slot_temporary{cls=\"$cls\"} == 1)"
    }
   ]
  },
  {
   "title": "Slot Retained Bytes",
   "type": "graph",
   "gridPos": { "y": 76, "h": 11, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ slot_name }}"
    }
   ]
  },
  {
   "title": "Slot Retained XID",
   "type": "graph",
   "gridPos": { "y": 80, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(pg_xact_xmax{cls=\"$cls\", role=\"primary\"})",
     "legendFormat": "XMAX"
    },
    {
     "expr": "pg_xact_xmin{cls=\"$cls\", role=\"primary\"}",
     "legendFormat": "XMIN"
    },
    {
     "expr": "max(pg_slot_xmin{cls=\"$cls\"})",
     "legendFormat": "{{ slot_name }}:XMIN"
    },
    {
     "expr": "pg_slot_catalog_xmin{cls=\"$cls\"}",
     "legendFormat": "{{ slot_name }}:C-XMIN"
    }
   ]
  }
 ]
}