{
 "title": "PG Database",
 "description": "Postgres Database Dashboard",
 "tags": [
  "PG",
  "Database"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"pg\"}, ins)"
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
   },
   {
    "name": "svc",
    "label": "Service",
    "query": "label_values(pg_up{ins=\"$ins\"}, svc)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{ins=\"$ins\"}, role)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_age{ins=\"$ins\"}, datname)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "gridPos": { "y": 1, "h": 2, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${datname}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 6, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "min by (ins,ip) (pg_status{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load0{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_in_recovery{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (pg_meta_info{ins=\"$ins\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "DB Age",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_database_age{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Checksum",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_data_checksums{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Pool Disabled",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 4, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pg:db:pool_disabled{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Pool Pause",
   "type": "stat",
   "gridPos": { "y": 7, "h": 2, "w": 4, "x": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pg:db:pool_paused{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 7, "h": 6, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "max by (datname) (pg_database_age{ins=\"$ins\"})"
    },
    {
     "expr": "max by (datname) (pg_database_is_template{ins=\"$ins\"})"
    },
    {
     "expr": "max by (datname) (pg_database_allow_conn{ins=\"$ins\"})"
    },
    {
     "expr": "max by (datname) (pg_database_conn_limit{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "PG Databases",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 4, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (datname) (pg_database_age{ins=\"$ins\"}))"
    }
   ]
  },
  {
   "title": "Instance Users",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 4, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:pool_users{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Database Users",
   "type": "stat",
   "gridPos": { "y": 9, "h": 2, "w": 4, "x": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(pg:pool:active_clients{ins=\"$ins\", datname=\"$datname\"}) by (user))"
    }
   ]
  },
  {
   "title": "PGB Databases",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 4, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (datname) (pgbouncer_pool_active_clients{ins=\"$ins\"}))"
    }
   ]
  },
  {
   "title": "Instance Pools",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 4, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:pools{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Database Pools",
   "type": "stat",
   "gridPos": { "y": 11, "h": 2, "w": 4, "x": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg:pool:active_clients{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Xact",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:xacts{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:tps{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:qps{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "gauge",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:backends{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 13, "h": 4, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "pg:db:pool_size{ins=\"$ins\", datname=\"$datname\"}"
    },
    {
     "expr": "max by (host) (pg:db:pool_reserve_size{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (host) (pg:db:pool_current_conn{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (host) (pg:db:pool_disabled{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (host) (pg:db:pool_paused{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "PG Load1",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:load1{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Xact RT",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:xact_rt{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Query RT",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:query_rt{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:active_clients{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Queue Clients",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:waiting_clients{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "iXact Servers",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:sessions{ins=\"$ins\", datname=\"$datname\", state=~\"idle in.*\"})"
    }
   ]
  },
  {
   "title": "Rollback Rate",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:rollbacks{ins=\"$ins\", datname=\"$datname\"} / pg:db:xacts{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Age",
   "type": "gauge",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_database_age{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "y": 21, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "table",
   "gridPos": { "y": 22, "h": 10, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    },
    {
     "expr": "sum(pg_class_reltuples{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "title": "Relation Size",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "y": 22, "h": 10, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "y": 32, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Seasonality",
     "type": "graph",
     "gridPos": { "y": 3, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:ins:tps{ins=\"$ins\"}",
       "legendFormat": "TPS"
      },
      {
       "expr": "pg:ins:tps{ins=\"$ins\"} OFFSET 1d",
       "legendFormat": "TPS -1D"
      },
      {
       "expr": "pg:ins:tps{ins=\"$ins\"} OFFSET 2d",
       "legendFormat": "TPS -2D"
      },
      {
       "expr": "pg:ins:commits{ins=\"$ins\"}",
       "legendFormat": "Commit"
      },
      {
       "expr": "pg:ins:rollbacks{ins=\"$ins\"}",
       "legendFormat": "Rollback"
      }
     ]
    },
    {
     "title": "Prepared Transaction",
     "type": "stat",
     "gridPos": { "y": 3, "h": 2, "w": 6, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_prepared_transactions{ins=\"$ins\"} > bool 0"
      }
     ]
    },
    {
     "title": "Locks Limit per xact",
     "type": "stat",
     "gridPos": { "y": 3, "h": 2, "w": 6, "x": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_locks_per_transaction{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Rollbacks in 1min",
     "type": "graph",
     "gridPos": { "y": 5, "h": 5, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(pg_db_xact_rollback{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "Rollbacks"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "graph",
     "gridPos": { "y": 10, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:tps{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "TPS"
      },
      {
       "expr": "pg:db:tps_avg30m{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "pg:db:tps_avg30m{ins=\"$ins\", datname=\"$datname\"} + pg:db:tps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "pg:db:tps_avg30m{ins=\"$ins\", datname=\"$datname\"} - pg:db:tps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "pg:db:tps_avg30m{ins=\"$ins\", datname=\"$datname\"} + 3 * pg:db:tps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "pg:ins:tps_avg30m{ins=\"$ins\"} - 3 * pg:ins:tps_sigma{ins=\"$ins\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Xact RT",
     "type": "graph",
     "gridPos": { "y": 10, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg:db:xact_rt{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "RT"
      },
      {
       "expr": "pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} + pg:db:xact_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} - pg:db:xact_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} + 3 * pg:db:xact_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} - 3 * pg:db:xact_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "TPS Divergence",
     "type": "graph",
     "gridPos": { "y": 17, "h": 4, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(pg:db:tps_sigma{ins=\"$ins\", datname=\"$datname\"} / pg:db:tps_mu{ins=\"$ins\", datname=\"$datname\"}) ^ 2",
       "legendFormat": "TPS Divergence"
      }
     ]
    },
    {
     "title": "Xact RT Divergence",
     "type": "graph",
     "gridPos": { "y": 17, "h": 4, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(pg:db:xact_rt_sigma{ins=\"$ins\", datname=\"$datname\"} / pg:db:xact_rt_avg30m{ins=\"$ins\", datname=\"$datname\"}) ^ 2",
       "legendFormat": "Xact RT Divergence"
      }
     ]
    },
    {
     "title": "Locks by Category",
     "type": "graph",
     "gridPos": { "y": 21, "h": 10, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg:db:xlock{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Exclusive"
      },
      {
       "expr": "pg:db:wlock{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "pg:db:rlock{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "graph",
     "gridPos": { "y": 21, "h": 10, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (pg_lock_count{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "y": 33, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS Seasonality",
     "type": "graph",
     "gridPos": { "y": 4, "h": 6, "w": 24, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:qps{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "QPS"
      },
      {
       "expr": "pg:db:qps{ins=\"$ins\", datname=\"$datname\"} OFFSET 1d",
       "legendFormat": "QPS -1D"
      },
      {
       "expr": "pg:db:qps{ins=\"$ins\", datname=\"$datname\"} OFFSET 2d",
       "legendFormat": "QPS -2D"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "y": 10, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:qps{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "QPS"
      },
      {
       "expr": "pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"} + pg:db:qps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"} - pg:db:qps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"} + 3 * pg:db:qps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"} - 3 * pg:db:qps_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Query RT",
     "type": "graph",
     "gridPos": { "y": 10, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg:db:query_rt{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "RT"
      },
      {
       "expr": "pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "µ"
      },
      {
       "expr": "pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} + pg:db:query_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+σ"
      },
      {
       "expr": "pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} - pg:db:query_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-σ"
      },
      {
       "expr": "pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} + 3 * pg:db:query_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "+3σ"
      },
      {
       "expr": "pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"} - 3 * pg:db:query_rt_sigma{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "QPS Divergence",
     "type": "graph",
     "gridPos": { "y": 17, "h": 4, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(pg:db:qps_sigma{ins=\"$ins\", datname=\"$datname\"} / pg:db:qps_avg30m{ins=\"$ins\", datname=\"$datname\"}) ^ 2",
       "legendFormat": "QPS Divergence"
      }
     ]
    },
    {
     "title": "Query RT Divergence",
     "type": "graph",
     "gridPos": { "y": 17, "h": 4, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(pg:db:query_rt_sigma{ins=\"$ins\", datname=\"$datname\"} / pg:db:query_rt_avg30m{ins=\"$ins\", datname=\"$datname\"}) ^ 2",
       "legendFormat": "RT Divergence"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "y": 34, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Scan",
     "type": "graph",
     "gridPos": { "y": 5, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Sequential Scan",
     "type": "graph",
     "gridPos": { "y": 5, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Index Access",
     "type": "graph",
     "gridPos": { "y": 13, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Function Call",
     "type": "graph",
     "gridPos": { "y": 13, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tuples",
   "type": "row",
   "gridPos": { "y": 35, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tuple Selected",
     "type": "graph",
     "gridPos": { "y": 6, "h": 6, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg:db:tup_selected{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Tuple Touched",
     "type": "graph",
     "gridPos": { "y": 6, "h": 6, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg:db:tup_touched{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Tuple Read/Write",
     "type": "graph",
     "gridPos": { "y": 12, "h": 6, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:tup_selected{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "SELECTED"
      },
      {
       "expr": "pg:db:tup_modified{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "MODIFIED"
      }
     ]
    },
    {
     "title": "Tuple Modified",
     "type": "graph",
     "gridPos": { "y": 12, "h": 6, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:tup_inserted{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "INSERTED"
      },
      {
       "expr": "pg:db:tup_updated{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "UPDATED"
      },
      {
       "expr": "pg:db:tup_deleted{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "DELETED"
      }
     ]
    }
   ]
  },
  {
   "title": "Statement",
   "type": "row",
   "gridPos": { "y": 36, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Statementes",
     "type": "table",
     "gridPos": { "y": 7, "h": 18, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (query) (pg_query_total_time{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (query) (pg_query_mean_time{ins=\"$ins\", datname=\"$datname\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (query) (pg:query:rt{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (query) (rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[1h]))"
      },
      {
       "expr": "max by (query) (rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1h]))"
      },
      {
       "expr": "min by (query) (pg_query_min_time{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (query) (pg_query_max_time{ins=\"$ins\", datname=\"$datname\"})"
      }
     ]
    },
    {
     "title": "Statement RT Ranking",
     "type": "graph",
     "gridPos": { "y": 7, "h": 9, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(64, pg_query_mean_time{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ query }}"
      }
     ]
    },
    {
     "title": "Statement RT",
     "type": "graph",
     "gridPos": { "y": 16, "h": 9, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg:query:rt{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ query }}"
      }
     ]
    },
    {
     "title": "Statement Call",
     "type": "graph",
     "gridPos": { "y": 25, "h": 9, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pg:query:call{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ query }}"
      }
     ]
    },
    {
     "title": "Statement Total Time Ranking",
     "type": "graph",
     "gridPos": { "y": 25, "h": 9, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(32, pg_query_total_time{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ query }}"
      }
     ]
    },
    {
     "title": "Statement Time (Stacked)",
     "type": "graph",
     "gridPos": { "y": 34, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ query }}"
      }
     ]
    },
    {
     "title": "Statement Time Spent in Last 1h",
     "type": "grafana-piechart-panel",
     "gridPos": { "y": 34, "h": 8, "w": 12, "x": 12 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1h])",
       "legendFormat": "{{ query }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "y": 37, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "y": 8, "h": 2, "w": 6, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_connections{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Max Worker",
     "type": "stat",
     "gridPos": { "y": 8, "h": 2, "w": 6, "x": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_worker_processes{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Backend State",
     "type": "graph",
     "gridPos": { "y": 8, "h": 9, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg:db:sessions{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Backend Processes",
     "type": "graph",
     "gridPos": { "y": 10, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_backend_count{ins=\"$ins\"}",
       "legendFormat": "{{ backend_type }}"
      }
     ]
    },
    {
     "title": "Backend Active",
     "type": "graph",
     "gridPos": { "y": 17, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\", datname=\"$datname\", state=\"active\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Idle In Transactions",
     "type": "graph",
     "gridPos": { "y": 17, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\", datname=\"$datname\", state=~\"idle in.*\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Backend Wait Event",
     "type": "graph",
     "gridPos": { "y": 24, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (event) (pg_wait_count{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "Sage",
     "type": "graph",
     "gridPos": { "y": 24, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (datname, state) (pg_activity_max_tx_duration{ins=\"$ins\", datname=\"$datname\", state!=\"idle|disabled\"})",
       "legendFormat": "{{ datname }} [{{ state }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool",
   "type": "row",
   "gridPos": { "y": 38, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "y": 9, "h": 5, "w": 16, "x": 0 },
     "targets": [
      {
       "expr": "pg:db:pool_size{ins=\"$ins\", datname=\"$datname\"}"
      },
      {
       "expr": "max by (host) (pg:db:pool_reserve_size{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (host) (pg:db:pool_current_conn{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (host) (pg:db:pool_disabled{ins=\"$ins\", datname=\"$datname\"})"
      },
      {
       "expr": "max by (host) (pg:db:pool_paused{ins=\"$ins\", datname=\"$datname\"})"
      }
     ]
    },
    {
     "title": "Pool Connection Usage",
     "type": "graph",
     "gridPos": { "y": 9, "h": 5, "w": 8, "x": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg:db:pool_current_conn{ins=\"$ins\", datname=\"$datname\"} / pg:db:pool_max_conn{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Server State",
     "type": "graph",
     "gridPos": { "y": 14, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:active_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "pg:db:used_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "pg:db:idle_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "pg:db:tested_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Tested"
      },
      {
       "expr": "pg:db:login_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "Login"
      }
     ]
    },
    {
     "title": "Server Active",
     "type": "graph",
     "gridPos": { "y": 14, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:active_servers{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Active Clients by Pool",
     "type": "graph",
     "gridPos": { "y": 22, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:pool:active_clients{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ user }}@{{ datname }}"
      }
     ]
    },
    {
     "title": "Active Clients by User",
     "type": "graph",
     "gridPos": { "y": 22, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (user) (pg:pool:active_clients{ins=\"$ins\", datname=\"$datname\"})",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Waiting Clients",
     "type": "graph",
     "gridPos": { "y": 30, "h": 6, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:pool:waiting_clients{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ user }}@{{ datname }}"
      }
     ]
    },
    {
     "title": "Max Queuing Time",
     "type": "graph",
     "gridPos": { "y": 30, "h": 6, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg:pool:maxwait{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ user }}@{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "y": 39, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checksum",
     "type": "stat",
     "gridPos": { "y": 10, "h": 2, "w": 6, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_data_checksums{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Checksum Failures",
     "type": "stat",
     "gridPos": { "y": 10, "h": 2, "w": 6, "x": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_db_checksum_failures{ins=\"$ins\"})"
      }
     ]
    },
    {
     "title": "Database Size and 10m Delta",
     "type": "graph",
     "gridPos": { "y": 10, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg_size_bytes{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "SIZE"
      },
      {
       "expr": "delta(pg_size_bytes{ins=\"$ins\", datname=\"$datname\"}[10m])",
       "legendFormat": "DELTA"
      }
     ]
    },
    {
     "title": "Database Age",
     "type": "graph",
     "gridPos": { "y": 12, "h": 6, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "pg_database_age{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "WAL Rate",
     "type": "graph",
     "gridPos": { "y": 18, "h": 6, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg:ins:wal_rate{ins=\"$ins\"}",
       "legendFormat": "WAL Rate"
      },
      {
       "expr": "pg:ins:ckpt_timed{ins=\"$ins\"}",
       "legendFormat": "Checkpoint"
      },
      {
       "expr": "pg:ins:ckpt_req{ins=\"$ins\"}",
       "legendFormat": "Checkpoint (Request)"
      }
     ]
    },
    {
     "title": "Buffer Hit Rate",
     "type": "graph",
     "gridPos": { "y": 18, "h": 6, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg:db:blks_hit_1m{ins=\"$ins\", datname=\"$datname\"} / pg:db:blks_access_1m{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Blocks Hit",
     "type": "graph",
     "gridPos": { "y": 24, "h": 5, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(pg_db_blks_hit{ins=\"$ins\"}[1m]) * 8192",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Block Read",
     "type": "graph",
     "gridPos": { "y": 24, "h": 5, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(pg_db_blks_read{ins=\"$ins\"}[1m]) * 8192",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Temp File Size",
     "type": "graph",
     "gridPos": { "y": 29, "h": 5, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg:db:temp_bytes{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Temp File Count",
     "type": "graph",
     "gridPos": { "y": 29, "h": 5, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg:db:temp_files{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily Stats",
   "type": "row",
   "gridPos": { "y": 40, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "y": 11, "h": 3, "w": 24, "x": 0 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(avg_over_time(pg:ins:load15{ins=\"$ins\"}[1d]))",
       "legendFormat": "Avg Load"
      },
      {
       "expr": "max(max_over_time(pg:ins:load15{ins=\"$ins\"}[1d]))",
       "legendFormat": "Max Load"
      },
      {
       "expr": "sum(increase(pg_db_xact_total{ins=\"$ins\", datname=\"$datname\"}[1d]))",
       "legendFormat": "DB Xacts"
      },
      {
       "expr": "sum(increase(pg_db_xact_rollback{ins=\"$ins\", datname=\"$datname\"}[1d]))",
       "legendFormat": "DB Rollbacks"
      },
      {
       "expr": "sum(increase(pgbouncer_stat_total_xact_count{ins=\"$ins\", datname=\"$datname\"}[1d]))",
       "legendFormat": "Pool Xacts"
      },
      {
       "expr": "sum(increase(pgbouncer_stat_total_query_count{ins=\"$ins\", datname=\"$datname\"}[1d]))",
       "legendFormat": "Pool Queries"
      },
      {
       "expr": "sum(increase(pg_db_tup_returned{ins=\"$ins\", datname=\"$datname\"}[1d]))",
       "legendFormat": "Rows Returned"
      },
      {
       "expr": "sum(increase(pg_db_tup_modified{ins=\"$ins\", datname=\"$datname\"}[1d])) * 8",
       "legendFormat": "Rows Modified"
      }
     ]
    }
   ]
  }
 ]
}