{
 "title": "PG Query",
 "description": "PG Query Detail",
 "tags": [
  "PG",
  "Database",
  "Query"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=\"pg\"}, ins)"
    }
   },
   {
    "name": "datname",
    "label": "Datname",
    "query": {
     "query": "label_values(pg_database_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "query",
    "label": "Query",
    "query": {
     "query": "label_values(pg:query:call{ins=\"$ins\", datname=\"$datname\"}, query)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, role)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query Overview", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Database Statementes",
   "type": "table",
   "gridPos": { "y": 1, "h": 11, "w": 17, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (query) (pg_query_total_time{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (query) (pg_query_mean_time{ins=\"$ins\", datname=\"$datname\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (query) (pg:query:rt{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (query) (rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[1h]))"
    },
    {
     "expr": "max by (query) (rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1h]))"
    },
    {
     "expr": "min by (query) (pg_query_min_time{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "max by (query) (pg_query_max_time{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Statement Time Spent in Last 1h",
   "type": "grafana-piechart-panel",
   "gridPos": { "y": 1, "h": 11, "w": 7, "x": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "graph",
   "gridPos": { "y": 12, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "pg:query:call{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "graph",
   "gridPos": { "y": 12, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg:query:rt{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spend per Second",
   "type": "graph",
   "gridPos": { "y": 19, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_query_total_time{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT Ranking",
   "type": "graph",
   "gridPos": { "y": 19, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(64, pg_query_mean_time{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  { "title": "Query Detail", "type": "row", "gridPos": { "y": 26, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "y": 27, "h": 9, "w": 18, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "QPS"
    },
    {
     "expr": "avg_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "µ"
    },
    {
     "expr": "avg_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) + stddev_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) - stddev_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) + 3 * stddev_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) - 3 * stddev_over_time(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "RT Stddev",
   "type": "singlestat",
   "gridPos": { "y": 27, "h": 3, "w": 3, "x": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_query_stddev_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "Avg Blk IO",
   "type": "singlestat",
   "gridPos": { "y": 27, "h": 3, "w": 3, "x": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(pg_query_blk_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"} / 1000)"
    }
   ]
  },
  {
   "title": "1D Calls",
   "type": "singlestat",
   "gridPos": { "y": 30, "h": 3, "w": 3, "x": 18 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1d]))"
    }
   ]
  },
  {
   "title": "RT Min",
   "type": "singlestat",
   "gridPos": { "y": 30, "h": 3, "w": 3, "x": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(pg_query_min_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "y": 33, "h": 3, "w": 3, "x": 18 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "RT Max",
   "type": "singlestat",
   "gridPos": { "y": 33, "h": 3, "w": 3, "x": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_query_max_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "Realtime Response Time",
   "type": "graph",
   "gridPos": { "y": 36, "h": 9, "w": 18, "x": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "RT"
    },
    {
     "expr": "avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "µ"
    },
    {
     "expr": "avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) + stddev_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) - stddev_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) + 3 * stddev_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) - 3 * stddev_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Avg Ret Rows",
   "type": "singlestat",
   "gridPos": { "y": 36, "h": 3, "w": 3, "x": 18 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "RT Realtime",
   "type": "singlestat",
   "gridPos": { "y": 36, "h": 3, "w": 3, "x": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "RT Mean",
   "type": "singlestat",
   "gridPos": { "y": 39, "h": 3, "w": 3, "x": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(pg_query_mean_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "1D Time",
   "type": "singlestat",
   "gridPos": { "y": 39, "h": 3, "w": 3, "x": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(pg_query_total_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1d]))"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "singlestat",
   "gridPos": { "y": 42, "h": 3, "w": 3, "x": 18 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"})"
    }
   ]
  },
  {
   "title": "1D Rows",
   "type": "singlestat",
   "gridPos": { "y": 42, "h": 3, "w": 3, "x": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(increase(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1d]))"
    }
   ]
  },
  {
   "title": "Avg Rows Returned",
   "type": "graph",
   "gridPos": { "y": 45, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "Rows"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "y": 45, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(pg_query_blk_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "Query RT Stats",
   "type": "bargauge",
   "gridPos": { "y": 52, "h": 7, "w": 12, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_query_max_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "max"
    },
    {
     "expr": "pg_query_mean_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "pg_query_min_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "min"
    },
    {
     "expr": "pg_query_stddev_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "stddev"
    }
   ]
  },
  {
   "title": "RT Divergence",
   "type": "graph",
   "gridPos": { "y": 52, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / stddev_over_time(pg:query:rt{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])) ^ 2",
     "legendFormat": "RT"
    }
   ]
  }
 ]
}