{
 "title": "PG Service",
 "description": "PG Service Overview",
 "tags": [
  "PG",
  "Service"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "svc", "label": "Service", "query": "label_values(pg_up{}, svc)" },
   {
    "name": "cls",
    "label": "Cluster",
    "query": "label_values(pg_up{svc=\"$svc\"}, cls)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{svc=\"$svc\"}, role)"
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{svc=\"$svc\"}, ins)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_age{svc=\"$svc\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "y": 1, "h": 2, "w": 8, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${svc}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 6, "w": 8, "x": 8 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 1, "h": 6, "w": 8, "x": 16 },
   "targets": [
    {
     "expr": "min by (ins,ip) (pg_status{svc=\"$svc\"})"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "y": 3, "h": 2, "w": 4, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${role}" }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "y": 5, "h": 2, "w": 4, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_up{svc=\"$svc\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 7, "h": 4, "w": 8, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_load1{svc=\"$svc\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "count(haproxy_backend_current_sessions{proxy=\"$svc\"})",
     "legendFormat": "Proxy"
    },
    {
     "expr": "count by (svc) (pg_up{svc=\"$svc\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "count(count by (datname) (pg_database_age{svc=\"$svc\", datname!~\"template0|template1|postgres\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(node:ins:cpu_count{svc=\"$svc\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{svc=\"$svc\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (ins, mountpoint)(node_filesystem_size_bytes{svc=\"$svc\", fstype!=\"rootfs\"}))",
     "legendFormat": "Disk"
    },
    {
     "expr": "max by (cls) (node_network_speed_bytes{svc=\"$svc\"}) * 8 or on() vector(1000000000)",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 7, "h": 4, "w": 16, "x": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:load0{svc=\"$svc\"})",
     "legendFormat": "cluster"
    },
    {
     "expr": "max by (role) (pg:svc:load0{svc=\"$svc\"})",
     "legendFormat": "{{ role }}"
    },
    {
     "expr": "max by (ins) (pg:ins:load0{svc=\"$svc\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "y": 11, "h": 6, "w": 11, "x": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (ins) (pg:ins:saturation0{svc=\"$svc\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "y": 11, "h": 6, "w": 13, "x": 11 },
   "targets": [
    {
     "expr": "ALERTS{svc=\"$svc\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "y": 17, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Proxy",
   "type": "table",
   "gridPos": { "y": 18, "h": 6, "w": 9, "x": 0 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "sum by (ins) (haproxy_frontend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "y": 18, "h": 6, "w": 15, "x": 9 },
   "targets": [
    {
     "expr": "haproxy_server_status{proxy=~\"$svc\"}"
    },
    {
     "expr": "max by (server) (haproxy_server_weight{proxy=~\"$svc\"})"
    },
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{proxy=~\"$svc\"})"
    }
   ]
  },
  {
   "title": "Route Health",
   "type": "graph",
   "gridPos": { "y": 24, "h": 7, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_status{proxy=\"$svc\"} > 0",
     "legendFormat": "{{ ins }} ➡️ {{ server }}"
    }
   ]
  }
 ]
}