{
 "title": "PG Table Detail",
 "description": "Single table detail in single instance",
 "tags": [
  "PG",
  "Database",
  "Table",
  "Detail"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"pg\"}, ins)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_age{ins=\"$ins\"}, datname)"
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{ins=\"$ins\"}, role)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
   },
   {
    "name": "relname",
    "label": "Relation",
    "query": "label_values(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"}, relname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${datname}" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_in_recovery{ins=\"$ins\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 2, "h": 4, "w": 24, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_class_reltuples{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Tuples"
    },
    {
     "expr": "pg_class_relsize{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "pg_class_relage{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Age"
    },
    {
     "expr": "rate(pg_table_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Tuple Read Rate"
    },
    {
     "expr": "rate(pg_table_n_tup_mod{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Tuple Modify Rate"
    }
   ]
  },
  { "title": "Table Metrics", "type": "row", "gridPos": { "y": 6, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Tuple Read",
   "type": "graph",
   "gridPos": { "y": 7, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Rows Insert / Update /Delete",
   "type": "graph",
   "gridPos": { "y": 7, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "max(rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "max(rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Sequential Scan",
   "type": "graph",
   "gridPos": { "y": 13, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Rows per Sequential Scan (1m)",
   "type": "graph",
   "gridPos": { "y": 13, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_table_seq_tup_read{ins=\"$ins\",  datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_table_seq_scan{ins=\"$ins\",  datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan",
   "type": "graph",
   "gridPos": { "y": 19, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Rows per Index Scan",
   "type": "graph",
   "gridPos": { "y": 19, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / rate(pg_table_idx_scan{ins=\"$ins\",  datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Live",
   "type": "graph",
   "gridPos": { "y": 25, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "Tuple Dead",
   "type": "graph",
   "gridPos": { "y": 25, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Dead"
    }
   ]
  },
  { "title": "Index Metrics", "type": "row", "gridPos": { "y": 31, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Index Access",
   "type": "graph",
   "gridPos": { "y": 32, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=~\"$relname.*\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Rows Accessed",
   "type": "graph",
   "gridPos": { "y": 32, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\", relname=~\"$relname.*\"}[1m]) ",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read",
   "type": "graph",
   "gridPos": { "y": 38, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_class_reltuples{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Avg Rows Accessed",
   "type": "graph",
   "gridPos": { "y": 38, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\", relname=~\"$relname.*\"}[1m]) / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=~\"$relname.*\"}[1m]) ",
     "legendFormat": "{{ relname }}"
    }
   ]
  }
 ]
}