{
 "title": "PG Table",
 "description": "PG Table Overview among single database",
 "tags": [
  "PG",
  "Database",
  "Table"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"pg\"}, ins)"
   },
   {
    "name": "datname",
    "label": "Datname",
    "query": "label_values(pg_database_age{ins=\"$ins\"}, datname)"
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{ins=\"$ins\"}, role)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${cls}" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${datname}" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "${ins}" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_in_recovery{ins=\"$ins\"})"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "y": 2, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Drill into Single Relation",
   "type": "table",
   "gridPos": { "y": 3, "h": 11, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (nspname,relname) "
    },
    {
     "expr": "sum(pg_class_reltuples{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "title": "Relation Size",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "y": 3, "h": 21, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "y": 14, "h": 10, "w": 12, "x": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (relname) ",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Scan", "type": "row", "gridPos": { "y": 24, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Index Scan",
   "type": "graph",
   "gridPos": { "y": 25, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan",
   "type": "graph",
   "gridPos": { "y": 25, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Scanned Tuples",
   "type": "graph",
   "gridPos": { "y": 33, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan -- Scanned Tuples",
   "type": "graph",
   "gridPos": { "y": 33, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Rows per Scan",
   "type": "graph",
   "gridPos": { "y": 41, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Total Scanned  Tuples",
   "type": "graph",
   "gridPos": { "y": 41, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Modify", "type": "row", "gridPos": { "y": 49, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Inserted",
   "type": "graph",
   "gridPos": { "y": 50, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "graph",
   "gridPos": { "y": 50, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "graph",
   "gridPos": { "y": 58, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated Ratio",
   "type": "graph",
   "gridPos": { "y": 58, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Modified",
   "type": "graph",
   "gridPos": { "y": 66, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_mod{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated",
   "type": "graph",
   "gridPos": { "y": 66, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Tuple", "type": "row", "gridPos": { "y": 74, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Live Tuple",
   "type": "graph",
   "gridPos": { "y": 75, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple",
   "type": "graph",
   "gridPos": { "y": 75, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live Tuple Delta",
   "type": "graph",
   "gridPos": { "y": 83, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple Delta",
   "type": "graph",
   "gridPos": { "y": 83, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Index Access", "type": "row", "gridPos": { "y": 91, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Index Access",
   "type": "graph",
   "gridPos": { "y": 92, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Blocks Hit Ratio",
   "type": "graph",
   "gridPos": { "y": 92, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]) / (rate(pg_index_idx_blks_read{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read",
   "type": "graph",
   "gridPos": { "y": 100, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched",
   "type": "graph",
   "gridPos": { "y": 100, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read per Scan",
   "type": "graph",
   "gridPos": { "y": 108, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched per Scan",
   "type": "graph",
   "gridPos": { "y": 108, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])  / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Functions", "type": "row", "gridPos": { "y": 116, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Function Call",
   "type": "graph",
   "gridPos": { "y": 117, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Time Spend",
   "type": "graph",
   "gridPos": { "y": 117, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration (Self Time)",
   "type": "graph",
   "gridPos": { "y": 125, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_func_self_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration",
   "type": "graph",
   "gridPos": { "y": 125, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "y": 133, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacuum (1m)",
     "type": "graph",
     "gridPos": { "y": 134, "h": 8, "w": 24, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_table_vacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autovacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Analyze (1m)",
     "type": "graph",
     "gridPos": { "y": 142, "h": 8, "w": 24, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_table_analyze_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autoanalyze_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    }
   ]
  }
 ]
}