{
 "title": "PG Table Catalog",
 "description": "Single table detail in PG Database",
 "tags": [
  "PG",
  "Catalog",
  "Database",
  "Table"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": "postgres" },
   {
    "name": "relname",
    "label": "Relation",
    "query": "SELECT relname FROM pg_namespace nsp JOIN pg_class rel ON nsp.oid = rel.relnamespace\nWHERE nspname NOT IN ('pg_catalog', 'monitor', 'information_schema') AND relkind = 'r';"
   },
   { "name": "datname", "label": "Instance", "query": "SELECT current_database();" }
  ]
 },
 "panels": [
  { "title": "Catalog", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Namespace / Schema",
   "type": "stat",
   "gridPos": { "y": 1, "h": 3, "w": 6, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT relnamespace::RegNamespace FROM pg_class WHERE relname = '$relname';"
    }
   ]
  },
  {
   "title": "Relation",
   "type": "stat",
   "gridPos": { "y": 1, "h": 3, "w": 12, "x": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "rawSql": "SELECT '$relname'" }
   ]
  },
  {
   "title": "Relation Kind",
   "type": "stat",
   "gridPos": { "y": 1, "h": 3, "w": 6, "x": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT relkind FROM pg_class WHERE relname = '$relname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "y": 4, "h": 4, "w": 24, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n         SELECT relpages ::BIGINT,\n                (relpages * 8192::REAL)    AS relsize,\n                reltuples ::REAL,\n                age(relfrozenxid) ::BIGINT AS age\n         FROM pg_class c\n         WHERE relname = '${relname}'\n         LIMIT 1) a,\n     (\n         SELECT n_live_tup AS live_tup,\n                n_dead_tup AS dead_tup,\n                CASE WHEN (n_live_tup + n_dead_tup) > 0 THEN n_dead_tup::NUMERIC / (n_live_tup + n_dead_tup) ELSE 0 END AS dead_ratio\n         FROM pg_stat_user_tables\n         WHERE relname = '$relname' LIMIT 1\n     ) b;"
    },
    {
     "rawSql": "SELECT ratio AS \"Bloat Ratio\" FROM monitor.pg_table_bloat WHERE relname = '$relname'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 8, "h": 10, "w": 6, "x": 0 },
   "targets": [
    {
     "rawSql": "SELECT  oid             ,\n        relnamespace    ,\n        reltype         ,\n        reloftype       ,\n        relowner        ,\n        relam           ,\n        relfilenode     ,\n        reltablespace   ,\n        reltoastrelid   \nFROM pg_class c\nWHERE relname = '${relname}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 8, "h": 10, "w": 6, "x": 6 },
   "targets": [
    {
     "rawSql": "SELECT relhasindex     :: INTEGER,\n   relispartition      :: INTEGER,\n   relisshared         :: INTEGER,\n   relhasrules         :: INTEGER,\n   relhastriggers      :: INTEGER,\n   relhassubclass      :: INTEGER,\n   relrowsecurity      :: INTEGER,\n   relforcerowsecurity :: INTEGER,\n   relispopulated      :: INTEGER\nFROM pg_class c\nWHERE relname = '${relname}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 8, "h": 10, "w": 6, "x": 12 },
   "targets": [
    {
     "rawSql": "SELECT relpages ::BIGINT,\n       (relpages * 8192::REAL) AS relsize,  \n       reltuples ::REAL,\n       relallvisible ::BIGINT,\n       relnatts ::BIGINT,\n       relchecks ::BIGINT,\n       relfrozenxid,\n       age(relfrozenxid) ::BIGINT AS age,\n       relminmxid\nFROM pg_class c\nWHERE relname = '${relname}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 8, "h": 3, "w": 6, "x": 18 },
   "targets": [
    {
     "rawSql": "SELECT \n   CASE relpersistence WHEN 'u' THEN 1 ELSE 0 END AS relunlogged,\n   CASE relpersistence WHEN 't' THEN 1 ELSE 0 END AS reltemporary\nFROM pg_class c\nWHERE relname = '${relname}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 11, "h": 5, "w": 6, "x": 18 },
   "targets": [
    {
     "rawSql": "SELECT unnest(relacl) AS acl\nFROM pg_class c\nWHERE relname = '${relname}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 16, "h": 2, "w": 6, "x": 18 },
   "targets": [
    {
     "rawSql": "SELECT unnest(reloptions) AS opt\nFROM pg_class c\nWHERE relname = '${relname}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 18, "h": 9, "w": 6, "x": 0 },
   "targets": [
    {
     "rawSql": "SELECT seq_scan,\n       seq_tup_read,\n       idx_scan,\n       idx_tup_fetch,\n       n_tup_ins,\n       n_tup_upd,\n       n_tup_del,\n       n_tup_hot_upd\nFROM pg_stat_user_tables\nWHERE relname = '$relname' LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 18, "h": 9, "w": 6, "x": 6 },
   "targets": [
    {
     "rawSql": "SELECT vacuum_count + autovacuum_count                   AS vacuum_total,\n       vacuum_count,\n       to_char(last_vacuum, 'YYYY-MM-DD HH24:MI:SS')     AS last_vacuum,\n       date_trunc('second', now() - last_vacuum)         AS since_last_vacuum,\n       autovacuum_count,\n       to_char(last_autovacuum, 'YYYY-MM-DD HH24:MI:SS') AS last_autovacuum,\n       date_trunc('second', now() - last_autovacuum)     AS since_last_autovacuum,\n       n_ins_since_vacuum\nFROM pg_stat_user_tables\nWHERE relname = '$relname'\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 18, "h": 9, "w": 6, "x": 12 },
   "targets": [
    {
     "rawSql": "SELECT analyze_count + autoanalyze_count                   AS analyze_total,\n       analyze_count,\n       to_char(last_analyze, 'YYYY-MM-DD HH24:MI:SS')     AS last_analyze,\n       date_trunc('second', now() - last_analyze)         AS since_last_analyze,\n       autoanalyze_count,\n       to_char(last_autoanalyze, 'YYYY-MM-DD HH24:MI:SS') AS last_autoanalyze,\n       date_trunc('second', now() - last_autoanalyze)     AS since_last_autoanalyze,\n       n_mod_since_analyze\nFROM pg_stat_user_tables\nWHERE relname = '$relname'\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 18, "h": 9, "w": 6, "x": 18 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_statio_user_tables WHERE relname = '$relname'"
    }
   ]
  },
  {
   "title": "Attributes",
   "type": "table",
   "gridPos": { "y": 27, "h": 8, "w": 24, "x": 0 },
   "targets": [
    {
     "rawSql": "SELECT s.attname,\n       a.attnum,\n       a.attstorage,\n       a.attalign,\n       attnotnull,\n       s.null_frac,\n       s.avg_width,\n       s.n_distinct,\n       s.correlation\nFROM pg_attribute a LEFT JOIN pg_stats s  \nON s.attname = a.attname \nWHERE tablename = '$relname' AND a.attrelid IN (SELECT oid FROM pg_class WHERE relname = '$relname')\nORDER BY attnum;\n"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "table",
   "gridPos": { "y": 35, "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_user_indexes WHERE relname = '${relname}';"
    }
   ]
  },
  {
   "title": "Relation Size",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "y": 40, "h": 7, "w": 24, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT relname, pg_table_size(oid) AS size FROM pg_class WHERE relname ~ '$relname';"
    }
   ]
  }
 ]
}