{
 "title": "PGSQL Tables",
 "description": "PGSQL Tables overview of single database",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:status{ins=\"$ins\"}"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_table_size_bytes{ins=\"$ins\", datname=\"$datname\", relkind!='i'}) by (relname) ",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Scan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Index Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Scanned Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan -- Scanned Tuples",
   "type": "timeseries",
   "description": "Rate of tuples been sequential scanned",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Rows per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Total Scanned  Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Modify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Modified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_mod{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Tuple", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Live Tuple",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live Tuple Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Index Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Index Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Blocks Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]) / (rate(pg_index_idx_blks_read{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]))",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])  / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  { "title": "Functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Function Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Time Spend (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration (Self Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_func_self_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Vacuum (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_vacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autovacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Analyze (1m)",
   "type": "timeseries",
   "description": "How many analyze (auto + manual) executed in last 1m on each table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_analyze_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autoanalyze_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  }
 ]
}