{
 "title": "PGSQL Table",
 "description": "PostgreSQL Single Table Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Database",
  "Table"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "relname",
    "label": "Table",
    "query": {
     "query": "label_values(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}, relname)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relation",
   "type": "stat",
   "description": "Relation name (fully qualified with schema name)",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Relation identifier for ${relname}",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_table_relid{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:status{ins=\"$ins\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_class_relnatts{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Columns"
    },
    {
     "expr": "pg_class_reltuples{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Rows"
    },
    {
     "expr": "pg_class_relsize{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "pg_class_relage{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Age"
    },
    {
     "expr": "rate(pg_table_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Row Read"
    },
    {
     "expr": "rate(pg_table_n_tup_mod{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Row Mod"
    },
    {
     "expr": "pg:table:scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Scan"
    },
    {
     "expr": "rate(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "Seq Scan"
    },
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "Idx Scan"
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Scan & Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Table Scan Rate",
   "type": "timeseries",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Sequential"
    }
   ]
  },
  {
   "title": "Row Scan Rate",
   "type": "timeseries",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Sequential"
    }
   ]
  },
  {
   "title": "Index Scan Rate",
   "type": "timeseries",
   "description": "Index scan rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Sequential Scan Rate",
   "type": "timeseries",
   "description": "Sequential scan rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  { "title": "Modification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Rows Modified (5m)",
   "type": "timeseries",
   "description": "Tuple Modification (insert|delete|update) in last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "INSERT"
    },
    {
     "expr": "increase(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "increase(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "UPDATE"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "HOT Updates",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "HOT Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "HOT Rate"
    }
   ]
  },
  { "title": "Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Index Scan Rate",
   "type": "timeseries",
   "description": "Index scan rate of last 1 minute on this table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_index_idx_blks_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Tuple Returned",
   "type": "timeseries",
   "description": "Rate of index tuples been read",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Tuple Fetched",
   "type": "timeseries",
   "description": "Rate of live table rows fetched by simple index scans using this index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Tuple Returned Per Scan",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Tuple Fetched Per Scan",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  { "title": "Sequences", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Sequence Values",
   "type": "stat",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_seq_last_value{ins=\"$ins\", datname=\"$datname\", seqname=~\"$relname.*\"}",
     "legendFormat": "{{ seqname }}  @"
    }
   ]
  },
  {
   "title": "Sequence Allocation (1m)",
   "type": "timeseries",
   "description": "Index scan tuples/s of last 1 minute",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_seq_last_value{ins=\"$ins\", datname=\"$datname\", seqname=~\"$relname.*\"}[1m])",
     "legendFormat": "{{ seqname }}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Function Call",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Time Spend (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration (Self Time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_self_time{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    }
   ]
  },
  { "title": "Blocks I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Table Heap Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_heap_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_heap_blks_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_heap_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_idx_blks_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_idx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Toast Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_toast_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_toast_blks_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_toast_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Toast Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_tidx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_tidx_blks_read{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_tidx_blks_hit{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Vacuum & Analyze", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Maintenance Activity",
   "type": "state-timeline",
   "description": "Vacuum and analyze activity on this table (manual or auto)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "increase(pg_table_vacuum_count{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Vacuum"
    },
    {
     "expr": "increase(pg_table_autovacuum_count{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Auto Vacuum"
    },
    {
     "expr": "increase(pg_table_analyze_count{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Analyze"
    },
    {
     "expr": "increase(pg_table_autoanalyze_count{ins=\"$ins\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Auto Analyze"
    }
   ]
  }
 ]
}