{
 "title": "PGSQL Shard",
 "description": "PostgreSQL Monitoring Home Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "Shard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": { "query": "label_values(pg_up, job)" } },
   {
    "name": "shard",
    "label": "Shard",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cls) (pg_up{job=\"$job\", cls=~\"$shard.*\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(pg_up{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{job=\"$job\", cls=~\"$shard.*\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(node_load1{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "count(max by (cls,datname) (pg_db_age{job=\"$job\", cls=~\"$shard.*\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(node:cls:cpu_count{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:fs:size_bytes{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(max by (cls,datname)(pg_size_bytes{datname!~\"log|wal\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node:cls:cpu_usage{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:num_backends{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:xact_commit_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:xact_rollback_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:cls:query_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:lsn_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "WAL Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Space Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_db_age{cls=~\"$shard.*\"}) / 2147483648",
     "legendFormat": "Age Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_repl_replay_diff{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:ixact_backends{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "iXact Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:conn_usage{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Conn Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer:cls:waiting_clients{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cls:pressure1{job=\"$job\", cls=~\"$shard.*\", cls=~\"$shard.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 20, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "pg:ins:status{job=\"$job\",cls=~\"$shard.*\"}"
    },
    {
     "expr": "ins:pressure1{job=\"$job\",cls=~\"$shard.*\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Cluster Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage_1m{cls=~\"$shard.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instance CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage_1m{cls=~\"$shard.*\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Cluster Pressure 5min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cls:pressure5{job=\"$job\", cls=~\"$shard.*\"} != -1",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instance Pressure 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ins:pressure1{job=\"$job\", cls=~\"$shard.*\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate5m{cls=~\"$shard.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instance QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate5m{cls=~\"$shard.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (cls) (pg_activity_count{cls=~\"$shard.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Instance Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=~\"$shard.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Average transaction response time from pgbouncer\n(You can get from postgres directly after PG14)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rt_1m{cls=~\"$shard.*\"}\n# pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"} # PG14",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (cls) (pg_repl_replay_diff{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  }
 ]
}