{
 "title": "PGSQL Queries",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$ins\"}",
     "legendFormat": "QPS"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$ins\"} OFFSET 1d",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$ins\"} OFFSET 2d",
     "legendFormat": "2 Day Ago"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"} / pgbouncer:ins:xact_rate1m{ins=\"$ins\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Long Run Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_duration{ins=\"$ins\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Average Queries per Commit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"} / on(ins) group_left() pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Table Scan 'QPS'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rate15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS Divergence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[5m]) / stddev_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[5m])) ^ 2",
     "legendFormat": "QPS Divergence"
    }
   ]
  },
  {
   "title": "RT Divergence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[5m]) / stddev_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[5m])) ^ 2",
     "legendFormat": "RT Divergence"
    }
   ]
  },
  {
   "title": "QPS Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m]) + 3 * stddev_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m]) - 3 * stddev_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m]) + stddev_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m]) - stddev_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m]) + 3 * stddev_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m]) - 3 * stddev_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m]) ",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m]) + stddev_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m]) - stddev_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:query_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$ins\"}",
     "legendFormat": "v"
    }
   ]
  },
  {
   "title": "QPS by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:query_rate5m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Query RT by Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Statementes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (datname, query) (pg_query_calls{ins=\"$ins\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Exec Time Spent (1h)",
   "type": "piechart",
   "description": "Time spent on executing statements  during last 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Call 1h",
   "type": "piechart",
   "description": "number of statement call in last 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_calls{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT Ranking",
   "type": "barchart",
   "description": "Rank of last 1m RT",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(32, increase(pg_query_exec_time{ins=\"$ins\"}[1h]) / increase(pg_query_calls{ins=\"$ins\"}[1h]))",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spent rate1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}