{
 "title": "PGSQL Alert",
 "description": "PostgreSQL Alerts",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "Alert"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Alert: Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Alert: Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 0, "y": 20 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 18, "w": 18, "x": 6, "y": 20 } },
  {
   "title": "INFRA: Aliveness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "InfraDown",
     "type": "timeseries",
     "description": "Infrastructure Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "infra:ins:up{job=\"infra\"}",
       "legendFormat": "{{ type }}@{{ instance }}"
      }
     ]
    },
    {
     "title": "AgentDown",
     "type": "timeseries",
     "description": "Agent Aliveness (node_exporter, pg_exporter, pgbouncer_exporter, haproxy_exporter)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "up{job!=\"infra\"}",
       "legendFormat": "{{ ins }}@{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeCpuHigh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:cpu_usage_1m", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE: Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeLoadHigh",
     "type": "timeseries",
     "description": "Standard Load (divide by cpu count) > 100%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:stdload1", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE: Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeOutOfMem",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:mem_avail", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE: Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeMemSwapped",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:swap_usage", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE : Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeDiskSlow",
     "type": "timeseries",
     "description": "Disk read/write avg latency > 32ms",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (ins,device) (node:dev:disk_write_rt_1m > node:dev:disk_read_rt_1m or node:dev:disk_read_rt_1m)",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE : Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeFsFull",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:space_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsExhaust",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "node:fs:space_exhaust{}", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsFilesFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:inode_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFdFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:fd_usage", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "Node: Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeTcpErrHigh",
     "type": "timeseries",
     "description": "TCP Error Rate > 1 / s",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      { "expr": "rate(node:ins:tcp_error[1m])", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "NodeTcpRetransHigh",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      { "expr": "node:ins:tcp_retrans_ratio1m", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE : NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeNtpSanity",
     "type": "timeseries",
     "description": "Check ntp protocol / clock sanity",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min without() (node_ntp_sanity or node_timex_sync_status)",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "NodeClockSkew",
     "type": "timeseries",
     "description": "Clock time offset alert > 50ms",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "abs(node_timex_offset_seconds)", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "PGSQL: Aliveness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresDown",
     "type": "timeseries",
     "description": "Postgres Database Service Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PgbouncerDown",
     "type": "timeseries",
     "description": "Pgbouncer Connection Pooler Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresPartition",
     "type": "timeseries",
     "description": "Number of leader of a postgres partition",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "pg:cls:partition", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "PostgresReplicationBreak",
     "type": "timeseries",
     "description": "Number of replication streaming slave change",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(pg_downstream_count{state=\"streaming\"}[5m])",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "PostgresReplicationLag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "pg:ins:lag_bytes", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PostgresReplicationLagSeconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "pg:ins:lag_seconds", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresWalRateHigh",
     "type": "timeseries",
     "description": "Transaction Rollback",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "pg:cls:lsn_rate1m", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "PostgresPressureHigh",
     "type": "timeseries",
     "description": "Postgres & Pgbouncer load index: Active Time / Available Time",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "ins:pressure1", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PgbouncerQuerySlow",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "pgbouncer:db:query_rt_1m", "legendFormat": "{{ ins }}:{{ datname }}" }
     ]
    },
    {
     "title": "PostgresTpsHigh",
     "type": "timeseries",
     "description": "Transactions in database",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:xact_total_rate1m{datname!~\"postgres|template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    },
    {
     "title": "PostgresRollbackHigh",
     "type": "timeseries",
     "description": "Transaction Rollback",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:xact_rollback_rate1m{datname!~\"postgres|template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "PgbouncerClientQueue",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "pgbouncer:db:waiting_clients", "legendFormat": "{{ ins }}:{{ datname }}" }
     ]
    },
    {
     "title": "PostgresConnUsageHigh",
     "type": "timeseries",
     "description": "Database connection Usage",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg:db:conn_usage{datname!~\"postgres|template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    },
    {
     "title": "PostgresBackendNumHigh",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "pg:db:num_backends", "legendFormat": "{{ ins }}:{{ datname }}" }
     ]
    },
    {
     "title": "PostgresIdleInXact",
     "type": "timeseries",
     "description": "Idle in Transaction\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:ixact_backends{datname!~\"postgres|template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresXidWarpAround",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (ins, datname) (pg:db:age{datname!~\"postgres|template0|template1\"})",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  }
 ]
}