{
 "title": "ETCD Overview",
 "description": "ETCD Service Overview",
 "tags": [
  "Pigsty",
  "ETCD",
  "Overview",
  "HOME",
  "INFRA"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ETCD Has Leader",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)", "legendFormat": "Has Leader" },
    { "expr": "sum(etcd_server_has_leader)", "legendFormat": "Members" }
   ]
  },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "etcd_server_is_leader", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"etcd\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "Rate Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total",
     "legendFormat": "{{instance}} Leader Change Seen"
    }
   ]
  },
  {
   "title": "Network RT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[2m]))",
     "legendFormat": "{{ ins }} -> {{ To }}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket [5m])) by (ins, le))",
     "legendFormat": "{{ ins }} WAL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket [5m])) by (ins, le))",
     "legendFormat": "{{ ins }} DB"
    }
   ]
  },
  {
   "title": "Proposal Committed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proposal Applied",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total[1m])\n",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total [1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_peer_received_bytes_total [1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total [1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_client_grpc_received_bytes_total [1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  {
   "title": "DB Size: db / quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes / etcd_server_quota_backend_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  }
 ]
}