{
 "title": "PGSQL Service",
 "description": "Postgres Service",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster",
  "Service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "svc",
    "label": "Service",
    "query": {
     "query": "label_values(haproxy_server_check_status, proxy)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(haproxy_server_check_status{proxy='$svc'}, cls)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(haproxy_server_check_status{proxy='$svc'}, proxy)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service",
   "type": "stat",
   "description": "Service = ${svc}. Which is unique identifier of service",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "Service among cluster. Number of routes from proxy to server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    },
    {
     "expr": "sum by (proxy) (haproxy_server_status{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "All haproxy instances in this cluster ${cls}",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "sum by (ins) (haproxy_server_status{cls=\"$cls\", proxy=\"$svc\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "All postgres instance among this cluster",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (server)(haproxy_server_status{proxy=~\"$svc\"})",
     "legendFormat": "Route"
    },
    {
     "expr": "max by (server) (haproxy_server_weight{proxy=~\"$svc\"})"
    },
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{proxy=~\"$svc\"})"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Role is service identifier among cluster. e.g primary, replica, standby, offline, delayed, etc....",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Proxy",
   "type": "stat",
   "description": "Number of haproxy instance among this cluster that provide service for ${svc}",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(haproxy_server_check_status{cls=\"$cls\", proxy=\"$svc\"}) by (ins))",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "description": "Number of postgres instance among this cluster that provide service ${svc}",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count(haproxy_server_check_status{cls=\"$cls\", proxy=\"$svc\"}) by (ins))",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Healthy Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_status{proxy=\"$svc\"} > 0",
     "legendFormat": "{{ ins }} ➡️ {{ server }}"
    }
   ]
  },
  {
   "title": "Proxy ➔ Server Sessions",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"}) > 0",
     "legendFormat": "{{ ins }} ➔ {{ server }}"
    }
   ]
  },
  {
   "title": "Proxy Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - haproxy_process_idle_time_percent{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proxy Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_frontend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Server Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ins:pressure1{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Server Sessions",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Traffic by Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (rate(haproxy_frontend_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[1m]) + rate(haproxy_frontend_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Traffic by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(haproxy_server_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[1m]) + rate(haproxy_server_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}