#!/usr/bin/ansible-playbook
---
#--------------------------------------------------------------#
# patroni restart affected replica nodes at replica individually
#--------------------------------------------------------------#

- name: patroni restart {{ pg_cluster }} at replica individually
  tags: [ pg_hugepage, patroni, pg_launch, pt_restart ]
  become_user: "{{ dbsu }}"
  when: patroni_mode != 'remove' and pg_role != 'primary'
  block:
    - name: retrieve current patroni replica member of {{ pg_cluster }}
      command: /pg/bin/pg-member
      register: pg_member_name_cmd

    - name: set variable curr_pg_member_name
      set_fact:
        curr_pg_member_name: "{{ pg_member_name_cmd.stdout | default('') | trim }}"
      changed_when: false

    - name: restart patroni replica member of {{ pg_cluster }}
      when: curr_pg_member_name is defined and curr_pg_member_name|length>0
      command: /usr/bin/patronictl -c /pg/bin/patroni.yml restart --force {{ pg_cluster }} {{ curr_pg_member_name }}
      register: patroni_restart_cmd

    - name: print result if failed at replica
      when:
        - patroni_restart_cmd is defined
        - patroni_restart_cmd.rc is defined
        - patroni_restart_cmd.rc != 0
      debug:
        msg: |
          rc: {{ patroni_restart_cmd.rc }},
            stdout: {{ patroni_restart_cmd.stdout }},
            stderr: {{ patroni_restart_cmd.stderr }}
      changed_when: false

...
