---
#--------------------------------------------------------------#
# Write hugepage sysctl parameter if needed
#--------------------------------------------------------------#

- name: write hugepage sysctl parameter if needed
  become: yes
  when: new_nr_hugepages is defined
  block:
    - name: write hugepage sysctl parameter
      vars:
        txt: |
          vm.nr_hugepages = {{ new_nr_hugepages }}
      copy:
        dest: /etc/sysctl.d/hugepage.conf
        # write txt first line to /etc/sysctl.d/hugepage.conf
        content: |
          {{ txt.split('\n')[0] }}

    - name: activate tuned profile, prepare for database performance impact!
      args: { executable: /bin/bash }
      shell: |
        sync; echo 3 > /proc/sys/vm/drop_caches   # 刷盘，释放系统缓存（请做好数据库性能受到冲击的准备）
        sysctl -p /etc/sysctl.d/hugepage.conf
      ignore_errors: true

    - name: print new_nr_hugepages after write
      become: yes
      args: { executable: /bin/bash }
      shell: |
        cat /proc/meminfo | grep HugePages_
        sysctl -a | grep vm.nr_hugepages
      ignore_errors: true
      changed_when: false
      register: hugepage_after_write_cmd

    - name: print hugepage_after_write_cmd
      when: hugepage_after_write_cmd is defined
      debug:
        msg: |
          rc: {{ hugepage_after_write_cmd.rc }}
            STDOUT: {{ hugepage_after_write_cmd.stdout }}
            STDERR: {{ hugepage_after_write_cmd.stderr }}
      ignore_errors: true
      changed_when: false

...
