---
#--------------------------------------------------------------#
# HONOR PG_SAFEGUARD                              [pg_safeguard]
#--------------------------------------------------------------#
- name: ABORT due to pg_safeguard enabled
  connection: local
  when: pg_safeguard|bool
  tags: [ always , pg_safeguard ]
  any_errors_fatal: true
  ignore_errors: false
  fail: msg="Abort due to pg_safeguard for {{ pg_cluster }}-{{ pg_seq }} @ {{ inventory_hostname }} is enabled, override with -e pg_safeguard=false"


#--------------------------------------------------------------#
# remove exporter targets from prometheus           [prometheus]
#--------------------------------------------------------------#
- import_tasks: prometheus.yml
  when: prometheus_enabled|bool
  tags: [ prometheus , register ]


#--------------------------------------------------------------#
# remove pgsql datasource from grafana                 [grafana]
#--------------------------------------------------------------#
- import_tasks: grafana.yml
  when: grafana_enabled|bool
  tags: [ grafana , register ]


#--------------------------------------------------------------#
# remove pg dns records                                    [dns]
#--------------------------------------------------------------#
- import_tasks: dns.yml
  tags: dns


#--------------------------------------------------------------#
# remove pg vip manager                                    [vip]
#--------------------------------------------------------------#
- import_tasks: vip.yml
  tags: vip


#--------------------------------------------------------------#
# remove service                                    [pg_service]
#--------------------------------------------------------------#
- import_tasks: pg_service.yml
  tags: [ haproxy, pg_service ]


#--------------------------------------------------------------#
# remove monitor                                   [pg_exporter]
#--------------------------------------------------------------#
# pg_exporter, pgbouncer_exporter
- import_tasks: pg_exporter.yml
  tags: pg_exporter


#--------------------------------------------------------------#
# remove pgbouncer                                   [pgbouncer]
#--------------------------------------------------------------#
- import_tasks: pgbouncer.yml
  tags: pgbouncer


#--------------------------------------------------------------#
# remove postgres                                     [postgres]
#--------------------------------------------------------------#
# pg_replica, pg_primary, pg_meta
- import_tasks: postgres.yml
  tags: postgres


#--------------------------------------------------------------#
# remove backup                                     [pgbackrest]
#--------------------------------------------------------------#
- import_tasks: pgbackrest.yml
  tags: pgbackrest


#--------------------------------------------------------------#
# remove data                                          [pg_data]
#--------------------------------------------------------------#
- name: remove postgres data
  tags: pg_data
  when: pg_clean|bool
  ignore_errors: yes
  file: path={{ item }} state=absent
  with_items:
    - /pg/data
    - "{{ pg_fs_main }}/postgres"

- name: remove pg_fs_wal/?/pg_wal (if pg_fs_wal defined)
  tags: pg_data
  when: pg_clean|bool and (pg_fs_wal | length > 0)
  ignore_errors: yes
  file: path={{ item }} state=absent
  with_items:
    - "{{ pg_fs_wal }}/{{ pg_cluster }}-{{ pg_version }}"

#--------------------------------------------------------------#
# remove packages                                       [pg_pkg]
#--------------------------------------------------------------#
# pigsty will NOT uninstall postgres packages unless explicitly specified
# example: ./pgsql-rm.yml -l <cls> -t pg_pkg -e pg_uninstall=true
# to uninstall pg_extensions only:
# ./pgsql-rm.yml -t pg_extension -e pg_uninstall=true

- name: remove postgres packages
  tags: pg_pkg
  when: pg_uninstall|bool
  ignore_errors: yes
  block:

    # remove pg path & alias
    - name: remove postgres environ
      file: path={{ item }} state=absent
      with_items:
        - /etc/profile.d/pgsql.sh
        - /etc/profile.d/pg-alias.sh

    - name: lookup pg packages & extensions names
      become: no
      connection: local
      tags: pg_extension
      set_fact:
        pg_packages_list: |-
          {% set pkg_map = package_map | default({}) %}
          {% for pkg_list in pg_packages %}{% for pkg in pkg_list | trim | regex_replace('(,|\\s)+', ',') | regex_findall('([^,\\s]+)') | default([]) %}{% if pkg != '' %}{% if pkg in pkg_map %}{% set pkg = pkg_map[pkg] %}{% endif %}{% if not loop.first %},{% endif %}{{ pkg|replace('${pg_version}', pg_version|string)|replace('$v', pg_version|string) }}{% endif %}{% endfor %}

          {% endfor %}
        pg_extension_list: |-
          {% set pkg_map = package_map | default({}) %}
          {% for ext_list in pg_extensions %}{% for ext in ext_list | trim | regex_replace('(,|\\s)+', ',') | regex_findall('([^,\\s]+)') | default([]) %}{% if ext != '' %}{% if ext in pkg_map %}{% set ext = pkg_map[ext] %}{% endif %}{% if not loop.first %},{% endif %}{{ ext|replace('${pg_version}', pg_version|string)|replace('$v', pg_version|string) }}{% endif %}{% endfor %}

          {% endfor %}

    # uninstall extensions first
    - name: uninstall pg extensions
      tags: pg_extension
      package: name={{ item }} state=absent
      with_items: "{{ pg_extension_list | trim | regex_findall('([^\\n]+)') | map('replace', '$v', pg_version|string) | list | map('replace', '${pg_version}', pg_version|string) | map('regex_replace', '(,|\\s)+', ',' ) | list }}"

    - name: uninstall pg packages
      package: name={{ item }} state=absent
      with_items: "{{ pg_packages_list | trim | regex_findall('[^\\n]+') | map('replace', '$v', pg_version|string) | list | map('replace', '${pg_version}', pg_version|string) | map('regex_replace', '(,|\\s)+', ',' ) | list }}"

...