---
#--------------------------------------------------------------#
# Remove VIP-Manager                                       [vip]
#--------------------------------------------------------------#
# TODO: if you have external vip service provider, remove it here
- name: stop and disable vip-manager
  tags: vip
  become: yes
  ignore_errors: yes
  block:

    - name: stop and disable vip-manager service
      systemd: name=vip-manager state=stopped enabled=no daemon_reload=yes

    - name: remove vip-manager config file
      file: name=/etc/default/vip-manager.yml state=absent
...