{
 "title": "Redis Overview",
 "description": "Redis Overview Dashboard",
 "tags": [
  "Pigsty",
  "REDIS",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": { "query": "label_values(redis_up, job)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cls) (redis_up{job=\"$job\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(count by (ip) (label_replace(redis_up{job=\"$job\"}, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\")))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(redis_up{job=\"$job\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(redis_instance_info{job=\"$job\", role=\"master\"})",
     "legendFormat": "Primary"
    },
    {
     "expr": "count(redis_instance_info{job=\"$job\", role=\"slave\"})",
     "legendFormat": "Replica"
    },
    {
     "expr": "count(node_load1{job=\"$job\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "count((count by (db) (redis_db_keys{})))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(node:cls:cpu_count{job=\"$job\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(max by (ip) (label_replace(redis_total_system_memory_bytes, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\")))",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(redis_memory_max_bytes{job=\"$job\"})",
     "legendFormat": "Mem Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:cls:cpu_usage{job=\"$job\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "redis_instance_info{job=\"$job\"}"
    },
    {
     "expr": "redis:ins:cpu_usage{job=\"$job\"}"
    },
    {
     "expr": "redis:ins:mem_usage{job=\"$job\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", job=\"$job\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=\"$job\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:cls:cpu_usage{job=\"$job\"} != -1",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(redis:ins:cpu_usage{job=\"$job\"}[3m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "redis:cls:cpu_usage", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "CPU Usage (Child)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "redis:cls:cpu_usage_child", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "redis:cls:tx{}", "legendFormat": "▲{{ cls }}" },
      { "expr": "- redis:cls:rx{}", "legendFormat": "▼{{ cls }}" }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "redis:cls:mem_usage", "legendFormat": "{{ cls }}" }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis:env:qps", "legendFormat": "QPS" },
      { "expr": "redis:env:qps_mu", "legendFormat": "µ" },
      {
       "expr": "redis:env:qps_mu + redis:env:qps_sigma",
       "legendFormat": "+σ"
      },
      {
       "expr": "redis:env:qps_mu - redis:env:qps_sigma",
       "legendFormat": "-σ"
      },
      {
       "expr": "redis:env:qps_mu + 3 * redis:env:qps_sigma",
       "legendFormat": "+3σ"
      },
      {
       "expr": "redis:env:qps_mu - 3 * redis:env:qps_sigma",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Overall Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis:env:rt", "legendFormat": "QPS" },
      { "expr": "redis:env:rt_mu", "legendFormat": "µ" },
      {
       "expr": "redis:env:rt_mu + redis:env:rt_sigma",
       "legendFormat": "+σ"
      },
      {
       "expr": "redis:env:rt_mu - redis:env:rt_sigma",
       "legendFormat": "-σ"
      },
      {
       "expr": "redis:env:rt_mu + 3 * redis:env:rt_sigma",
       "legendFormat": "+3σ"
      },
      {
       "expr": "redis:env:rt_mu - 3 * redis:env:rt_sigma",
       "legendFormat": "-3σ"
      }
     ]
    },
    {
     "title": "Cluster QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:cls:qps", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Cluster QPS (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:cls:qps", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Cluster RT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis:cls:rt", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Cluster Time (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (cls) (redis:cls:cmd_time)",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Command QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:env:cmd_qps", "legendFormat": "{{ cmd }}" }
     ]
    },
    {
     "title": "Command QPS (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:env:cmd_qps", "legendFormat": "{{ cmd }}" }
     ]
    },
    {
     "title": "Command RT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis:env:cmd_rt", "legendFormat": "{{ cmd }}" }
     ]
    },
    {
     "title": "Command Time (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis:env:cmd_time", "legendFormat": "{{ cmd }}" }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clients",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis:cls:clients", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Connected Replicas",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sum by (cls) (redis_connected_slaves{})",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Received Conn Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis:cls:conn_rate", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Incoming Connection 1 Day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "topk(100, sum by (cls)(increase(redis_connections_received_total{}[1d])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Reject Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis:cls:conn_reject", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Blocked Client Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis:cls:blocked_clients", "legendFormat": "{{ cls }}" }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Expired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:cls:key_expire{}", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Keys (per DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum (redis_db_keys{}) by (db)", "legendFormat": "{{ db }} " }
     ]
    },
    {
     "title": "Key Evicted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis:cls:key_evict{}", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "Keys (per Cluster)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum by (cls) (redis_db_keys{})", "legendFormat": "{{ cls }} " }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (cls) (redis_db_avg_ttl_seconds{})",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Key Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "redis:cls:key_hit_rate{}", "legendFormat": "{{ cls }}" }
     ]
    }
   ]
  },
  {
   "title": "Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "LSN Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cls) (redis:ins:lsn_rate{})",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Latest Fork Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis:cls:fork_time", "legendFormat": "{{ cls }}" }
     ]
    }
   ]
  }
 ]
}