{
 "title": "PGSQL Alert",
 "description": "PostgreSQL Alerts",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "Alert"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}⚡️] {{alertname}}  @ {{ cls }}"
    },
    {
     "expr": "ALERTS{alertstate=\"pending\"}",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ cls }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 0, "y": 8 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 18, "w": 18, "x": 6, "y": 8 } },
  { "title": "INFRA: Aliveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "InfraDown",
   "type": "timeseries",
   "description": "Infrastructure Aliveness (Including Node & Haproxy)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "infra:ins:up{job=\"infra\"}",
     "legendFormat": "{{ type }}@{{ instance }}"
    }
   ]
  },
  {
   "title": "AgentDown",
   "type": "timeseries",
   "description": "Agent Aliveness (node_exporter, pg_exporter, pgbouncer_exporter, haproxy_exporter)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "up{job!=\"infra\"}",
     "legendFormat": "{{ ins }}@{{ instance }}"
    }
   ]
  },
  { "title": "NODE : CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "NodeCpuHigh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:cpu_usage_1m", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "NODE: Schedule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "NodeLoadHigh",
   "type": "timeseries",
   "description": "Standard Load (divide by cpu count) > 100%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:stdload1", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "NODE: Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "NodeOutOfMem",
   "type": "timeseries",
   "description": "Available memory < 10%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:mem_avail", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "NODE: Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "NodeMemSwapped",
   "type": "timeseries",
   "description": "Available memory < 10%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:swap_usage", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "NODE : Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "NodeDiskSlow",
   "type": "timeseries",
   "description": "Disk read/write avg latency > 32ms",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (ins,device) (node:dev:disk_write_rt_1m > node:dev:disk_read_rt_1m or node:dev:disk_read_rt_1m)",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "NODE : Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "NodeFsFull",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:fs:space_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
   ]
  },
  {
   "title": "NodeFsExhaust",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node:fs:space_exhaust{}", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
   ]
  },
  {
   "title": "NodeFsFilesFull",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:fs:inode_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
   ]
  },
  {
   "title": "NodeFdFull",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:fd_usage", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "Node: Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  { "title": "Node: Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "NodeTcpErrHigh",
   "type": "timeseries",
   "description": "TCP Error Rate > 1 / s",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "rate(node:ins:tcp_error[1m])", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "NodeTcpRetransHigh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    { "expr": "node:ins:tcp_retrans_ratio1m", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "NODE : NTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "NodeNtpSanity",
   "type": "timeseries",
   "description": "Check ntp protocol / clock sanity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min without() (node_ntp_sanity or node_timex_sync_status)",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "NodeClockSkew",
   "type": "timeseries",
   "description": "Clock time offset alert > 50ms",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "abs(node_timex_offset_seconds)", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "PGSQL: Aliveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "PostgresDown",
   "type": "timeseries",
   "description": "Postgres Database Service Aliveness",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "PgbouncerDown",
   "type": "timeseries",
   "description": "Pgbouncer Connection Pooler Aliveness",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "PGSQL : Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "PostgresPartition",
   "type": "timeseries",
   "description": "Number of leader of a postgres partition",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg:cls:partition", "legendFormat": "{{ cls }}" }
   ]
  },
  {
   "title": "PostgresReplicationBreak",
   "type": "timeseries",
   "description": "Number of replication streaming slave change",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(pg_downstream_count{state=\"streaming\"}[5m])",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "PostgresReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "pg:ins:lag_bytes", "legendFormat": "Lag (B)" }
   ]
  },
  {
   "title": "PostgresReplicationLagSeconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg:ins:lag_seconds", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "PGSQL : Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "PostgresPressureHigh",
   "type": "timeseries",
   "description": "Postgres & Pgbouncer load index: Active Time / Available Time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "ins:pressure1", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "PgbouncerQuerySlow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pgbouncer:db:query_rt_1m", "legendFormat": "{{ ins }}:{{ datname }}" }
   ]
  },
  { "title": "PGSQL : Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "PgbouncerClientQueue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pgbouncer:db:waiting_clients", "legendFormat": "{{ ins }}:{{ datname }}" }
   ]
  },
  {
   "title": "PostgresConnUsageHigh",
   "type": "timeseries",
   "description": "Database connection Usage",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "PostgresIdleInXact",
   "type": "timeseries",
   "description": "Idle in Transaction\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:db:ixact_backends{datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  { "title": "PGSQL : Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 241 } },
  {
   "title": "Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "pg:cls:age", "legendFormat": "{{ cls }}" }
   ]
  }
 ]
}