---

#--------------------------------------------------------------#
# 1. Setup node timezone (if given)
#--------------------------------------------------------------#
- name: Setup default node timezone
  tags: node_timezone
  when: node_timezone is defined and node_timezone != ""
  timezone: name={{ node_timezone }}

#--------------------------------------------------------------#
# 2. Make sure ntp/chrony package installed
#--------------------------------------------------------------#
- name: Install ntp or chrony
  tags: [ node_ntp, ntp_config ]
  when: node_ntp_enabled|bool
  block:
    - name: Install chrony package
      package: name=chrony state=present

#--------------------------------------------------------------#
# 3. Config ntp (when node_ntp_setup is true)
# if you already have ntp & chronyd settled, use node_ntp_setup = false
#--------------------------------------------------------------#
- name: Config ntpd and chronyd service
  tags: [ node_ntp, ntp_config ]
  when: node_ntp_enabled|bool
  block:
    - name: Copy the chrony.conf template
      template: src=chrony.conf.j2 dest=/etc/chrony.conf

#--------------------------------------------------------------#
# 4. Launch ntp
#--------------------------------------------------------------#
- name: Launch ntpd and chrony service
  tags: [ node_ntp, ntp_launch ]
  when: node_ntp_enabled|bool
  block:
    - name: Launch chronyd service
      systemd: name=chronyd enabled=true state=restarted


#--------------------------------------------------------------#
# 5. Setup Crontab
#--------------------------------------------------------------#
- name: Append /etc/crontab
  tags: node_cron
  when: node_crontab|length > 0 and not node_crontab_overwrite|bool
  lineinfile: path=/etc/crontab line="{{ item }}"
  with_items: "{{ node_crontab }}"

# overwrite /etc/crontab if node_crontab_overwrite is true
- name: Overwrite /etc/crontab
  tags: node_cron
  when: node_crontab|length > 0 and node_crontab_overwrite|bool
  copy:
    dest: /etc/crontab
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      
      # For details see man 4 crontabs
      
      # Example of job definition:
      # .---------------- minute (0 - 59)
      # |  .------------- hour (0 - 23)
      # |  |  .---------- day of month (1 - 31)
      # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
      # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
      # |  |  |  |  |
      # *  *  *  *  * user-name  command to be executed
      
      {% for item in node_crontab %}
      {{ item }}
      {% endfor %}


...
