{
 "title": "PGLOG Analysis",
 "description": "PostgreSQL Log Sample Analysis",
 "tags": [
  "Pigsty",
  "PGLOG"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log", "label": "Log Table", "query": "pigsty.csvlog" }
  ]
 },
 "panels": [
  {
   "title": "Log Events by Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       level AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Event by ErrCode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       code AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Count by CmdTag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       cmd_tag AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Events by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       coalesce(datname, '<null>') AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Events by Username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       coalesce(username, '<null>') AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT conn, count(*)\nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY conn ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Application",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT appname AS app, count(*)\nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY appname ORDER BY 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT * FROM ${log} WHERE $__timeFilter(ts) ORDER BY ts DESC LIMIT 1000;"
    }
   ]
  }
 ]
}