{
 "title": "PGLOG Instance",
 "description": "PostgreSQL Log for Single Instance",
 "tags": [
  "Pigsty",
  "Instance",
  "Log"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": "label_values(ins)" },
   {
    "name": "job",
    "label": "Log Type",
    "query": "label_values({ins=\"$ins\"},job)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", job=\"$job\"})[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", job=\"$job\"} |~ \"ERROR|FATAL|PANIC\")[$__interval]))",
     "legendFormat": "errs per $__interval"
    }
   ]
  },
  {
   "title": "Searched Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", job=\"$job\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  {
   "title": "Rencent Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{ins=\"$ins\", job=\"$job\"} |~ \"$search\""
    }
   ]
  }
 ]
}