{
 "title": "GPSQL Overview",
 "description": "Greenplum/MatrixDB Cluster Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "GPSQL",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Data Source", "query": "prometheus" },
   { "name": "gp", "label": "Greenplum", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "master",
    "label": "Master",
    "query": {
     "query": "label_values(pg_up{cls=~'$gp.*', cls=~'.*mdw.*'}, cls)"
    }
   },
   {
    "name": "segments",
    "label": "Segments",
    "query": {
     "query": "label_values(pg_up{cls=~'$gp.*(seg|sdw).*'}, cls)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=~\"$gp.*\"}, ip)"
    }
   },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=~'$gp.*', cls=~'.*mdw.*'}, ins)"
    }
   },
   { "name": "cls", "label": "Master", "query": { "query": "label_values(pg_up, cls)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Cluster Name" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_up{cls=~\"$gp.*\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (ip) (pg_up{cls=~\"$gp.*\"}))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{cls=~\"$gp.*\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(max by (cls,datname) (pg_db_age{cls=~\"$gp.*\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(pg:cls:cpu_count{cls=~\"$gp.*\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=~\"$gp.*\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=~\"$gp.*\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(max by (cls,datname)(pg_size_bytes{datname!~\"log|wal\", cls=~\"$gp.*\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "description": "CPU Usage",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{cls=~\"$gp.*\"}",
     "legendFormat": "C {{ cls }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=~\"$gp.*\"}"
    },
    {
     "expr": "ins:pressure1{cls=~\"$gp.*\"}"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:conn_usage{cls=~\"$gp.*\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:query_rate1m{cls=~\"$gp.*\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:waiting_clients{cls=~\"$gp.*\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Memory Usage",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:mem_commit_ratio{cls=~\"$gp.*\"}",
     "legendFormat": "M {{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Space Usage",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{cls=~\"$gp.*\"}",
     "legendFormat": "S {{ ins }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "All nodes among environment ${job}",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "group by (nodename,release,ip,ins,cls) (node_uname_info{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ip) (node:ins:space_usage_max{cls=~\"$gp.*\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{cls=~\"$gp.*\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{cls=~\"$gp.*\"}) / 1000000000"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=~\"$gp.*\"}) by (ip) / 1000000000"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Session",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:num_backends{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Transactions per Seconds",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"}) / sum by (datname) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cls=\"$cls\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cls=\"$cls\", datname!=\"pgbouncer\"})",
     "legendFormat": "Age"
    }
   ]
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage_1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "description": "Number of backends for each instances among this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (cls) (pg_activity_count{cls=~\"$gp.*\"})",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Cluster Pressure",
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cls:pressure1{cls=\"$master\"}",
     "legendFormat": "{{ cls }} ⭐️"
    },
    {
     "expr": "cls:pressure1{cls=~\"$gp.*\", cls!=\"$master\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Total Xacts",
   "type": "timeseries",
   "description": "Total transactions (commit + rollback) per second from PostgreSQL in last 5 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cls) (rate(pg_db_xact_total{cls=~\"$gp.*\", cls=\"$cls\"}[5m])) ",
     "legendFormat": "{{ cls }} ⭐️"
    },
    {
     "expr": "sum by (cls) (rate(pg_db_xact_total{cls=~\"$gp.*\", cls!=\"$cls\"}[5m])) ",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:cls:disk_read_bytes_rate1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}-R▲"
    },
    {
     "expr": "- node:cls:disk_write_bytes_rate1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}-W▼"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:cls:network_tx_bytes_rate1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}-TX▲"
    },
    {
     "expr": "- node:cls:network_rx_bytes_rate1m{cls=~\"$gp.*\"}",
     "legendFormat": "{{ cls }}-RX▼"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Replication Lag (WAL Replay Lag) measured in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=~\"$gp.*\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{cls=~\"$gp.*\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum(rate(pg_db_tup_inserted{cls=~\"$gp.*\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{cls=~\"$gp.*\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{cls=~\"$gp.*\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  }
 ]
}