{
 "title": "Node Overview",
 "description": "Node Home Dashboard",
 "tags": [
  "Pigsty",
  "NODE",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": { "query": "label_values(node_load1, job)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_load1{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "node:env:cpu_count{job=\"$job\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "node:env:mem_total{job=\"$job\"}",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:env:size_bytes{job=\"$job\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:cpu_usage{job=\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:stdload1{job=\"$job\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:mem_usage{job=\"$job\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:space_usage{job=\"$job\"}",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node:cls:cpu_usage{}", "legendFormat": "{{ cls }}" }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "All nodes among environment ${job}",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "group by (nodename,release,ip,ins,cls) (node_uname_info{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:space_usage_max{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{job=\"$job\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{job=\"$job\"}) / 1000000000"
    },
    {
     "expr": "sum(node:fs:size_bytes{job=\"$job\"}) by (ip) / 1000000000"
    },
    {
     "expr": "count by (ip) (up{ip!=\"\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", job=\"$job\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", job=\"$job\"}",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ ins }}"
    }
   ]
  },
  {
   "title": "Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Load 15",
     "type": "timeseries",
     "description": "Standard node load in last 15 minutes (divide by cpu core number)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:stdload15{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Memory Committed",
     "type": "timeseries",
     "description": "Memory commit ratio for each nodes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:mem_commit_ratio{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "NTP Drift",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_ntp_offset_seconds{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Disk IO Bandwidth",
     "type": "timeseries",
     "description": "total disk bandwidth per node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:disk_io_bytes_rate1m{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:env:device_space_usage_max{job=\"$job\"}",
       "legendFormat": "{{ mountpoint }} @ {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}