{
 "title": "Node Cluster",
 "description": "Node: Cluster Dashboard",
 "tags": [
  "Pigsty",
  "NODE",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(node_load1, cls)" } },
   {
    "name": "members",
    "label": "IP Address",
    "query": {
     "query": "label_values(node_load1{cls=\"$cls\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_load1{cls=\"$cls\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "node:cls:cpu_count{cls=\"$cls\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=\"$cls\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:cls:size_bytes{cls=\"$cls\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:stdload1{cls=\"$cls\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:mem_commit_ratio{cls=\"$cls\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{cls=\"$cls\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:fd_usage{cls=\"$cls\"})",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:inode_usage{cls=\"$cls\"})",
     "legendFormat": "iNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:cls:disk_iops_1m{cls=\"$cls\"})",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:disk_io_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "Disk IO"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:network_io_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "Net Traff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:tcp_error_rate1m{cls=\"$cls\"})",
     "legendFormat": "TCP Errs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:tcp_retrans_ratio1m{cls=\"$cls\"})",
     "legendFormat": "Retrans"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:cls:time_drift_max{cls=\"$cls\"})",
     "legendFormat": "Time Drift"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "All nodes among environment ${job}",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "group by (nodename,release,ip,ins,cls) (node_uname_info{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:space_usage_max{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{cls=\"$cls\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{cls=\"$cls\"}) / 1000000000"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=\"$cls\"}) by (ip) / 1000000000"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (type,instance) (up{cls=\"$cls\", job=\"infra\"})",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "min by (ins,ip) (up{cls=\"$cls\", job=\"node\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (up{cls=\"$cls\", job=\"pgsql\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (up{cls=\"$cls\", job=\"redis\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (instance) (up{cls=\"$cls\", job!~\"(node|infra|pgsql|redis)\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage_1m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "node:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:cls:cpu_usage{cls=\"$cls\"}",
       "legendFormat": "Realtime"
      },
      {
       "expr": "node:cls:cpu_usage_1m{cls=\"$cls\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node:cls:cpu_usage_5m{cls=\"$cls\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node:cls:cpu_usage_15m{cls=\"$cls\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Cluster CPU Time by State (per Second)",
     "type": "timeseries",
     "description": "Sum of all state will approximately to the number of cpu core",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{cls=\"$cls\"}[1m]))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "sum(node:cls:cpu_count{cls=\"$cls\"})",
       "legendFormat": "CPU Count"
      }
     ]
    },
    {
     "title": "Instance CPU Usage (1m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage_1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Normalized Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:cls:stdload1{cls=\"$cls\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node:cls:stdload5{cls=\"$cls\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node:cls:stdload15{cls=\"$cls\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Instance Normalized Load (1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:stdload1{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Blocked Processes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_blocked{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Process in D State",
     "type": "timeseries",
     "description": "Uninterruptible sleep (usually IO)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_state{cls=\"$cls\", state=\"D\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Thread",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_processes_threads{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "description": "Context switch rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:ctx_switch_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Fork",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:forks_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Interrupt",
     "type": "timeseries",
     "description": "Interrupt Rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:interrupt_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Memory Structure",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemFree_bytes{cls=\"$cls\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum(node_memory_Cached_bytes{cls=\"$cls\"})",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum(node_memory_Buffers_bytes{cls=\"$cls\"})",
       "legendFormat": "Buffer"
      },
      {
       "expr": "sum(node_memory_PageTables_bytes{cls=\"$cls\"})",
       "legendFormat": "PageTable"
      },
      {
       "expr": "sum(node_memory_Slab_bytes{cls=\"$cls\"})",
       "legendFormat": "Slab"
      },
      {
       "expr": "sum(node_memory_Shmem_bytes{cls=\"$cls\"})",
       "legendFormat": "Shmem"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:mem_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Memory Committed Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{cls=\"$cls\"} / node_memory_CommitLimit_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Memory Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:swap_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Page In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:pagein_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:pageout_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Swap In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:swapin_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:swapout_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Dirty Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Dirty_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Write Back",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Major Page Fault (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pgmajfault_rate1m{cls=\"$cls\"}",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Page Fault (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pagefault_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:disk_reads_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:disk_writes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Read/Write Bandwidth",
     "type": "timeseries",
     "description": "▲ for read bandwidth, ▼ for write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:disk_read_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:disk_write_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Reads/Writes Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of read / write requests\n▲ for read ▼ for write",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:dev:disk_mreads_ratio1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_mwrites_ratio1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Request Size (areq-sz)",
     "type": "timeseries",
     "description": "▲ for read, ▼ for write, Showing I/O pattern",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_batch_1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_batch_1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Await Time",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_rt_1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_rt_1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Average Service Time (svctm)",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_io_rt_1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Instant Queue Size",
     "type": "timeseries",
     "description": "Number of items which were in the queue at the sampling time point",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "average number of operations waiting to be serviced.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:dev:disk_avg_queue_size{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Avail Space 1D Prediction",
     "type": "stat",
     "description": "Prediction of avail filesystem space a day later!",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_predict_1d{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "iNode Usage",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:inode_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Device Error",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{cls=\"$cls\", fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Derive 1h",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:fs:space_deriv1h{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:fs:space_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Exhaust Estimate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:fs:space_exhaust{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FD Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:fd_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Packets",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:network_rx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:network_rx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_pps1m{cls=\"$cls\", device!=\"lo\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:ins:network_rx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:network_rx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:tcp_insegs_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      },
      {
       "expr": "- node:ins:tcp_outsegs_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      }
     ]
    },
    {
     "title": "UDP Datagrams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "- rate(node_netstat_Udp_OutDatagrams{cls=\"$cls\"}[1m])",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{cls=\"$cls\"}[1m])",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Socket InUse",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Socket TimeWait",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_tw{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      { "legendFormat": "Time Wait" }
     ]
    },
    {
     "title": "TCP Retransmission Rate",
     "type": "timeseries",
     "description": "TCP retransmission segments and rate",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:tcp_retrans_ratio1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Active Open (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Passive Open (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Listen Overflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Listen Drop"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} In Error"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Retrans"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:cls:time_drift_range{cls=\"$cls\"}",
       "legendFormat": "Drift Range"
      },
      {
       "expr": "node:cls:time_drift_max{cls=\"$cls\"}",
       "legendFormat": "Drift Max"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:ins:time_drift{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_ntp_sanity{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Time Drift",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_ntp_offset_seconds{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      { "expr": "0", "legendFormat": "Time" }
     ]
    },
    {
     "title": "Node Exporter Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (collector) (node_scrape_collector_duration_seconds{cls=\"$cls\"})",
       "legendFormat": "{{ collector }}"
      }
     ]
    },
    {
     "title": "Hardware Temperature (Max of Instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max by (ins) (node_hwmon_temp_celsius{cls=\"$cls\"})",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  }
 ]
}