{
 "title": "PGCAT Schema",
 "description": "PostgreSQL Catalog Explorer for Single Database",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn}';" },
   {
    "name": "schema",
    "label": "Schema",
    "query": "SELECT nspname FROM pg_namespace;"
   },
   {
    "name": "nspid",
    "label": "SchemaID",
    "query": "SELECT oid FROM pg_namespace WHERE nspname = '$schema';"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "targets": [
    { "rawSql": "SELECT '$ins';" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "rawSql": "SELECT '$datname';" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT '$schema';" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select unnest(nspacl) from pg_namespace WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT json_object_agg(kind, count) AS data\n         FROM (SELECT relkind::TEXT AS kind, count(*) AS count FROM pg_class \n         WHERE relnamespace = '$nspid'\n         GROUP BY 1) d\n     ) j;"
    }
   ]
  },
  {
   "title": "Class",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "SELECT * FROM pg_class;",
     "rawSql": "SELECT \n*, '$schema' || '.' || relname AS \"Name\", relowner::RegRole AS \"Owner\",\npg_relation_size(oid) AS Size, age(relfrozenxid) AS age\nFROM pg_class\nWHERE relnamespace = '$nspid';"
    }
   ]
  },
  {
   "title": "Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tables",
     "type": "table",
     "description": "Tables of current database ${datname}",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "SELECT * FROM pg_class;",
       "rawSql": "SELECT c.oid,\n       n.nspname,\n       n.nspname || '.' || c.relname AS name,\n       CASE WHEN relispartition THEN 'P' ELSE c.relkind END AS kind,\n       age(c.relfrozenxid)::FLOAT / 2147483648 AS relage,\n       (n_tup_ins + n_tup_upd + n_tup_del) AS n_tup_mod,\n       seq_scan + idx_scan AS tbl_scan, seq_tup_read + idx_tup_fetch AS tup_read,\n       reltuples,\n       relpages,\n       relfilenode,\n       pg_table_size(c.oid)                                 AS size,\n       relnatts,\n       s.*\nFROM pg_catalog.pg_class c\n         LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n         LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid\nWHERE c.relkind IN ('r', 'p', '')\nAND schemaname = '$schema'\nORDER BY 1, 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexes",
     "type": "table",
     "description": "Read = Returned Rows\n\nFetch = Scanned Rows",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || indexrelname AS \"Index\", \n       schemaname || '.' || relname AS \"Table\", \n       *,\n       pg_get_indexdef(indexrelid) AS def\nFROM pg_stat_user_indexes\nWHERE schemaname = '$schema';"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all heap tables",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM\n    (SELECT CURRENT_CATALOG                                                                                         AS datname,\n        nspname,\n        relname,\n        tblid,\n        bs * tblpages                                                                                           AS size,\n        CASE WHEN tblpages - est_tblpages_ff > 0 THEN (tblpages - est_tblpages_ff) / tblpages::FLOAT ELSE 0 END AS ratio\n FROM (SELECT ceil(reltuples / ((bs - page_hdr) * fillfactor / (tpl_size * 100))) +\n              ceil(toasttuples / 4) AS est_tblpages_ff,\n              tblpages,\n              fillfactor,\n              bs,\n              tblid,\n              nspname,\n              relname,\n              is_na\n       FROM (SELECT (4 + tpl_hdr_size + tpl_data_size + (2 * ma)\n           - CASE WHEN tpl_hdr_size % ma = 0 THEN ma ELSE tpl_hdr_size % ma END\n           - CASE WHEN ceil(tpl_data_size)::INT % ma = 0 THEN ma ELSE ceil(tpl_data_size)::INT % ma END\n                        )                    AS tpl_size,\n                    (heappages + toastpages) AS tblpages,\n                    heappages,\n                    toastpages,\n                    reltuples,\n                    toasttuples,\n                    bs,\n                    page_hdr,\n                    tblid,\n                    nspname,\n                    relname,\n                    fillfactor,\n                    is_na\n             FROM (SELECT tbl.oid                                                                           AS tblid,\n                          ns.nspname,\n                          tbl.relname,\n                          tbl.reltuples,\n                          tbl.relpages                                                                      AS heappages,\n                          coalesce(toast.relpages, 0)                                                       AS toastpages,\n                          coalesce(toast.reltuples, 0)                                                      AS toasttuples,\n                          coalesce(substring(array_to_string(tbl.reloptions, ' ') FROM 'fillfactor=([0-9]+)')::smallint,\n                                   100)                                                                     AS fillfactor,\n                          current_setting('block_size')::numeric                                            AS bs,\n                          CASE\n                              WHEN version() ~ 'mingw32' OR version() ~ '64-bit|x86_64|ppc64|ia64|amd64' THEN 8\n                              ELSE 4 END                                                                    AS ma,\n                          24                                                                                AS page_hdr,\n                          23 +\n                          CASE WHEN MAX(coalesce(s.null_frac, 0)) > 0 THEN (7 + count(s.attname)) / 8 ELSE 0::int END\n                              + CASE\n                                    WHEN bool_or(att.attname = 'oid' and att.attnum < 0) THEN 4\n                                    ELSE 0 END                                                              AS tpl_hdr_size,\n                          sum((1 - coalesce(s.null_frac, 0)) * coalesce(s.avg_width, 0))                    AS tpl_data_size,\n                          bool_or(att.atttypid = 'pg_catalog.name'::regtype)\n                              OR sum(CASE WHEN att.attnum > 0 THEN 1 ELSE 0 END) <> count(s.attname)        AS is_na\n                   FROM pg_attribute AS att\n                            JOIN pg_class AS tbl ON att.attrelid = tbl.oid\n                            JOIN pg_namespace AS ns ON ns.oid = tbl.relnamespace\n                            LEFT JOIN pg_stats AS s ON s.schemaname = ns.nspname AND s.tablename = tbl.relname AND\n                                                       s.inherited = false AND s.attname = att.attname\n                            LEFT JOIN pg_class AS toast ON tbl.reltoastrelid = toast.oid\n                   WHERE NOT att.attisdropped\n                     AND tbl.relkind = 'r'\n                     AND nspname = '$schema'\n                   GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10) AS s) AS s2) AS s3\n WHERE NOT is_na) bloat"
      }
     ]
    },
    {
     "title": "Table Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM\n    (SELECT CURRENT_CATALOG                                                                                         AS datname,\n        nspname,\n        relname,\n        tblid,\n        bs * tblpages                                                                                           AS size,\n        CASE WHEN tblpages - est_tblpages_ff > 0 THEN (tblpages - est_tblpages_ff) / tblpages::FLOAT ELSE 0 END AS ratio\n FROM (SELECT ceil(reltuples / ((bs - page_hdr) * fillfactor / (tpl_size * 100))) +\n              ceil(toasttuples / 4) AS est_tblpages_ff,\n              tblpages,\n              fillfactor,\n              bs,\n              tblid,\n              nspname,\n              relname,\n              is_na\n       FROM (SELECT (4 + tpl_hdr_size + tpl_data_size + (2 * ma)\n           - CASE WHEN tpl_hdr_size % ma = 0 THEN ma ELSE tpl_hdr_size % ma END\n           - CASE WHEN ceil(tpl_data_size)::INT % ma = 0 THEN ma ELSE ceil(tpl_data_size)::INT % ma END\n                        )                    AS tpl_size,\n                    (heappages + toastpages) AS tblpages,\n                    heappages,\n                    toastpages,\n                    reltuples,\n                    toasttuples,\n                    bs,\n                    page_hdr,\n                    tblid,\n                    nspname,\n                    relname,\n                    fillfactor,\n                    is_na\n             FROM (SELECT tbl.oid                                                                           AS tblid,\n                          ns.nspname,\n                          tbl.relname,\n                          tbl.reltuples,\n                          tbl.relpages                                                                      AS heappages,\n                          coalesce(toast.relpages, 0)                                                       AS toastpages,\n                          coalesce(toast.reltuples, 0)                                                      AS toasttuples,\n                          coalesce(substring(array_to_string(tbl.reloptions, ' ') FROM 'fillfactor=([0-9]+)')::smallint,\n                                   100)                                                                     AS fillfactor,\n                          current_setting('block_size')::numeric                                            AS bs,\n                          CASE\n                              WHEN version() ~ 'mingw32' OR version() ~ '64-bit|x86_64|ppc64|ia64|amd64' THEN 8\n                              ELSE 4 END                                                                    AS ma,\n                          24                                                                                AS page_hdr,\n                          23 +\n                          CASE WHEN MAX(coalesce(s.null_frac, 0)) > 0 THEN (7 + count(s.attname)) / 8 ELSE 0::int END\n                              + CASE\n                                    WHEN bool_or(att.attname = 'oid' and att.attnum < 0) THEN 4\n                                    ELSE 0 END                                                              AS tpl_hdr_size,\n                          sum((1 - coalesce(s.null_frac, 0)) * coalesce(s.avg_width, 0))                    AS tpl_data_size,\n                          bool_or(att.atttypid = 'pg_catalog.name'::regtype)\n                              OR sum(CASE WHEN att.attnum > 0 THEN 1 ELSE 0 END) <> count(s.attname)        AS is_na\n                   FROM pg_attribute AS att\n                            JOIN pg_class AS tbl ON att.attrelid = tbl.oid\n                            JOIN pg_namespace AS ns ON ns.oid = tbl.relnamespace\n                            LEFT JOIN pg_stats AS s ON s.schemaname = ns.nspname AND s.tablename = tbl.relname AND\n                                                       s.inherited = false AND s.attname = att.attname\n                            LEFT JOIN pg_class AS toast ON tbl.reltoastrelid = toast.oid\n                   WHERE NOT att.attisdropped\n                     AND tbl.relkind = 'r'\n                     AND nspname = '$schema'\n                   GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10) AS s) AS s2) AS s3\n WHERE NOT is_na) bloat"
      }
     ]
    },
    {
     "title": "Index Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all btree indexes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM (\n     SELECT CURRENT_CATALOG AS datname, nspname, idxname AS relname, tblid, idxid, relpages::BIGINT * bs AS size,\n            COALESCE((relpages - ( reltuples * (6 + ma - (CASE WHEN index_tuple_hdr % ma = 0 THEN ma ELSE index_tuple_hdr % ma END)\n                                                    + nulldatawidth + ma - (CASE WHEN nulldatawidth % ma = 0 THEN ma ELSE nulldatawidth % ma END))\n                                       / (bs - pagehdr)::FLOAT  + 1 )), 0) / relpages::FLOAT AS ratio\n     FROM (\n              SELECT nspname,idxname,indrelid AS tblid,indexrelid AS idxid,\n                     reltuples,relpages,\n                     current_setting('block_size')::INTEGER                                                               AS bs,\n                     (CASE WHEN version() ~ 'mingw32' OR version() ~ '64-bit|x86_64|ppc64|ia64|amd64' THEN 8 ELSE 4 END)  AS ma,\n                     24                                                                                                   AS pagehdr,\n                     (CASE WHEN max(COALESCE(pg_stats.null_frac, 0)) = 0 THEN 2 ELSE 6 END)                               AS index_tuple_hdr,\n                     sum((1.0 - COALESCE(pg_stats.null_frac, 0.0)) *\n                         COALESCE(pg_stats.avg_width, 1024))::INTEGER                                                     AS nulldatawidth\n              FROM pg_attribute\n                       JOIN (\n                  SELECT pg_namespace.nspname,\n                         ic.relname                                                   AS idxname,\n                         ic.reltuples,\n                         ic.relpages,\n                         pg_index.indrelid,\n                         pg_index.indexrelid,\n                         tc.relname                                                   AS tablename,\n                         regexp_split_to_table(pg_index.indkey::TEXT, ' ') :: INTEGER AS attnum,\n                         pg_index.indexrelid                                          AS index_oid\n                  FROM pg_index\n                           JOIN pg_class ic ON pg_index.indexrelid = ic.oid\n                           JOIN pg_class tc ON pg_index.indrelid = tc.oid\n                           JOIN pg_namespace ON pg_namespace.oid = ic.relnamespace\n                           JOIN pg_am ON ic.relam = pg_am.oid\n                  WHERE pg_am.amname = 'btree' AND ic.relpages > 0 AND nspname = '$schema'\n              ) ind_atts ON pg_attribute.attrelid = ind_atts.indexrelid AND pg_attribute.attnum = ind_atts.attnum\n                       JOIN pg_stats ON pg_stats.schemaname = ind_atts.nspname\n                  AND ((pg_stats.tablename = ind_atts.tablename AND pg_stats.attname = pg_get_indexdef(pg_attribute.attrelid, pg_attribute.attnum, TRUE))\n                      OR (pg_stats.tablename = ind_atts.idxname AND pg_stats.attname = pg_attribute.attname))\n              WHERE pg_attribute.attnum > 0\n              GROUP BY 1, 2, 3, 4, 5, 6\n          ) est\n) bloat;"
      }
     ]
    },
    {
     "title": "Index Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "rawSql": "SELECT nspname || '.' || relname AS relname, size, ratio, size * ratio AS waste FROM (\n     SELECT CURRENT_CATALOG AS datname, nspname, idxname AS relname, tblid, idxid, relpages::BIGINT * bs AS size,\n            COALESCE((relpages - ( reltuples * (6 + ma - (CASE WHEN index_tuple_hdr % ma = 0 THEN ma ELSE index_tuple_hdr % ma END)\n                                                    + nulldatawidth + ma - (CASE WHEN nulldatawidth % ma = 0 THEN ma ELSE nulldatawidth % ma END))\n                                       / (bs - pagehdr)::FLOAT  + 1 )), 0) / relpages::FLOAT AS ratio\n     FROM (\n              SELECT nspname,idxname,indrelid AS tblid,indexrelid AS idxid,\n                     reltuples,relpages,\n                     current_setting('block_size')::INTEGER                                                               AS bs,\n                     (CASE WHEN version() ~ 'mingw32' OR version() ~ '64-bit|x86_64|ppc64|ia64|amd64' THEN 8 ELSE 4 END)  AS ma,\n                     24                                                                                                   AS pagehdr,\n                     (CASE WHEN max(COALESCE(pg_stats.null_frac, 0)) = 0 THEN 2 ELSE 6 END)                               AS index_tuple_hdr,\n                     sum((1.0 - COALESCE(pg_stats.null_frac, 0.0)) *\n                         COALESCE(pg_stats.avg_width, 1024))::INTEGER                                                     AS nulldatawidth\n              FROM pg_attribute\n                       JOIN (\n                  SELECT pg_namespace.nspname,\n                         ic.relname                                                   AS idxname,\n                         ic.reltuples,\n                         ic.relpages,\n                         pg_index.indrelid,\n                         pg_index.indexrelid,\n                         tc.relname                                                   AS tablename,\n                         regexp_split_to_table(pg_index.indkey::TEXT, ' ') :: INTEGER AS attnum,\n                         pg_index.indexrelid                                          AS index_oid\n                  FROM pg_index\n                           JOIN pg_class ic ON pg_index.indexrelid = ic.oid\n                           JOIN pg_class tc ON pg_index.indrelid = tc.oid\n                           JOIN pg_namespace ON pg_namespace.oid = ic.relnamespace\n                           JOIN pg_am ON ic.relam = pg_am.oid\n                  WHERE pg_am.amname = 'btree' AND ic.relpages > 0 AND nspname = '$schema'\n              ) ind_atts ON pg_attribute.attrelid = ind_atts.indexrelid AND pg_attribute.attnum = ind_atts.attnum\n                       JOIN pg_stats ON pg_stats.schemaname = ind_atts.nspname\n                  AND ((pg_stats.tablename = ind_atts.tablename AND pg_stats.attname = pg_get_indexdef(pg_attribute.attrelid, pg_attribute.attnum, TRUE))\n                      OR (pg_stats.tablename = ind_atts.idxname AND pg_stats.attname = pg_attribute.attname))\n              WHERE pg_attribute.attnum > 0\n              GROUP BY 1, 2, 3, 4, 5, 6\n          ) est\n) bloat;"
      }
     ]
    }
   ]
  },
  {
   "title": "Seq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || sequencename AS \"Sequence\", *\nFROM pg_sequences\nWHERE schemaname = '$schema';"
      }
     ]
    }
   ]
  }
 ]
}