{
 "title": "PGCAT Queries",
 "description": "PostgreSQL Catalog Explorer for Query",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database",
  "Query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   {
    "name": "query",
    "label": "Query",
    "query": "SELECT distinct queryid::TEXT FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND userid != 10 LIMIT 1000;"
   },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn}';" }
  ]
 },
 "panels": [
  { "title": "SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQL Statements",
   "type": "table",
   "description": "pg_stat_statements of database ${datname}",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname'\nLIMIT 10000;\n-- ORDER BY mean_exec_time DESC\n-- LIMIT 100;"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "SQL by Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Calls",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 36 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND calls > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Calls",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT\n",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.calls AS value, s.mean_exec_time AS rt\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND calls > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Rows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Rows",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 51 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY rows DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Rows",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT\n",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Time",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 66 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND total_exec_time > 0\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Time",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT\n",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.total_exec_time AS value, s.mean_exec_time AS rt\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND total_exec_time > 0\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by WALs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by WAL",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 81 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND wal_bytes > 0\nORDER BY wal_bytes DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by WAL",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT\n",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.wal_bytes AS value, s.mean_exec_time AS rt\nFROM monitor.pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND wal_bytes > 0\nORDER BY wal_bytes DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  }
 ]
}