{
 "title": "PGSQL Shard",
 "description": "PostgreSQL Monitoring Home Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "Shard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": { "query": "label_values(pg_up, job)" } },
   {
    "name": "shard",
    "label": "Shard",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (cls)(pg_up{cls=~\"$shard.*\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(pg_up{cls=~\"$shard.*\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (ip) (pg_up{cls=~\"$shard.*\"}))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{cls=~\"$shard.*\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(max by (datname) (pg_db_age{cls=~\"$shard.*\", datname!~'template0|template1|postgres'}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(pg:cls:cpu_count{cls=~\"$shard.*\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=~\"$shard.*\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=~\"$shard.*\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(max by (cls,datname)(pg_size_bytes{datname!~\"log|wal\", cls=~\"$shard.*\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:cls:cpu_usage{cls=~\"$shard.*\"} * node:cls:cpu_count{cls=~\"$shard.*\"}) / \nsum(node:cls:cpu_count{cls=~\"$shard.*\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:num_backends{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:xact_commit_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:xact_rollback_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:cls:query_rate1m{cls=~\"$shard.*\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:lsn_rate1m{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "WAL Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{cls=~\"$shard.*\"})",
     "legendFormat": "Space Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_db_age{cls=~\"$shard.*\"}) / 2147483648",
     "legendFormat": "Age Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_repl_replay_diff{cls=~\"$shard.*\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:ixact_backends{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "iXact Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:conn_usage{job=\"$job\", cls=~\"$shard.*\"})",
     "legendFormat": "Conn Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer:cls:waiting_clients{cls=~\"$shard.*\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:load1{job=\"$job\", cls=~\"$shard.*\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "PGSQL Instances",
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "min by (cls,ins,ip) (up{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:space_usage{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:cpu_usage{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:cpu_count{cls=~\"$shard.*\"})"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=~\"$shard.*\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:active_clients{cls=~\"$shard.*\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cls=~\"$shard.*\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", cls=~\"$shard.*\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", cls=~'$shard.*'})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  { "title": "Members", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=~\"$shard.*\"}) + \nmax by (ins) (patroni_standby_leader{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cls,ins,scope) (patroni_version{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_server_version{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_cluster_unlocked{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_pending_restart{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_failsafe_mode_is_active{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_dcs_last_seen{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=~\"$shard.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Cluster CPU 5m Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:cls:cpu_usage_5m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Node Instance CPU 1m Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage_1m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "PG Cluster Load5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(pg:cls:load5{job=\"$job\", cls=~\"$shard.*\"}[5m]) != -1",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "PG Instance Load1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(pg:ins:load1{job=\"$job\", cls=~\"$shard.*\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Instance Session",
     "type": "timeseries",
     "description": "Number of backends for each instances",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (cls) (pg_db_numbackends{cls=~\"$shard.*\"})",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Cluster TPS Rate5m",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(pg:cls:xact_commit_rate5m{cls=~\"$shard.*\"}[1m])",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "Disk Bandwidth",
     "type": "timeseries",
     "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:cls:disk_read_bytes_rate1m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ cls }}-R▲"
      },
      {
       "expr": "- node:cls:disk_write_bytes_rate1m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ cls }}-W▼"
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "timeseries",
     "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:cls:network_tx_bytes_rate1m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ cls }}-TX▲"
      },
      {
       "expr": "- node:cls:network_rx_bytes_rate1m{cls=~\"$shard.*\"}",
       "legendFormat": "{{ cls }}-RX▼"
      }
     ]
    },
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by (cls) (pg_repl_replay_diff{job=\"$job\", cls=~\"$shard.*\"})",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "RT",
     "type": "timeseries",
     "description": "Average transaction response time from pgbouncer\n(You can get from postgres directly after PG14)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pgbouncer:ins:xact_rt_1m{cls=~\"$shard.*\"}\n# pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"} # PG14",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  }
 ]
}