{
 "title": "PGSQL Replication",
 "description": "PostgreSQL Replication of Single cluster",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Cluster" },
    { "expr": "1", "legendFormat": "Leader" }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "leader: {{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Slots",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "max by (ins, slot_name, datname) (pg_slot_retained_bytes{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_active{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_temporary{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_wal_status{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_restart_lsn{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_bytes{cls=\"$cls\"}",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_seconds{cls=\"$cls\"}",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_repl_replay_lag{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_lsn{cls=\"$cls\"} - pg_repl_sent_lsn{cls=\"$cls\"}",
     "legendFormat": "[SENT] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_sent_lsn{cls=\"$cls\"} - pg_repl_write_lsn{cls=\"$cls\"}",
     "legendFormat": "[WRITE] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_write_lsn{cls=\"$cls\"} - pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[FLUSH] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"} - pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "[REPLAY] {{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds (Follower's View)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_lag{cls=\"$cls\"}",
     "legendFormat": "→ {{ ins }}"
    }
   ]
  },
  { "title": "LSN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Replication LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"}",
     "legendFormat": "replay @ {{ appname }}"
    },
    {
     "expr": "pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "flush @ {{ appname }}"
    },
    {
     "expr": "pg_repl_write_lsn{cls=\"$cls\"}",
     "legendFormat": "write @ {{ appname }}"
    },
    {
     "expr": "pg_slot_restart_lsn{cls=\"$cls\"}",
     "legendFormat": "slot restart @ {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Checkpoint LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{ins=\"$primary\"}",
     "legendFormat": "Checkpoint Leader $primary"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "Checkpoint Follower {{ ins }}"
    },
    {
     "expr": "pg_checkpoint_redo_lsn{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "Redo {{ ins }}"
    }
   ]
  },
  {
   "title": "LSN Progress Rate 1m",
   "type": "timeseries",
   "description": "Rate of lsn in last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "XMax Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cls=\"$cls\"}",
     "legendFormat": "xmax-{{ ins }}"
    },
    {
     "expr": "pg_xact_xmin{cls=\"$cls\"}",
     "legendFormat": "xmin-{{ ins }}"
    }
   ]
  },
  {
   "title": "Xmin Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmin{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "XMin Horizon",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(pg_xact_xmax{cls=\"$cls\"})",
     "legendFormat": "XMax"
    },
    {
     "expr": "pg_repl_backend_xmin{cls=\"$cls\"}",
     "legendFormat": "repl: {{ appname }}"
    },
    {
     "expr": "pg_slot_catalog_xmin{cls=\"$cls\"}",
     "legendFormat": "slot: {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Xact in Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xnum{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Slot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Slot Retained Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} reserved for {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Logical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "max by (subname) (pg_sub_id{ins=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_pid{ins=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_received_lsn{ins=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_reported_lsn{ins=\"$primary\"})"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (ins)(pg_pubrel_count{ins=\"$primary\"}) > bool 0 or on() vector(0)",
       "legendFormat": "Publication"
      },
      {
       "expr": "count by (ins)(pg_sub_id{ins=\"$primary\"}) or on() vector(0)",
       "legendFormat": "Subscription"
      }
     ]
    },
    {
     "title": "Publication Table Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 125 },
     "targets": [
      {
       "expr": "pg_pubrel_count{ins=\"$primary\"}",
       "legendFormat": "{{ pubname }}"
      }
     ]
    },
    {
     "title": "Subscription Table Count by State",
     "type": "timeseries",
     "description": "i = init , d = data sync , r = ready",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
     "targets": [
      {
       "expr": "pg_subrel_count{ins=\"$primary\"}",
       "legendFormat": "{{ subname }}.{{ state }}"
      }
     ]
    }
   ]
  }
 ]
}