{
 "title": "PGSQL Persist",
 "description": "PostgreSQL Persistence of single instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Cluster" },
    { "expr": "1", "legendFormat": "IP" },
    { "expr": "1", "legendFormat": "Name" }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg_in_recovery{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:conn_usage{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:query_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:waiting_clients{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:lag_bytes{cls=\"$cls\", ins=~'$cls.*'})"
    },
    {
     "expr": "min by (ins) (up{cls=\"$cls\", job=\"pgsql\"})"
    }
   ]
  },
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pg_bgwriter_checkpoints_req{ins=\"$ins\"} + pg_bgwriter_checkpoints_timed{ins=\"$ins\"}",
     "legendFormat": "Checkpoint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{ins=\"$ins\"}",
     "legendFormat": "Timeline"
    },
    {
     "expr": "pg_checkpoint_prev_tli{ins=\"$ins\"}",
     "legendFormat": "Prev TLI"
    },
    {
     "expr": "pg_checkpoint_elapse{ins=\"$ins\"}",
     "legendFormat": "Last Checkpoint"
    },
    {
     "expr": "pg_checkpoint_next_xid_epoch{ins=\"$ins\"}",
     "legendFormat": "Next Xid Epoch"
    },
    {
     "expr": "pg_checkpoint_next_xid_epoch{ins=\"$ins\"}",
     "legendFormat": "NextXidEpoch"
    },
    {
     "expr": "pg_checkpoint_next_xid{ins=\"$ins\"}",
     "legendFormat": "NextXid"
    },
    {
     "expr": "pg_checkpoint_next_oid{ins=\"$ins\"}",
     "legendFormat": "Next OID"
    },
    {
     "expr": "pg_checkpoint_next_multixact_id{ins=\"$ins\"}",
     "legendFormat": "NextMultiXactID"
    },
    {
     "expr": "pg_checkpoint_next_multi_offset{ins=\"$ins\"}",
     "legendFormat": "NextMultiOffset"
    },
    {
     "expr": "pg_checkpoint_oldest_xid{ins=\"$ins\"}",
     "legendFormat": "Oldest XID"
    }
   ]
  },
  {
   "title": "LSN Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{ins=\"$ins\"}",
     "legendFormat": "Checkpoint"
    }
   ]
  },
  {
   "title": "Checkpoint Sync/Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_checkpoint_sync_time{ins=\"$ins\"}[1m])",
     "legendFormat": "Sync"
    },
    {
     "expr": "- rate(pg_bgwriter_checkpoint_write_time{ins=\"$ins\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_wal_log_hints{ins=\"$ins\"}",
     "legendFormat": "WAL Log Hints"
    },
    {
     "expr": "pg_setting_data_checksums{ins=\"$ins\"}",
     "legendFormat": "Data Checksum"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "XID",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{ins=\"$ins\"}",
     "legendFormat": "xmax"
    },
    {
     "expr": "pg_xact_xmin{ins=\"$ins\"}",
     "legendFormat": "xmin"
    },
    {
     "expr": "pg_db_frozen_xid{ins=\"$ins\"}",
     "legendFormat": "frozen {{ datname }}"
    },
    {
     "expr": "pg_checkpoint_oldest_active_xid{ins=\"$ins\"}",
     "legendFormat": "ckpt oldest active xid"
    },
    {
     "expr": "pg_checkpoint_oldest_xid{ins=\"$ins\"}",
     "legendFormat": "ckpt oldest xid"
    },
    {
     "expr": "pg_checkpoint_next_xid{ins=\"$ins\"}",
     "legendFormat": "ckpt next xid"
    },
    {
     "expr": "pg_checkpoint_newest_commit_ts_xid{ins=\"$ins\"}",
     "legendFormat": "ckpt newest cmt ts xid"
    }
   ]
  },
  {
   "title": "Age Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:age{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Age Exhaust Estimate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(pg:db:age_exhaust{ins=\"$ins\"}, -1)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "BGWriter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Buffer Flush",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_clean{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Clean"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_checkpoint{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_backend{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Buffer Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_alloc{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Alloc"
    }
   ]
  },
  { "title": "Datafile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "PG Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_size_bytes{ins=\"$ins\", datname!~\"(log|wal)\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "WAL & Log Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_size_bytes{ins=\"$ins\", datname=~\"(log|wal)\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Temp File Size (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(pg_db_temp_bytes{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Temp File Count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_db_temp_files{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Size Delta 10m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(pg_size_bytes{ins=\"$ins\", datname!~\"(log|wal)\"}[10m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Size Delta 10m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(pg_size_bytes{ins=\"$ins\", datname=\"wal\"}[10m])",
     "legendFormat": "WAL"
    },
    {
     "expr": "delta(pg_size_bytes{ins=\"$ins\", datname=\"log\"}[10m])",
     "legendFormat": "LOG"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Blocks Access 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg:db:blks_access_1m{ins=\"$ins\"} * 4096",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Read 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg:db:blks_read_1m{ins=\"$ins\"} * 4096",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Read/Write Time Spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:db:blk_read_time_seconds_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲ {{ datname }}"
    },
    {
     "expr": "- pg:db:blk_read_time_seconds_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼ {{ datname }}"
    }
   ]
  },
  {
   "title": "Checksum Failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_cks_fails{ins=\"$ins\", datname!~'postgres|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Archiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Archiver Finished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "pg_archiver_finish_count{ins=\"$ins\"}",
     "legendFormat": "Checkpoint"
    }
   ]
  },
  {
   "title": "Archiver Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "pg_archiver_failed_count{ins=\"$ins\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_archiver_last_finish_time{ins=\"$ins\"}",
     "legendFormat": "Last Finish"
    },
    {
     "expr": "pg_archiver_last_failed_time{ins=\"$ins\"}",
     "legendFormat": "Last Failure"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Writeback / Dirty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{ip=\"$ip\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_Dirty_bytes{ip=\"$ip\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Page In/Out Rate",
   "type": "timeseries",
   "description": "Rate of pages in/out/swapin/swapout",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:pagein_rate1m{ip=\"$ip\"}",
     "legendFormat": "▲PageIn"
    },
    {
     "expr": "- node:ins:pageout_rate1m{ip=\"$ip\"}",
     "legendFormat": "▼PageOut"
    }
   ]
  },
  {
   "title": "Major Page Fault",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:ins:pgmajfault_rate1m{ip=\"$ip\"}",
     "legendFormat": "PageFault"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:ins:pagefault_rate1m{ip=\"$ip\"}",
     "legendFormat": "PageFault"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (device) (node:dev:disk_util_1m{ip=\"$ip\"})",
     "legendFormat": "util"
    },
    {
     "expr": "max by (device) (node:dev:disk_avg_queue_size{ip=\"$ip\"})",
     "legendFormat": "queue"
    },
    {
     "expr": "max by (device) (node:dev:disk_reads_rate1m{ip=\"$ip\"})",
     "legendFormat": "r/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_writes_rate1m{ip=\"$ip\"})",
     "legendFormat": "w/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_mreads_rate1m{ip=\"$ip\"})",
     "legendFormat": "mr/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_mwrites_rate1m{ip=\"$ip\"})",
     "legendFormat": "mw/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_bytes_rate1m{ip=\"$ip\"})",
     "legendFormat": "rb/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_bytes_rate1m{ip=\"$ip\"})",
     "legendFormat": "wb/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_rt_1m{ip=\"$ip\"})",
     "legendFormat": "r_await"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_rt_1m{ip=\"$ip\"})",
     "legendFormat": "w_await"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_batch_1m{ip=\"$ip\"})",
     "legendFormat": "rreq-sz"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_batch_1m{ip=\"$ip\"})",
     "legendFormat": "wreq-sz"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "description": "▲ for read IOPS, ▼ for write IOPS ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:dev:disk_reads_rate1m{ip=\"$ip\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_writes_rate1m{ip=\"$ip\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_write_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node:fs:size_bytes{ip=\"$ip\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (device) (node:fs:avail_bytes{ip=\"$ip\"})",
     "legendFormat": "Avail"
    },
    {
     "expr": "max by (device) (node:fs:size_bytes{ip=\"$ip\"} - node:fs:avail_bytes{ip=\"$ip\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max by (device) (node:fs:space_usage{ins=\"$ins\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max by (device) (node:fs:inode_total{ip=\"$ip\"})",
     "legendFormat": "iNodes"
    },
    {
     "expr": "max by (device) (node:fs:inode_free{ip=\"$ip\"})",
     "legendFormat": "iNode Free"
    },
    {
     "expr": "max by (device) (node:fs:inode_used{ip=\"$ip\"})",
     "legendFormat": "iNode Used"
    },
    {
     "expr": "max by (device) (node:fs:inode_usage{ip=\"$ip\"})",
     "legendFormat": "iNode Usage"
    },
    {
     "expr": "min by (device) (node_filesystem_readonly{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
     "legendFormat": "iNode Usage"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ip=\"$ip\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Space Exhaust Estimate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node:fs:space_exhaust{ip=\"$ip\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "PGSQL I/O (16beta)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write Rate 1m",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (ins) (rate(pg_io_reads{ins=\"$ins\"}[1m]))",
       "legendFormat": "▲{{ type }}"
      },
      {
       "expr": "- sum by (ins) (rate(pg_io_writes{ins=\"$ins\"}[1m]))",
       "legendFormat": "▼{{ type }}"
      }
     ]
    },
    {
     "title": "Read/Write Bandwidth",
     "type": "timeseries",
     "description": "▲ for read bandwidth, ▼ for write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (ins) (rate(pg_io_reads{ins=\"$ins\"}[1m]) * pg_io_op_bytes{ins=\"$ins\"})",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- sum by (ins) (rate(pg_io_reads{ins=\"$ins\"}[1m]) * pg_io_op_bytes{ins=\"$ins\"})",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Operations Rate 1min",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pg_io_reads{ins=\"$ins\"}[1m]))",
       "legendFormat": "reads"
      },
      {
       "expr": "sum(rate(pg_io_writes{ins=\"$ins\"}[1m]))",
       "legendFormat": "writes"
      },
      {
       "expr": "sum(rate(pg_io_hits{ins=\"$ins\"}[1m]))",
       "legendFormat": "hits"
      },
      {
       "expr": "sum(rate(pg_io_writebacks{ins=\"$ins\"}[1m]))",
       "legendFormat": "writeback"
      },
      {
       "expr": "sum(rate(pg_io_extends{ins=\"$ins\"}[1m]))",
       "legendFormat": "extends"
      },
      {
       "expr": "sum(rate(pg_io_fsyncs{ins=\"$ins\"}[1m]))",
       "legendFormat": "fsyncs"
      }
     ]
    },
    {
     "title": "Operations Response Time 1min",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(pg_io_read_time{ins=\"$ins\"}[1m])) / sum(rate(pg_io_reads{ins=\"$ins\"}[1m]))",
       "legendFormat": "reads"
      },
      {
       "expr": "sum(rate(pg_io_write_time{ins=\"$ins\"}[1m])) / sum(rate(pg_io_writes{ins=\"$ins\"}[1m]))",
       "legendFormat": "writes"
      },
      {
       "expr": "sum(rate(pg_io_writeback_time{ins=\"$ins\"}[1m])) / sum(rate(pg_io_writebacks{ins=\"$ins\"}[1m]))",
       "legendFormat": "writeback"
      },
      {
       "expr": "sum(rate(pg_io_extend_time{ins=\"$ins\"}[1m])) / sum(rate(pg_io_extends{ins=\"$ins\"}[1m]))",
       "legendFormat": "extends"
      },
      {
       "expr": "sum(rate(pg_io_fsync_time{ins=\"$ins\"}[1m])) / sum(rate(pg_io_fsyncs{ins=\"$ins\"}[1m]))",
       "legendFormat": "fsyncs"
      }
     ]
    },
    {
     "title": "I/O Ops/s in Last minute",
     "type": "table",
     "description": "OPS / s\n",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "sum by (type) (rate(pg_io_reads{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_writes{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_writebacks{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_extends{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_fsyncs{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_hits{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_evictions{ins=\"$ins\"}[1m]))"
      },
      {
       "expr": "sum by (type) (rate(pg_io_reuses{ins=\"$ins\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}