{
 "title": "PGSQL Overview",
 "description": "PostgreSQL Monitoring Home Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": { "query": "label_values(pg_up, job)" } },
   { "name": "ds", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cls) (pg_up{job=\"$job\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(pg_up{job=\"$job\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{job=\"$job\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(count(pg_up{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(max by (cls,datname) (pg_db_age{job=\"$job\", datname!~'template0|template1|postgres'}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(pg:cls:cpu_count{job=\"$job\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(pg:ins:mem_size{job=\"$job\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (cls,datname)(pg_size_bytes{datname!~\"log|wal\", job=\"$job\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:cpu_usage{job=\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:num_backends{job=\"$job\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_commit_rate1m{job=\"$job\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_rollback_rate1m{job=\"$job\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:env:query_rate1m{job=\"$job\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:lsn_rate1m{job=\"$job\"}",
     "legendFormat": "WAL Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:space_usage{job=\"$job\"})",
     "legendFormat": "Space Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:age{job=\"$job\"}",
     "legendFormat": "Age Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:lag_bytes{job=\"$job\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:ixact_backends{job=\"$job\"})",
     "legendFormat": "iXact Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:conn_usage{job=\"$job\"})",
     "legendFormat": "Conn Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer:cls:waiting_clients{job=\"$job\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cls:pressure1{job=\"$job\"}",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "PGSQL Instances",
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "pg:ins:status{job=\"$job\"}"
    },
    {
     "expr": "pg:ins:load1{job=\"$job\"}"
    },
    {
     "expr": "pg:ins:space_usage{job=\"$job\"}"
    },
    {
     "expr": "pg:ins:cpu_usage{job=\"$job\"}"
    },
    {
     "expr": "pg:ins:cpu_count{job=\"$job\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", job=\"$job\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=\"$job\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "PostgreSQL Cluster Load 5\nLoad = active session time / total cpu time",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:load5{job=\"$job\"} != -1",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "PostgreSQL Instance Load 1\nLoad = active session time / total cpu time",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:load1{job=\"$job\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Patroni Members",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "max by (ins) (patroni_primary{}) + \nmax by (ins) (patroni_standby_leader{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (cls,ins,scope) (patroni_version{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_postgres_server_version{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_is_paused{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_cluster_unlocked{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_pending_restart{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_failsafe_mode_is_active{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_xlog_paused{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (patroni_postgres_running{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (time() - patroni_dcs_last_seen{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (time() - patroni_postmaster_start_time{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases & Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database",
     "type": "table",
     "description": "Business Database among this cluster\nValue means current connections\n\nClick goes to PGSQL Database Dashboard",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cls,datname) (pg_db_numbackends{job=\"$job\", datname!~\"wal|log|postgres|template\\\\d\"})",
       "legendFormat": "{{ datname }} @ {{ cls }}"
      }
     ]
    },
    {
     "title": "Service",
     "type": "table",
     "description": "Service among this environment",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_current_sessions{jproxy!=\"stats\"})",
       "legendFormat": "{{ datname }} @ {{ cls }}"
      }
     ]
    }
   ]
  }
 ]
}