{
 "title": "PGSQL Database",
 "description": "PostgreSQL Database Overview",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"},datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Database" },
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Cluster" }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cls}",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_datid{ins=\"$ins\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:age{ins=\"$ins\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{ins=\"$ins\"} + pg_db_allow_conn{ins=\"$ins\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$ins\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$ins\"})",
     "legendFormat": "Conn Limit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_rollback_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:ixact_backends{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "iXact"
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_temp_bytes{ins=\"$ins\", datname=\"$datname\"}[5m]))",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_numbackends{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}) \n+ sum by (relname) (pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (datname, query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:age{ins=\"$ins\", datname=\"$datname\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "PG Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:tup_fetched_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Row Fetch / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:tup_modified_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Row Modify / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:active_time_rate1m{ins=\"$ins\", datname=\"$datname\"}\n/ pg:db:num_backends{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Active Time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:rlock_count{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "Read Locks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:wlock_count{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "Write Locks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xlock_count{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "EX Locks"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Session",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_db_numbackends{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pgbouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_servers{ins=\"$ins\",datname=\"$datname\"})",
     "legendFormat": "Pool Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_clients{ins=\"$ins\",datname=\"$datname\"})",
     "legendFormat": "Pool Client"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "PGB Conn"
    }
   ]
  },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Database in Pgbouncer of this instance ${ins}",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{ins=\"$ins\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:xact_rate1m{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:xact_rt_1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Xact RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pgbouncer_pool_waiting_clients{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rate1m{ins=\"$ins\",datname=\"$datname\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rt_1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "Query RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:rx_rate1m{ins=\"$ins\", datname=\"$datname\"}) + sum(pgbouncer:db:tx_rate1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "Traffic"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Query RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Time Spent (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Rows (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query by Time (1h)",
   "type": "piechart",
   "description": "Time spent on executing statements  during last 1 hour",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query by Call (1h)",
   "type": "piechart",
   "description": "number of statement call in last 1 hour",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_calls{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}