{
 "title": "PGSQL PITR",
 "description": "PostgreSQL PITR Auxiliary Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cls)"
    }
   },
   {
    "name": "instances",
    "label": "Log Ins",
    "query": {
     "query": "label_values(up{cls=\"$cls\"},ins)"
    }
   },
   { "name": "src", "label": "Log Src", "query": "postgres,pgbackrest,patroni" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "PITR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XID Progress",
   "type": "timeseries",
   "description": "TransactionID xmax on each instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "LSN Progress",
   "type": "timeseries",
   "description": "Current WAL Sequence Number on each Instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_lsn{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Postgres & Patroni PITR Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_xact_xmax{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (ins) (pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins,state) (pg_recv_flush_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"} < bool on(cls) group_left() max by (cls)(pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins,ip) (pg_up{cls=\"$cls\", job=\"pgsql\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue  = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow : Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=~\"$members\"}",
     "legendFormat": "postgres {{ ins }}"
    },
    {
     "expr": "pgbouncer_up{ip=~\"$members\"}",
     "legendFormat": "pgbouncer {{ ins }}"
    },
    {
     "expr": "patroni_up{ip=~\"$members\"}",
     "legendFormat": "patroni {{ ins }}"
    },
    {
     "expr": "pg_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pg_exporter {{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgb_exporter {{ ins }}"
    },
    {
     "expr": "node_up{ip=~\"$members\"}",
     "legendFormat": "node {{ ins }}"
    },
    {
     "expr": "haproxy_up{ip=~\"$members\"}",
     "legendFormat": "haproxy {{ ins }}"
    },
    {
     "expr": "docker_up{ip=~\"$members\"}",
     "legendFormat": "docker {{ ins }}"
    },
    {
     "expr": "promtail_up{ip=~\"$members\"}",
     "legendFormat": "promtail {{ ins }}"
    },
    {
     "expr": "infra_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mongo_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=~\"$members\"}",
     "legendFormat": "mysql {{ ins }}"
    },
    {
     "expr": "mysql_exporter_up{ip=~\"$members\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue  = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow : Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"} < bool on(cls) group_left() \nmax by (cls)(pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Leadership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cls=\"$cls\"} == 0) * 0 + 1",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"postgres\"})[5m]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"patroni\"})[5m]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src)(count_over_time(({cls=\"$cls\", src=\"pgbackrest\"})[5m]))",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"postgres\"})[$__interval]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"patroni\"})[$__interval]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (sum(count_over_time(({cls=\"$cls\", src=\"pgbackrest\"})[$__interval])))",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Searched Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cls=\"$cls\", job=\"pgsql\", ins=~\"$instances\", src=~\"$src\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "${src} logs",
   "type": "logs",
   "description": "Recent logs for pgbouncer & patroni & postgres",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{cls=\"$cls\", job=\"pgsql\", ins=~\"$instances\", src=~\"$src\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Docs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 33, "w": 24, "x": 0, "y": 52 },
     "options": {
      "content": "[PITR](https://pigsty.io/docs/pgsql/pitr): https://pigsty.io/docs/pgsql/pitr | [PITR 中文](https://pigsty.io/docs/pgsql/pitr/)\n\nGet PITR hint from `/pg/bin/pg-pitr` script\n\n\n```bash\npg-pitr                                 # restore to wal archive stream end (e.g. used in case of entire DC failure)\npg-pitr -i                              # restore to the time of latest backup complete (not often used)\npg-pitr --time=\"2022-12-30 14:44:44+08\" # restore to specific time point (in case of drop db, drop table)\npg-pitr --name=\"my-restore-point\"       # restore TO a named restore point create by pg_create_restore_point\npg-pitr --lsn=\"0/7C82CB8\" -X            # restore right BEFORE a LSN\npg-pitr --xid=\"1234567\" -X -P           # restore right BEFORE a specific transaction id, then promote\npg-pitr --backup=latest                 # restore to latest backup set\npg-pitr --backup=20221108-105325        # restore to a specific backup set, which can be checked with pgbackrest info\n\npg-pitr                                 # pgbackrest --stanza=pg-meta restore\npg-pitr -i                              # pgbackrest --stanza=pg-meta --type=immediate restore\npg-pitr -t \"2022-12-30 14:44:44+08\"     # pgbackrest --stanza=pg-meta --type=time --target=\"2022-12-30 14:44:44+08\" restore\npg-pitr -n \"my-restore-point\"           # pgbackrest --stanza=pg-meta --type=name --target=my-restore-point restore\npg-pitr -b 20221108-105325F             # pgbackrest --stanza=pg-meta --type=name --set=20221230-120101F restore\npg-pitr -l \"0/7C82CB8\" -X               # pgbackrest --stanza=pg-meta --type=lsn --target=\"0/7C82CB8\" --target-exclusive restore\npg-pitr -x 1234567 -X -P                # pgbackrest --stanza=pg-meta --type=xid --target=\"0/7C82CB8\" --target-exclusive --target-action=promote restore\n```\n\nPITR SOP Manual\n\n\n```bash\n[1. Stop PostgreSQL] ===========================================\n   1.1 Pause Patroni (if there are any replicas)\n       $ pg pause <cls>  # pause patroni auto failover\n   1.2 Shutdown Patroni\n       $ pt-stop         # sudo systemctl stop patroni\n   1.3 Shutdown Postgres\n       $ pg-stop         # pg_ctl -D /pg/data stop -m fast\n\n[2. Perform PITR] ===========================================\n   2.1 Restore Backup\n       $ pgbackrest --stanza=pg-test --type=time --target='2022-12-30 14:44:44+08' restore\n   2.2 Start PG to Replay WAL\n       $ pg-start        # pg_ctl -D /pg/data start\n   2.3 Validate and Promote\n     - If database content is ok, promote it to finish recovery, otherwise goto 2.1\n       $ pg-promote      # pg_ctl -D /pg/data promote\n\n[3. Restore Primary] ===========================================\n   3.1 Enable Archive Mode (Restart Required)\n       $ psql -c 'ALTER SYSTEM SET archive_mode = on;'\n   3.1 Restart Postgres to Apply Changes\n       $ pg-restart      # pg_ctl -D /pg/data restart\n   3.3 Restart Patroni\n       $ pt-restart      # sudo systemctl restart patroni\n\n[4. Restore Cluster] ===========================================\n   4.1 Re-Init All **REPLICAS** (if any)\n       - 4.1.1 option 1: restore replicas with same pgbackrest cmd (require central backup repo)\n           $ pgbackrest --stanza=pg-test --type=time --target='2022-12-30 14:44:44+08' restore\n       - 4.1.2 option 2: nuke the replica data dir and restart patroni (may take long time to restore)\n           $ rm -rf /pg/data/*; pt-restart\n       - 4.1.3 option 3: reinit with patroni, which may fail if primary lsn < replica lsn\n           $ pg reinit pg-test\n   4.2 Resume Patroni\n       $ pg resume pg-test   # enable auto-failover again\n   4.3 Full Backup (optional)\n       $ pg-backup full      # IT's recommend to make a new full backup after PITR\n```"
     }
    }
   ]
  }
 ]
}