{
 "title": "PGSQL Service",
 "description": "Postgres Cluster Service",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster",
  "Service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "svc",
    "label": "Service",
    "query": {
     "query": "label_values(haproxy_server_check_status, proxy)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(haproxy_server_check_status{proxy='$svc'}, cls)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(haproxy_server_check_status{proxy='$svc'}, proxy)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service",
   "type": "stat",
   "description": "Service = ${svc}. Which is unique identifier of service",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "Service among cluster. Number of routes from proxy to server",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    },
    {
     "expr": "sum by (proxy) (haproxy_server_status{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "All haproxy instances in this cluster ${cls}",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum without (proxy) (haproxy_backend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "sum by (ins) (haproxy_server_status{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "max by (ins) ((100 - haproxy_process_idle_time_percent{cls=\"$cls\", proxy=\"$svc\"}))  / 100"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Role is service identifier among cluster. e.g primary, replica, standby, offline, delayed, etc....",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Proxy",
   "type": "stat",
   "description": "Number of haproxy instance among this cluster that provide service for ${svc}",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(haproxy_server_check_status{cls=\"$cls\", proxy=\"$svc\"}) by (ins))",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "description": "Number of postgres instance among this cluster that provide service ${svc}",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count(haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"}) by (ins))",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "Active Session"
    },
    {
     "expr": "count(sum by (server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"}) > 0)",
     "legendFormat": "Active Server"
    },
    {
     "expr": "count(sum by (ins)(haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"} > 0))",
     "legendFormat": "Active Proxy"
    }
   ]
  },
  {
   "type": "table",
   "description": "All postgres instance among this cluster",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (server)(haproxy_server_status{proxy=~\"$svc\"})",
     "legendFormat": "Route"
    },
    {
     "expr": "max by (server) (haproxy_server_weight{proxy=~\"$svc\"})"
    },
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{proxy=~\"$svc\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_current_sessions{cls=\"$cls\"}\n)"
    }
   ]
  },
  { "title": "Service ${svc}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "svc" },
  {
   "title": "Active Session",
   "type": "timeseries",
   "description": "Session are created between proxies(haproxy) and servers(postgres).",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ ins }} ➔ {{ server }}"
    }
   ]
  },
  {
   "title": "Active Session (by Server)",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Active Session (by Proxy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_frontend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Busy Ratio (of Proxy)",
   "type": "timeseries",
   "description": "HAProxy CPU Usage (busy ratio)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "haproxy:ins:usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Busy Ratio (of Server)",
   "type": "timeseries",
   "description": "PostgreSQL Instance CPU Usage (busy ratio)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ins:pressure1{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Traffic (by Proxy)",
   "type": "timeseries",
   "description": "▲ for out traffic\n▼ for incoming traffic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(haproxy_frontend_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ ins }}-TX▲"
    },
    {
     "expr": "- sum by (ins) (rate(haproxy_frontend_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ ins }}-RX▼"
    }
   ]
  },
  {
   "title": "Traffic (by Server)",
   "type": "timeseries",
   "description": "▲ for out traffic\n▼ for incoming traffic",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(haproxy_server_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ server }}-TX▲"
    },
    {
     "expr": "- sum by (server) (rate(haproxy_server_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ server }}-RX▼"
    }
   ]
  }
 ]
}