#!/bin/bash
set -uo pipefail
#==============================================================#
# File      :   pg-primary-member
# Desc      :   retrieve patroni primary member name from patroni REST API
# Path      :   /pg/bin/pg-primary-member
# Depend    :   patroni
# License   :   AGPLv3 @ https://pigsty.io/docs/about/license
# Author    :   waiting
#==============================================================#

name=$(/usr/bin/patronictl -c /pg/bin/patroni.yml list -f json 2>/dev/null | jq -r '.[] | select(.Role == "Leader") | .Member' )
echo $name

