{
 "title": "PGSQL Alert",
 "description": "PostgreSQL Alerts",
 "tags": [
  "Pigsty",
  "Overview",
  "Alert"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "stat",
   "gridPos": { "y": 1, "h": 7, "w": 5, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "y": 1, "h": 7, "w": 19, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}⚡️] {{alertname}}  @ {{ cls }}"
    },
    {
     "expr": "ALERTS{alertstate=\"pending\"}",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ cls }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Alert", "type": "alertlist", "gridPos": { "y": 8, "h": 18, "w": 6, "x": 0 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "y": 8, "h": 18, "w": 18, "x": 6 } },
  { "title": "ALL: Aliveness", "type": "row", "gridPos": { "y": 26, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "InfraDown",
   "type": "timeseries",
   "description": "Infrastructure Aliveness (Including Node & Haproxy)",
   "gridPos": { "y": 27, "h": 8, "w": 12, "x": 0 },
   "targets": [
    {
     "expr": "infra:ins:up{job=\"infra\"}",
     "legendFormat": "{{ type }}@{{ instance }}"
    }
   ]
  },
  {
   "title": "AgentDown",
   "type": "timeseries",
   "description": "Agent Aliveness (node_exporter, pg_exporter, pgbouncer_exporter, haproxy_exporter)",
   "gridPos": { "y": 27, "h": 8, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "up{job!=\"meta\"}",
     "legendFormat": "{{ ins }}@{{ instance }}"
    }
   ]
  },
  {
   "title": "PostgresDown",
   "type": "timeseries",
   "description": "Postgres Database Service Aliveness",
   "gridPos": { "y": 35, "h": 8, "w": 12, "x": 0 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "PgbouncerDown",
   "type": "timeseries",
   "description": "Pgbouncer Connection Pooler Aliveness",
   "gridPos": { "y": 35, "h": 8, "w": 12, "x": 12 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "NODE : CPU & Load",
   "type": "row",
   "gridPos": { "y": 43, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NODE_CPU_HIGH",
     "type": "timeseries",
     "gridPos": { "y": 3, "h": 7, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:cpu_usage{} * 100", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "NODE_LOAD_HIGH",
     "type": "timeseries",
     "description": "Standard Load (divide by cpu count)",
     "gridPos": { "y": 3, "h": 7, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:stdload5{}", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE: Memory & Swap",
   "type": "row",
   "gridPos": { "y": 44, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "NODE : Disk & Filesystem",
   "type": "row",
   "gridPos": { "y": 45, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NODE_FS_FULL",
     "type": "timeseries",
     "gridPos": { "y": 5, "h": 7, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:space_usage{}", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NODE_FS_PREDICT_FULL",
     "type": "timeseries",
     "gridPos": { "y": 5, "h": 7, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "node:fs:space_exhaust", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NODE_INODE_FULL",
     "type": "timeseries",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:inode_usage{}", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NODE_FD_FULL",
     "type": "timeseries",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:fd_usage{}", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE : Network & Protocol",
   "type": "row",
   "gridPos": { "y": 46, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "NODE : Miscellaneous",
   "type": "row",
   "gridPos": { "y": 47, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "PGSQL : Replication",
   "type": "row",
   "gridPos": { "y": 48, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "PGSQL : Activity",
   "type": "row",
   "gridPos": { "y": 49, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL_LOAD_HIGH",
     "type": "timeseries",
     "description": "Postgres & Pgbouncer load index: Active Time / Available Time",
     "gridPos": { "y": 9, "h": 7, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "pg:ins:pressure1{}", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PGSQL_CONN_HIGH",
     "type": "timeseries",
     "description": "Connection Usage Ratio",
     "gridPos": { "y": 9, "h": 7, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cls,ins) (pg_db_numbackends) / min by (cls,ins) (pg_setting_max_connections)",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Session",
   "type": "row",
   "gridPos": { "y": 50, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "PGSQL : Persist",
   "type": "row",
   "gridPos": { "y": 51, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  },
  {
   "title": "PGSQL: Miscellaneous",
   "type": "row",
   "gridPos": { "y": 52, "h": 1, "w": 24, "x": 0 },
   "collapsed": true
  }
 ]
}