{
 "title": "PGSQL Query",
 "description": "PGSQL Query Dashboard",
 "tags": [
  "Pigsty",
  "Database",
  "Query"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up{}, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "query",
    "label": "Query",
    "query": {
     "query": "label_values(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}, query)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "y": 1, "h": 6, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Database Statementes",
   "type": "table",
   "gridPos": { "y": 1, "h": 13, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"})  > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query)(increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[15m]))",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[15m]))",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "timeseries",
   "gridPos": { "y": 7, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spend per Second",
   "type": "timeseries",
   "gridPos": { "y": 14, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spent in Last 1h",
   "type": "piechart",
   "gridPos": { "y": 14, "h": 7, "w": 12, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "y": 21, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "y": 22, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:query:call{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "y": 22, "h": 7, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS Divergence",
   "type": "timeseries",
   "gridPos": { "y": 29, "h": 5, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])) ^ 2",
     "legendFormat": "QPS Divergence"
    }
   ]
  },
  {
   "title": "RT Divergence",
   "type": "timeseries",
   "gridPos": { "y": 29, "h": 5, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])) ^ 2",
     "legendFormat": "RT Divergence"
    }
   ]
  },
  {
   "title": "QPS (Dist 15m Offset 8m)",
   "type": "timeseries",
   "gridPos": { "y": 34, "h": 16, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}  OFFSET 450s",
     "legendFormat": "QPS"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + 3 * stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - 3 * stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "RT  (Dist 15m Offset 8m)",
   "type": "timeseries",
   "description": "Average Response time in last 15 minute (offset 8min)",
   "gridPos": { "y": 34, "h": 16, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}  OFFSET 450s",
     "legendFormat": "RT"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + 3 * stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - 3 * stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Total Rows Returned (1m, 5m, 15m)",
   "type": "timeseries",
   "gridPos": { "y": 50, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Average Rows Returned per Query",
   "type": "timeseries",
   "gridPos": { "y": 50, "h": 7, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Total WAL Bytes Generated",
   "type": "timeseries",
   "gridPos": { "y": 57, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "WAL Bytes Generated per Query",
   "type": "timeseries",
   "gridPos": { "y": 57, "h": 7, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "increase(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Exec Time Spent",
   "type": "timeseries",
   "gridPos": { "y": 64, "h": 7, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "IO Time Spent",
   "type": "timeseries",
   "gridPos": { "y": 64, "h": 7, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  }
 ]
}