{
 "title": "PGSQL Tables",
 "description": "PGSQL Tables overview of single database",
 "tags": [
  "Pigsty",
  "Database",
  "Table"
 ],
 "time": { "to": "now", "from": "now-1h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up{}, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance identifier ${ins}",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "y": 0, "h": 2, "w": 6, "x": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:status{ins=\"$ins\"}"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "y": 2, "h": 1, "w": 24, "x": 0 } },
  {
   "type": "piechart",
   "gridPos": { "y": 3, "h": 11, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (relname) ",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "y": 3, "h": 11, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_class_relsize{ins=\"$ins\", datname=\"$datname\"}) by (nspname,relname) "
    },
    {
     "expr": "sum(pg_class_reltuples{ins=\"$ins\", datname=\"$datname\"}) by (relname) "
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "row",
   "gridPos": { "y": 14, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Scan",
     "type": "timeseries",
     "gridPos": { "y": 15, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Sequential Scan",
     "type": "timeseries",
     "gridPos": { "y": 15, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(pg_table_seq_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Index Scan -- Scanned Tuples",
     "type": "timeseries",
     "gridPos": { "y": 23, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Sequential Scan -- Scanned Tuples",
     "type": "timeseries",
     "description": "Rate of tuples been sequential scanned",
     "gridPos": { "y": 23, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Index Scan -- Rows per Scan",
     "type": "timeseries",
     "gridPos": { "y": 31, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Total Scanned  Tuples",
     "type": "timeseries",
     "gridPos": { "y": 31, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_table_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_table_seq_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    }
   ]
  },
  { "title": "Table Modify", "type": "row", "gridPos": { "y": 15, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "y": 16, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "y": 16, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "y": 24, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated Ratio",
   "type": "timeseries",
   "gridPos": { "y": 24, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_table_n_tup_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Modified",
   "type": "timeseries",
   "gridPos": { "y": 32, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_mod{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated",
   "type": "timeseries",
   "gridPos": { "y": 32, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Tuple",
   "type": "row",
   "gridPos": { "y": 40, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Tuple",
     "type": "timeseries",
     "gridPos": { "y": 65, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Dead Tuple",
     "type": "timeseries",
     "gridPos": { "y": 65, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Live Tuple Delta",
     "type": "timeseries",
     "gridPos": { "y": 73, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_table_n_live_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Dead Tuple Delta",
     "type": "timeseries",
     "gridPos": { "y": 73, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_table_n_dead_tup{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    }
   ]
  },
  { "title": "Index Access", "type": "row", "gridPos": { "y": 41, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Index Access",
   "type": "timeseries",
   "gridPos": { "y": 42, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Blocks Hit Ratio",
   "type": "timeseries",
   "gridPos": { "y": 42, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]) / (rate(pg_index_idx_blks_read{ins=\"$ins\", datname=\"$datname\"}[1m]) + rate(pg_index_idx_blks_hit{ins=\"$ins\", datname=\"$datname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read",
   "type": "timeseries",
   "gridPos": { "y": 50, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched",
   "type": "timeseries",
   "gridPos": { "y": 50, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read per Scan",
   "type": "timeseries",
   "gridPos": { "y": 58, "h": 8, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched per Scan",
   "type": "timeseries",
   "gridPos": { "y": 58, "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{ins=\"$ins\", datname=\"$datname\"}[1m])  / rate(pg_index_idx_scan{ins=\"$ins\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "y": 66, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Function Call",
     "type": "timeseries",
     "gridPos": { "y": 67, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Time Spend (Stacked)",
     "type": "timeseries",
     "gridPos": { "y": 67, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration (Self Time)",
     "type": "timeseries",
     "gridPos": { "y": 75, "h": 8, "w": 12, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_self_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration",
     "type": "timeseries",
     "gridPos": { "y": 75, "h": 8, "w": 12, "x": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{ins=\"$ins\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "y": 67, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacuum (1m)",
     "type": "timeseries",
     "gridPos": { "y": 124, "h": 8, "w": 24, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(pg_table_vacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autovacuum_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Analyze (1m)",
     "type": "timeseries",
     "description": "How many analyze (auto + manual) executed in last 1m on each table",
     "gridPos": { "y": 132, "h": 8, "w": 24, "x": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(pg_table_analyze_count{ins=\"$ins\", datname=\"$datname\"}[1m]) + increase(pg_table_autoanalyze_count{ins=\"$ins\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    }
   ]
  }
 ]
}