{
 "title": "MYSQL Instance",
 "description": "MySQL Instance Dashboard",
 "tags": [
  "Pigsty",
  "MYSQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(mysql_up,ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(mysql_up{ins=\"$ins\"} ,ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(mysql_up{ins=\"$ins\"},ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysql_up{ins=\"$ins\"},cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Cluster" },
    { "expr": "1", "legendFormat": "IP" },
    { "expr": "1", "legendFormat": "Name" }
   ]
  },
  {
   "title": "MySQL Instances",
   "type": "table",
   "description": "All instances in mysql cluster ${cls}",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (cls,ins,ip) (mysql_up{})"
    },
    {
     "expr": "sum by (ins) (rate(mysql_global_status_queries{}[$interval]))"
    },
    {
     "expr": "sum by (ins) (rate(mysql_global_status_commands_total{}[$interval]))"
    },
    {
     "expr": "sum by (ins) (mysql_global_status_threads_connected{})"
    }
   ]
  },
  {
   "title": "QPS/TPS",
   "type": "timeseries",
   "description": "QPS计算只包括客户端发送到服务器的语句，而不包括存储程序中执行的语句\n- 以下命令不被统计：\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{ins=\"$ins\"}[$interval])",
     "legendFormat": "QPS"
    },
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(mysql_global_status_commands_total{ins=\"$ins\",command=~\"(commit|rollback)\"}[$interval])) without (command)",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_running{ins=\"$ins\"}",
     "legendFormat": "Active Conn"
    },
    {
     "calculatedInterval": "2m",
     "expr": "delta(mysql_global_status_connection_errors_total{ins=\"$ins\"}[1m]) > 0",
     "legendFormat": "ERROR: {{error}}"
    }
   ]
  },
  {
   "title": "Bytes Received/Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{ins=\"$ins\"}[$interval])",
     "legendFormat": "Receive"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{ins=\"$ins\"}[$interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Content",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{ins=\"$ins\"}",
     "legendFormat": "Data Total"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{ins=\"$ins\"}",
     "legendFormat": "Data Dirty"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{ins=\"$ins\"}[$interval])",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{ins=\"$ins\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{ins=\"$ins\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{ins=\"$ins\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  {
   "title": "Top Command QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{ins=\"$ins\"}[$interval])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  }
 ]
}