{
 "title": "MYSQL Overview",
 "description": "MySQL Monitoring Home Dashboard",
 "tags": [
  "Pigsty",
  "MYSQL",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": "mysql" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,3m,5m,10m,30m,1h,2h,6h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "MySQL Instances",
   "type": "table",
   "description": "All instances in mysql cluster ${cls}",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "min by (cls,ins,ip) (mysql_up{job=\"$job\"})"
    },
    {
     "expr": "sum by (ins) (rate(mysql_global_status_queries{job=\"$job\"}[$interval]))"
    },
    {
     "expr": "sum by (ins) (rate(mysql_global_status_commands_total{job=\"$job\"}[$interval]))"
    },
    {
     "expr": "sum by (ins) (mysql_global_status_threads_connected{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (rate(mysql_global_status_queries{job=\"$job\"}[$interval]))",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Blue  = PostgreSQL\n\nPurple = Pgbouncer\n\nAzure : Patroni & PG Exporter",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " min by (ins) (mysql_up{job=\"mysql\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}