{
 "title": "CMDB Overview",
 "description": "PostgreSQL Catalog Explorer for Single Instance",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview",
  "PGSQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.node_summary Where is_meta;"
    }
   ]
  },
  {
   "title": "DCS Servers",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.key, d.value FROM pigsty.global_var v, jsonb_each_text(v.value) d WHERE v.key = 'dcs_servers'"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT cls, is_meta FROM pigsty.group"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nginx / Repo Address",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_var WHERE key\n    in ('nginx_port', 'repo_address', 'nginx_home', 'repo_name');"
    }
   ]
  },
  {
   "title": "Nginx Upstream",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT d ->> 'name'     AS name,\n       (d ->> 'domain') AS domain,\n       d ->> 'endpoint' AS endpoint\nFROM pigsty.global_var v,\n     jsonb_array_elements(v.value) d\nWHERE v.key = 'nginx_upstream';"
    }
   ]
  },
  {
   "title": "Nginx Index",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH nginx AS (\n    SELECT d ->> 'name'     AS name,\n           d ->> 'domain'   AS domain,\n           d ->> 'endpoint' AS endpoint\n    FROM pigsty.global_var v,\n         jsonb_array_elements(v.value) d\n    WHERE v.key = 'nginx_upstream'),\n     nginx_indexes AS (\n         SELECT d ->> 'name'    AS name,\n                d ->> 'url'     AS domain,\n                d ->> 'comment' AS comment\n         FROM pigsty.global_var v,\n              jsonb_array_elements(v.value) d\n         WHERE v.key = 'nginx_indexes')\nSELECT name,\n       comment,\n       case\n           when starts_with(domain, '/') THEN (SELECT 'http://' || domain FROM nginx WHERE name = 'home' LIMIT 1) ||\n                                              domain\n           ELSE replace(domain, '${grafana}', (SELECT 'http://' || domain FROM nginx WHERE name = 'grafana' LIMIT 1))\n           END AS url\nFROM nginx_indexes\n;"
    }
   ]
  },
  { "title": "DCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_var WHERE key\n    in ('consul_enabled', 'etcd_enabled');"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_var WHERE key\n    in ('dcs_name', 'dcs_registry');"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_var WHERE key\n    in ('dcs_safeguard', 'dcs_clean');"
    }
   ]
  },
  {
   "title": "PG DCS Type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  to_json(value) #>> '{}' AS \"DCS Type\" FROM pigsty.global_var WHERE key = 'pg_dcs_type';"
    }
   ]
  },
  {
   "title": "DCS Servers",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT d.key, d.value FROM pigsty.global_var v, jsonb_each_text(v.value) d WHERE v.key = 'dcs_servers'"
    }
   ]
  },
  {
   "title": "REPO & PKGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_var WHERE key\n    in ('node_repo_method', 'node_repo_remove');"
      }
     ]
    },
    {
     "title": "Node Repo URLs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT string_agg(d, ',')\nFROM pigsty.global_var v, jsonb_array_elements_text(v.value) d\nWHERE v.key = 'node_repo_local_urls';"
      }
     ]
    },
    {
     "title": "Repo Upstream",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT\n        d ->> 'name' AS name,\n        d ->> 'baseurl'  AS domain,\n        d ->> 'description' AS comment\nFROM pigsty.global_var v,\n     jsonb_array_elements(v.value) d\nWHERE v.key = 'repo_upstreams';"
      }
     ]
    },
    {
     "title": "Repo Packages",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_packages'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_url_packages';"
      }
     ]
    },
    {
     "title": "PGSQL Packages",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "rawSql": "WITH ver AS (SELECT  to_json(value) #>> '{}' AS \"version\" FROM pigsty.global_var WHERE key = 'pg_version' LIMIT 1)\nSELECT replace(pkg, '${pg_version}' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_var v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_packages'\nUNION ALL\nSELECT replace(pkg, '${pg_version}' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_var v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_extensions'"
      }
     ]
    },
    {
     "title": "Node Packages",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_packages_default'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_packages';"
      }
     ]
    },
    {
     "title": "Meta Packages",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_packages_meta'\nUNION ALL\nSELECT to_json(value) #>> '{}' AS \"DCS Type\" FROM pigsty.global_var WHERE key = 'node_packages_meta_pip';"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS / Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  to_json(value) #>> '{}' AS \"DNS Enabled\" FROM pigsty.global_var WHERE key = 'nameserver_enabled';"
      }
     ]
    },
    {
     "title": "DNS Records",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 4, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'dns_records';"
      }
     ]
    },
    {
     "title": "/etc/resolv.conf",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_dns_options'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_dns_servers';"
      }
     ]
    },
    {
     "title": "/etc/hosts",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_etc_hosts_default'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_var v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_etc_hosts';"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  to_json(value) #>> '{}' AS \"Node DNS Method\" FROM pigsty.global_var WHERE key = 'node_dns_method';"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Clusters",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_cluster"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Instance",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_instance"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Service",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_service;"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Database",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_database;"
      }
     ]
    }
   ]
  }
 ]
}