{
 "title": "DCS Overview",
 "description": "Dashboards for Consul & ETCD",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "ETCD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETCD Has Leader",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)", "legendFormat": "Has Leader" },
    { "expr": "sum(etcd_server_has_leader)", "legendFormat": "Members" }
   ]
  },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "etcd_server_is_leader", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{type=\"etcd\"}",
     "legendFormat": "{{ type }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "Rate Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total",
     "legendFormat": "{{instance}} Leader Change Seen"
    }
   ]
  },
  {
   "title": "Network RT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[2m]))",
     "legendFormat": "{{ ins }} -> {{ To }}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket [5m])) by (ins, le))",
     "legendFormat": "{{ ins }} WAL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket [5m])) by (ins, le))",
     "legendFormat": "{{ ins }} DB"
    }
   ]
  },
  {
   "title": "Proposal Committed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proposal Applied",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total[1m])\n",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total [1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_peer_received_bytes_total [1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total [1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_client_grpc_received_bytes_total [1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  {
   "title": "DB Size: db / quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes / etcd_server_quota_backend_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  { "title": "CONSUL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_autopilot_healthy", "legendFormat": "Consul Healthy" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{type=\"consul\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{type=\"consul\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{type=\"consul\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consul_consul_members_servers{type=\"consul\"})",
     "legendFormat": "Servers"
    },
    {
     "expr": "max(consul_consul_state_nodes{type=\"consul\"})",
     "legendFormat": "Nodes"
    },
    {
     "expr": "max(consul_consul_state_services{type=\"consul\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "max(consul_consul_state_service_instances{type=\"consul\"})",
     "legendFormat": "Svc Instances"
    },
    {
     "expr": "max(consul_consul_state_kv_entries{type=\"consul\"})",
     "legendFormat": "KVs"
    }
   ]
  },
  {
   "title": "Consul Leader Seen",
   "type": "timeseries",
   "description": "Shows the duration since an agent had last seen the leader. Spikes here may indicate network issues or a leader slowing or becoming unavailable.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact != 0",
     "legendFormat": "{{ quantile }}%"
    }
   ]
  },
  {
   "title": "Commit Time",
   "type": "timeseries",
   "description": "This measures the time it takes to commit a new entry to the Raft log on the leader.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "consul_raft_commitTime", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "timeseries",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "delta(consul_raft_apply[30s])", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "Dispatch Log Time",
   "type": "timeseries",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "consul_raft_leader_dispatchLog", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Consul UI Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "{src=\"nginx\", filename=\"/var/log/nginx/consul.log\"}"
    }
   ]
  }
 ]
}