{
 "title": "Infra Overview",
 "description": "Logs Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "pigsty" },
    { "expr": "1", "legendFormat": "metadb" },
    { "expr": "1", "legendFormat": "grafana" },
    { "expr": "1", "legendFormat": "prometheus" },
    { "expr": "1", "legendFormat": "alertmanager" },
    { "expr": "1", "legendFormat": "consul" },
    { "expr": "1", "legendFormat": "yum repo" }
   ]
  },
  { "title": "Infra Dashboards", "type": "dashlist", "gridPos": { "h": 13, "w": 5, "x": 19, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\"})",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Grafana Alert", "type": "alertlist", "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 } },
  {
   "title": "NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Syslog",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{job=\"nodes\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Error Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{src=\"postgres\"}  |~ \"ERROR\""
      }
     ]
    }
   ]
  },
  {
   "title": "REDIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{job=\"redis\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra - Nginx - Access",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time(({src=\"nginx-access\"})[$__interval]))",
       "legendFormat": "logs per $__interval"
      }
     ]
    },
    {
     "title": "Nginx Access Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{src=\"nginx-access\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra - Nginx - Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time(({src=\"nginx-error\"})[$__interval]))",
       "legendFormat": "logs per $__interval"
      }
     ]
    },
    {
     "title": "Nginx Error Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{src=\"nginx-error\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra - Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{src=\"grafana\"}"
      }
     ]
    }
   ]
  }
 ]
}