{
 "title": "Infra Overview",
 "description": "Logs Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "table",
   "description": "All nodes among environment ${job}",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (nodename,release,ip,ins,cls) (node_uname_info{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:space_usage_max{job=\"$job\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{job=\"$job\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{job=\"$job\"}) / 1000000000"
    },
    {
     "expr": "sum(node:fs:size_bytes{job=\"$job\"}) by (ip) / 1000000000"
    },
    {
     "expr": "count by (ip) (up{ip!=\"\"})"
    }
   ]
  },
  { "title": "LOGS Dashboard", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Infra - Nginx - Access",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time(({src=\"nginx-access\"})[$__interval]))",
       "legendFormat": "logs per $__interval"
      }
     ]
    },
    {
     "title": "Nginx Access Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{src=\"nginx-access\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra - Nginx - Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time(({src=\"nginx-error\"})[$__interval]))",
       "legendFormat": "logs per $__interval"
      }
     ]
    },
    {
     "title": "Nginx Error Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{src=\"nginx-error\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra - Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{src=\"grafana\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Syslog",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{job=\"nodes\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Error Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "{src=\"postgres\"}  |~ \"ERROR\""
      }
     ]
    }
   ]
  },
  {
   "title": "REDIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{job=\"redis\"}"
      }
     ]
    }
   ]
  }
 ]
}