{
 "title": "ETCD Overview",
 "description": "ETCD Service Overview",
 "tags": [
  "Pigsty",
  "ETCD",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_cluster_version, cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETCD Spec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(etcd_up{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Members"
    },
    {
     "expr": "ceil(count(etcd_up{job=\"etcd\", cls=\"$cls\"})/ 2 + 0.1)",
     "legendFormat": "Quorum"
    },
    {
     "expr": "count(etcd_up{job=\"etcd\", cls=\"$cls\"}) - ceil(count(etcd_up{job=\"etcd\", cls=\"$cls\"})/ 2 + 0.1)",
     "legendFormat": "Tolerance"
    }
   ]
  },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (ins,instance) (up{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD Member List",
   "type": "table",
   "description": "All instances among etcd cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"etcd\", cls=\"$cls\"}"
    },
    {
     "expr": "group by (ins,server_version) (etcd_server_version{job=\"etcd\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (etcd_server_is_leader{job=\"etcd\", cls=\"$cls\"} * 2 \n+ etcd_server_is_learner{job=\"etcd\", cls=\"$cls\"})"
    },
    {
     "expr": "etcd_server_id{job=\"etcd\", cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"etcd\", cls=\"$cls\"}) by (cls) /\n count(up{job=\"etcd\", cls=\"$cls\"}) by (cls)\nor on() vector(0)",
     "legendFormat": "ETCD Health"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"$cls\"}) or on() vector(0)",
     "legendFormat": "Has Leader"
    }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    },
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"$cls\"}) or on() vector(0)",
     "legendFormat": "ETCD Has Leader?"
    }
   ]
  },
  {
   "title": "Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}  @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network RT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"etcd\", cls=\"$cls\"}[2m]))",
     "legendFormat": "{{ ins }} -> {{ To }}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\", cls=\"$cls\"}[5m])) by (ins, le))",
     "legendFormat": "{{ ins }} WAL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\", cls=\"$cls\"}[5m])) by (ins, le))",
     "legendFormat": "{{ ins }} DB"
    }
   ]
  },
  {
   "title": "Proposal Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proposal Applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_peer_received_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "DB Size: db / quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"etcd\", cls=\"$cls\"} / etcd_server_quota_backend_bytes{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "ETCD Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,src) (count_over_time(({cls=\"$cls\", src=\"syslog\"} |~ \"etcd\")[$__interval]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "ETCD Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{cls=\"$cls\", src=\"syslog\"} |~ \"etcd\"",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}