{
 "title": "Infra Overview",
 "description": "Pigsty Infrastructure Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "pigsty" },
    { "expr": "1", "legendFormat": "cmdb" },
    { "expr": "1", "legendFormat": "grafana" },
    { "expr": "1", "legendFormat": "prometheus" },
    { "expr": "1", "legendFormat": "alertmanager" },
    { "expr": "1", "legendFormat": "loki" },
    { "expr": "1", "legendFormat": "etcd" },
    { "expr": "1", "legendFormat": "nginx" }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (type, instance) (up{job=\"infra\"})",
     "legendFormat": "{{ type }} {{ instance }}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Infra Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "up{job=\"infra\"}",
     "legendFormat": "{{ type }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "ALERT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"}) or on() vector(0)",
       "legendFormat": "Firing"
      },
      {
       "expr": "count(ALERTS{alertstate=\"pending\"})",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 2, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity)",
       "legendFormat": "{{ alertname }}"
      }
     ]
    },
    {
     "title": "Firing Alerts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\"})",
       "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
      }
     ]
    },
    { "title": "Grafana Alert", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 12 } },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ALERTS" }
     ]
    }
   ]
  },
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "Nginx Healthy @ {{ ip }}" }
   ]
  },
  {
   "title": "Nginx Conn Accept/Handle",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{}[5m])",
     "legendFormat": "{{ ip }} Accecpt"
    },
    {
     "expr": "irate(nginx_connections_handled{}[5m])",
     "legendFormat": "{{ ip }} Handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active{}", "legendFormat": "{{ ip }} active" },
    { "expr": "nginx_connections_reading{}", "legendFormat": "{{ ip }} reading" },
    { "expr": "nginx_connections_waiting{}", "legendFormat": "{{ ip }} waiting" },
    { "expr": "nginx_connections_writing{}", "legendFormat": "{{ ip }} writing" }
   ]
  },
  { "title": "PROMETHEUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "Prometheus {{ instance }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{type=\"prometheus\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{})",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{}[1m]))",
     "legendFormat": "Sample / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{})",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{type=\"prometheus\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_storage_blocks_bytes{})",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "grafana_build_info", "legendFormat": "Grafana {{ instance }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{type=\"grafana\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{}[1m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, grafana_frontend_boot_first_contentful_paint_time_seconds_bucket)",
     "legendFormat": "First Paint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, grafana_frontend_boot_load_time_seconds_bucket)",
     "legendFormat": "Render Full"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{type=\"grafana\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{type=\"grafana\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "LOKI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info", "legendFormat": "Loki {{ instance }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{type=\"loki\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "Bytes / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "Lines / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{type=\"loki\"})",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{type=\"loki\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{type=\"loki\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "ETCD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)", "legendFormat": "ETCD Healthy" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etcd_server_is_leader", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "up{job=\"etcd\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  }
 ]
}