{
 "title": "Logs Instance",
 "description": "Logs for Single Node/Instance",
 "tags": [
  "Pigsty",
  "INFRA",
  "Instance",
  "NODE",
  "PGSQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": "label_values(ins)" },
   {
    "name": "src",
    "label": "Source",
    "query": "label_values({ins=\"$ins\"}, src)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", src=\"$src\"})[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "Searched Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({ins=\"$ins\", src=\"$src\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{ins=\"$ins\", src=\"$src\"} |~ \"$search\""
    }
   ]
  }
 ]
}