{
 "title": "Nginx Overview",
 "description": "Nginx metrics, access log & error logs",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(nginx_http_requests_total, ins)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(nginx_http_requests_total{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Aliveness",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{ins=\"$ins\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} REQ/s"
    }
   ]
  },
  {
   "title": "Nginx Conn Accept/Handle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} Accecpt"
    },
    {
     "expr": "irate(nginx_connections_handled{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} Handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} active"
    },
    {
     "expr": "nginx_connections_reading{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} reading"
    },
    {
     "expr": "nginx_connections_waiting{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} waiting"
    },
    {
     "expr": "nginx_connections_writing{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} writing"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({src=\"nginx\", ip=\"$ip\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>`[1m])) ",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Lines by Server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(count_over_time(({src=\"nginx\", ip=\"$ip\"})[$__interval])) by (filename)",
     "legendFormat": "{{ filename }}"
    }
   ]
  },
  { "title": "Access Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({src=\"nginx\", ip=\"$ip\"})[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  {
   "title": "Nginx Access Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{src=\"nginx\", ip=\"$ip\"}"
    }
   ]
  },
  { "title": "Error Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({src=\"nginx-error\", ip=\"$ip\"})[$__interval]))",
     "legendFormat": "logs per $__interval"
    }
   ]
  },
  {
   "title": "Nginx Error Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{src=\"nginx-error\", ip=\"$ip\"}"
    }
   ]
  }
 ]
}