{
 "title": "Prometheus Overview",
 "description": "Pigsty Prometheus Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "Source", "query": "prometheus" },
   {
    "name": "ins",
    "label": "Prometheus",
    "query": {
     "query": "label_values(prometheus_build_info, ins)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(prometheus_build_info{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_build_info{ins=\"$ins\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{ins=\"$ins\"})",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(prometheus_tsdb_head_samples_appended_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "Sample / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"prometheus\", ins=\"$ins\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_http_requests_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ins=\"$ins\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{ins=\"$ins\"}",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Prometheus Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{src=\"nginx\", filename=\"/var/log/nginx/prometheus.log\", ip=\"$ip\"}"
    }
   ]
  },
  { "title": "Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_series_created_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Series+"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_removed_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Series-"
    },
    {
     "expr": "sum(prometheus_tsdb_head_series{ins=\"$ins\"})",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Head Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{ins=\"$ins\"})",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Series Churn",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "topk(10 , scrape_series_added{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_created_total{ins=\"$ins\"}[1m]) )",
     "legendFormat": "created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{ip=~\"$ip\"}[1m]) )",
     "legendFormat": "removed"
    }
   ]
  },
  { "title": "Sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_samples_appended_total{ins=\"$ins\"}",
     "legendFormat": "Samples"
    }
   ]
  },
  {
   "title": "Scrape Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{ins=\"$ins\"}",
     "legendFormat": "{{ job }}-{{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Sample Rate"
    }
   ]
  },
  { "title": "Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{ins=\"$ins\"})",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{ins=\"$ins\"}",
     "legendFormat": "{{ job }}-{{ instance }}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{ins=\"$ins\", config!=\"config-0\"}",
     "legendFormat": "{{ config }}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "topk(32 , scrape_duration_seconds{ins=\"$ins\"})"
    }
   ]
  },
  { "title": "Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Rule Evaluation Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_group_last_duration_seconds{ins=\"$ins\"}",
     "legendFormat": "{{ rule_group }}"
    }
   ]
  },
  {
   "title": "Rule Groups",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 54 },
   "targets": [
    {
     "expr": "sum by (rule_group) (prometheus_rule_group_rules{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (rule_group) (prometheus_rule_evaluations_total{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (rule_group) (prometheus_rule_group_interval_seconds{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (rule_group) (prometheus_rule_group_last_duration_seconds{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (rule_group) (prometheus_rule_group_last_evaluation_samples{ins=\"$ins\"})"
    },
    {
     "expr": "sum by (rule_group) (prometheus_rule_evaluation_failures_total{ins=\"$ins\"})"
    }
   ]
  }
 ]
}