{
 "title": "PGCAT Table",
 "description": "PostgreSQL Catalog Explorer for Tables",
 "tags": [
  "Pigsty",
  "PGCAT",
  "Database",
  "Table"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   {
    "name": "relname",
    "label": "Relation",
    "query": "SELECT nspname || '.' || relname FROM pg_namespace nsp JOIN pg_class rel ON nsp.oid = rel.relnamespace\nWHERE nspname NOT IN ('pg_catalog', 'monitor', 'information_schema','pg_toast') AND relkind = ANY(ARRAY['r', 'm', 't' ] );"
   },
   { "name": "nspname", "label": "Schema", "query": "SELECT '$relname';" },
   { "name": "tblname", "label": "Raw Relation", "query": "SELECT '$relname';" },
   {
    "name": "oid",
    "label": "Table OID",
    "query": "SELECT rel.oid AS oid FROM pg_namespace nsp JOIN pg_class rel ON nsp.oid = rel.relnamespace WHERE nspname = '${nspname}' AND relname = '${tblname}';"
   }
  ]
 },
 "panels": [
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database",
   "type": "stat",
   "description": "Database name",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Schema",
   "type": "stat",
   "description": "Schema Name",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Relation",
   "type": "stat",
   "description": "Relation Name",
   "gridPos": { "h": 2, "w": 9, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "Relation OID",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Relation Kind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT relkind FROM pg_class WHERE relname = '$tblname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n         SELECT relpages ::BIGINT,\n                (relpages * 8192::REAL)    AS relsize,\n                reltuples ::REAL,\n                age(relfrozenxid) ::BIGINT AS age\n         FROM pg_class c\n         WHERE oid = '${oid}'\n         LIMIT 1) a,\n     (\n         SELECT n_live_tup     AS live_tup,\n                n_dead_tup     AS dead_tup,\n                CASE\n                    WHEN (n_live_tup + n_dead_tup) > 0 THEN n_dead_tup::NUMERIC / (n_live_tup + n_dead_tup)\n                    ELSE 0 END AS dead_ratio\n         FROM pg_stat_user_tables\n         WHERE relid = '${oid}'\n         LIMIT 1\n     ) b;"
    },
    {
     "rawSql": "SELECT ratio AS \"Bloat Ratio\" FROM monitor.pg_table_bloat WHERE relname = '${tblname}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT oid, relnamespace, reltype, reloftype, relowner, relam, relfilenode, reltablespace, reltoastrelid FROM pg_class c WHERE oid = '$oid';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT relhasindex :: INTEGER, relispartition :: INTEGER, relisshared :: INTEGER, relhasrules :: INTEGER, relhastriggers :: INTEGER, relhassubclass :: INTEGER, relrowsecurity :: INTEGER, relforcerowsecurity :: INTEGER, relispopulated :: INTEGER FROM pg_class c WHERE oid = '${oid}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT relpages ::BIGINT, (relpages * 8192::REAL) AS relsize, reltuples ::REAL, relallvisible ::BIGINT, relnatts ::BIGINT, relchecks ::BIGINT, relfrozenxid, age(relfrozenxid) ::BIGINT AS age, relminmxid FROM pg_class c WHERE oid = '${oid}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \n   CASE relpersistence WHEN 'u' THEN 1 ELSE 0 END AS relunlogged,\n   CASE relpersistence WHEN 't' THEN 1 ELSE 0 END AS reltemporary\nFROM pg_class c WHERE oid = '${oid}'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT unnest(relacl) AS acl FROM pg_class c WHERE oid = '${oid}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT unnest(reloptions) AS opt FROM pg_class c WHERE oid = '${oid}';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT seq_scan,\n       seq_tup_read,\n       idx_scan,\n       idx_tup_fetch,\n       n_tup_ins,\n       n_tup_upd,\n       n_tup_del,\n       n_tup_hot_upd\nFROM pg_stat_user_tables\nWHERE relid = '$oid' LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT vacuum_count + autovacuum_count                   AS vacuum_total,\n       vacuum_count,\n       to_char(last_vacuum, 'YYYY-MM-DD HH24:MI:SS')     AS last_vacuum,\n       date_trunc('second', now() - last_vacuum)         AS since_last_vacuum,\n       autovacuum_count,\n       to_char(last_autovacuum, 'YYYY-MM-DD HH24:MI:SS') AS last_autovacuum,\n       date_trunc('second', now() - last_autovacuum)     AS since_last_autovacuum,\n       n_ins_since_vacuum\nFROM pg_stat_user_tables\nWHERE relid = '$oid'\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT analyze_count + autoanalyze_count                   AS analyze_total,\n       analyze_count,\n       to_char(last_analyze, 'YYYY-MM-DD HH24:MI:SS')     AS last_analyze,\n       date_trunc('second', now() - last_analyze)         AS since_last_analyze,\n       autoanalyze_count,\n       to_char(last_autoanalyze, 'YYYY-MM-DD HH24:MI:SS') AS last_autoanalyze,\n       date_trunc('second', now() - last_autoanalyze)     AS since_last_autoanalyze,\n       n_mod_since_analyze\nFROM pg_stat_user_tables\nWHERE relid = '${oid}'\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_statio_user_tables WHERE relid = '${oid}'"
    }
   ]
  },
  {
   "title": "Columns",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT *, pg_catalog.format_type(a.atttypid, a.atttypmod) AS atttype\nFROM pg_attribute a LEFT JOIN LATERAL (\n    SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid, true) AS def\n    FROM pg_catalog.pg_attrdef d\n    WHERE d.adrelid = a.attrelid\n      AND d.adnum = a.attnum\n      AND a.atthasdef\n    ) d ON true\nWHERE attrelid = '${oid}' AND attnum > 0 ORDER BY attnum;"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT *, pg_get_indexdef(indexrelid) AS def FROM pg_stat_user_indexes WHERE relid = '${oid}';"
    }
   ]
  }
 ]
}