{
 "title": "PGCAT Query",
 "description": "PostgreSQL Catalog Explorer for Query",
 "tags": [
  "Pigsty",
  "PGCAT",
  "Database",
  "Query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn}';" },
   {
    "name": "query",
    "label": "Query",
    "query": "SELECT distinct queryid::TEXT FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND userid != 10 LIMIT 1000;"
   },
   {
    "name": "qs",
    "query": "SELECT query FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' LIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. Formed as {{ cls }}-{{ seq }}. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Database name",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Query Identifier",
   "type": "stat",
   "description": "Query identifier generated from plan",
   "gridPos": { "h": 2, "w": 11, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Users list that runs this query",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT array_agg(u.usename)::TEXT\nFROM monitor.pg_stat_statements s LEFT OUTER JOIN pg_user u ON s.userid = u.usesysid\nWHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query';"
    }
   ]
  },
  {
   "title": "Query String",
   "type": "text",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 2 },
   "options": { "content": "```sql\n${qs}\n```" },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Statements Stat for ${query}",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT s.*, u.usename\nFROM monitor.pg_stat_statements s LEFT OUTER JOIN pg_user u ON s.userid = u.usesysid\nWHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query';"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Statements",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT queryid::TEXT AS qid, *\nFROM monitor.pg_stat_statements s\nWHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND\nuserid != 10 LIMIT 10;"
    }
   ]
  }
 ]
}